// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// src/idl/gen.cpp — C++ code generator: walks a dds::idl::Module tree and
// emits a self-contained C++ header (struct + `<Name>Codec` per IDL
// struct, `enum class` per IDL enum, `using` alias per IDL typedef).
//
// C++ port of go-DDS's tools/idl/gen.go, minus its TypedPublisher/
// TypedSubscriber factory-function emission (cpp-DDS has no dds::Codec<T>/
// TypedPublisher<T> abstraction to target -- see dds/idl/idl.hpp) and
// minus its PascalCase field-name conversion (C++ field/type names are
// emitted exactly as written in the IDL source -- both are deliberate,
// documented scope differences from the go-DDS reference generator).
//
// KNOWN SCOPE LIMITATION (matches go-DDS's own toGoName precedent, just
// with the identity function instead of PascalCase-conversion): an IDL
// field or type name that collides with a C++ keyword (e.g. a field
// literally named `class` or `template`) will produce a header that fails
// to compile. Not exercised by any DDS topic-type IDL in this repo's test
// suite; no escaping/mangling is attempted, matching this repo's
// established "port behavior, don't over-engineer past what the oracle
// itself handles" convention (go-DDS's own generator has the same
// unescaped-keyword gap, just for Go keywords instead of C++ ones).

#include "dds/idl/idl.hpp"

#include <algorithm>
#include <cctype>
#include <set>
#include <sstream>

namespace dds::idl {
namespace {

// GenerateFailure is thrown internally to unwind to the top-level entry
// point; never escapes generate().
struct GenerateFailure {
    std::string message;
};

class Generator {
public:
    explicit Generator(const Module& root) : root_(root) {}

    std::string generate() {
        std::string ns = namespace_name(root_);
        line("// Code generated by cpp-DDS ddstool (IDL compiler). DO NOT EDIT.");
        line("");
        line("#pragma once");
        line("");
        line("#include <array>");
        line("#include <cstdint>");
        line("#include <optional>");
        line("#include <string>");
        line("#include <vector>");
        line("");
        line("#include \"dds/cdr/cdr.hpp\"");
        line("");
        line("namespace " + ns + " {");
        line("");
        emit_module(root_);
        line("} // namespace " + ns);
        return out_;
    }

private:
    // ── Name / namespace helpers ─────────────────────────────────────────

    static std::string namespace_name(const Module& root) {
        if (root.name.empty()) {
            return "idlgen";
        }
        std::string lower = root.name;
        std::transform(lower.begin(), lower.end(), lower.begin(),
                        [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        return lower;
    }

    // bare_ref_name strips any module prefix from a qualified name.
    // "VehicleData::Speed" -> "Speed", "Speed" -> "Speed".
    static std::string bare_ref_name(const std::string& name) {
        auto pos = name.rfind("::");
        if (pos == std::string::npos) {
            return name;
        }
        return name.substr(pos + 2);
    }

    // ── Module-tree lookups (unscoped/global by design -- matches go-DDS's
    //    own searchStruct/searchEnum/searchTypedef, which resolve a bare
    //    name anywhere in the tree rather than enforcing real IDL lexical
    //    scoping) ────────────────────────────────────────────────────────

    static const Struct* search_struct(const Module& m, const std::string& name) {
        auto pos = name.find("::");
        if (pos != std::string::npos) {
            std::string mod_name = name.substr(0, pos);
            std::string rest = name.substr(pos + 2);
            for (const auto& sub : m.modules) {
                if (sub->name == mod_name) {
                    return search_struct(*sub, rest);
                }
            }
            return nullptr;
        }
        for (const auto& s : m.structs) {
            if (s.name == name) {
                return &s;
            }
        }
        for (const auto& sub : m.modules) {
            if (const Struct* s = search_struct(*sub, name)) {
                return s;
            }
        }
        return nullptr;
    }

    static const Enum* search_enum(const Module& m, const std::string& name) {
        auto pos = name.find("::");
        if (pos != std::string::npos) {
            std::string mod_name = name.substr(0, pos);
            std::string rest = name.substr(pos + 2);
            for (const auto& sub : m.modules) {
                if (sub->name == mod_name) {
                    return search_enum(*sub, rest);
                }
            }
            return nullptr;
        }
        for (const auto& e : m.enums) {
            if (e.name == name) {
                return &e;
            }
        }
        for (const auto& sub : m.modules) {
            if (const Enum* e = search_enum(*sub, name)) {
                return e;
            }
        }
        return nullptr;
    }

    static const Typedef* search_typedef(const Module& m, const std::string& name) {
        auto pos = name.find("::");
        if (pos != std::string::npos) {
            std::string mod_name = name.substr(0, pos);
            std::string rest = name.substr(pos + 2);
            for (const auto& sub : m.modules) {
                if (sub->name == mod_name) {
                    return search_typedef(*sub, rest);
                }
            }
            return nullptr;
        }
        for (const auto& td : m.typedefs) {
            if (td.name == name) {
                return &td;
            }
        }
        for (const auto& sub : m.modules) {
            if (const Typedef* td = search_typedef(*sub, name)) {
                return td;
            }
        }
        return nullptr;
    }

    const Struct* find_struct(const std::string& name) const { return search_struct(root_, name); }
    const Enum* find_enum(const std::string& name) const { return search_enum(root_, name); }
    const Typedef* find_typedef(const std::string& name) const { return search_typedef(root_, name); }

    // resolve_typedef expands a struct_-kind TypeSpec if its ref_name is a
    // typedef alias. Leaves all other TypeSpecs (and unresolved struct_
    // references) unchanged.
    TypeSpec resolve_typedef(TypeSpec ts) const {
        if (ts.kind != TypeKind::struct_) {
            return ts;
        }
        const Typedef* td = find_typedef(bare_ref_name(ts.ref_name));
        if (td == nullptr) {
            return ts;
        }
        return td->type;
    }

    // ── Type mapping ──────────────────────────────────────────────────────

    std::string cpp_type(TypeSpec ts) const {
        ts = resolve_typedef(ts);
        switch (ts.kind) {
            case TypeKind::boolean: return "bool";
            case TypeKind::octet: return "uint8_t";
            case TypeKind::short_: return "int16_t";
            case TypeKind::ushort: return "uint16_t";
            case TypeKind::long_: return "int32_t";
            case TypeKind::ulong: return "uint32_t";
            case TypeKind::long_long: return "int64_t";
            case TypeKind::ulong_long: return "uint64_t";
            case TypeKind::float_: return "float";
            case TypeKind::double_: return "double";
            case TypeKind::string: return "std::string";
            case TypeKind::sequence:
                if (!ts.elem_type) {
                    return "std::vector<uint8_t>";
                }
                if (ts.elem_type->kind == TypeKind::octet) {
                    return "std::vector<uint8_t>";
                }
                return "std::vector<" + cpp_type(*ts.elem_type) + ">";
            case TypeKind::array:
                if (!ts.elem_type) {
                    return "std::vector<uint8_t>";
                }
                return "std::array<" + cpp_type(*ts.elem_type) + ", " + std::to_string(ts.array_size) + ">";
            case TypeKind::struct_:
            case TypeKind::enum_:
                return bare_ref_name(ts.ref_name);
        }
        return "void*"; // unreachable
    }

    // ── Encode/decode statement generation ───────────────────────────────
    //
    // Every returned line is either:
    //   - a self-contained statement/one-liner (no net brace delta), or
    //   - a block opener, ending in exactly "{", or
    //   - a lone "}" block closer.
    // write_lines() below relies on that discipline to auto-indent.

    std::string next_tmp(const std::string& prefix) { return "_" + prefix + std::to_string(tmp_counter_++); }

    void append_encode(std::vector<std::string>& out, TypeSpec ts, const std::string& ref) {
        ts = resolve_typedef(ts);
        switch (ts.kind) {
            case TypeKind::boolean: out.push_back("e.write_bool(" + ref + ");"); return;
            case TypeKind::octet: out.push_back("e.write_uint8(" + ref + ");"); return;
            case TypeKind::short_: out.push_back("e.write_int16(" + ref + ");"); return;
            case TypeKind::ushort: out.push_back("e.write_uint16(" + ref + ");"); return;
            case TypeKind::long_: out.push_back("e.write_int32(" + ref + ");"); return;
            case TypeKind::ulong: out.push_back("e.write_uint32(" + ref + ");"); return;
            case TypeKind::long_long: out.push_back("e.write_int64(" + ref + ");"); return;
            case TypeKind::ulong_long: out.push_back("e.write_uint64(" + ref + ");"); return;
            case TypeKind::float_: out.push_back("e.write_float32(" + ref + ");"); return;
            case TypeKind::double_: out.push_back("e.write_float64(" + ref + ");"); return;
            case TypeKind::string: out.push_back("e.write_string(" + ref + ");"); return;
            case TypeKind::sequence: {
                if (!ts.elem_type) {
                    throw GenerateFailure{"cannot encode " + ref + ": sequence has no element type"};
                }
                if (ts.elem_type->kind == TypeKind::octet) {
                    out.push_back("e.write_bytes(" + ref + ");");
                    return;
                }
                out.push_back("e.write_uint32(static_cast<uint32_t>(" + ref + ".size()));");
                std::string elem_var = next_tmp("elem");
                out.push_back("for (const auto& " + elem_var + " : " + ref + ") {");
                append_encode(out, *ts.elem_type, elem_var);
                out.push_back("}");
                return;
            }
            case TypeKind::array: {
                if (!ts.elem_type) {
                    throw GenerateFailure{"cannot encode " + ref + ": array has no element type"};
                }
                std::string elem_var = next_tmp("elem");
                out.push_back("for (const auto& " + elem_var + " : " + ref + ") {");
                append_encode(out, *ts.elem_type, elem_var);
                out.push_back("}");
                return;
            }
            case TypeKind::struct_:
            case TypeKind::enum_: {
                if (find_enum(ts.ref_name) != nullptr) {
                    out.push_back("e.write_int32(static_cast<int32_t>(" + ref + "));");
                    return;
                }
                const Struct* s = find_struct(ts.ref_name);
                if (s == nullptr) {
                    throw GenerateFailure{"cannot encode " + ref + ": unknown struct " + ts.ref_name};
                }
                std::string bare = bare_ref_name(ts.ref_name);
                if (visited_.count(bare) != 0) {
                    throw GenerateFailure{"cannot encode " + ref + ": cyclic struct " + ts.ref_name};
                }
                visited_.insert(bare);
                for (const auto& f : s->fields) {
                    append_encode(out, f.type, ref + "." + f.name);
                }
                visited_.erase(bare);
                return;
            }
        }
        throw GenerateFailure{"cannot encode " + ref + ": unsupported type"};
    }

    void append_decode(std::vector<std::string>& out, TypeSpec ts, const std::string& dest) {
        ts = resolve_typedef(ts);
        switch (ts.kind) {
            case TypeKind::boolean: append_primitive_decode(out, "read_bool", dest); return;
            case TypeKind::octet: append_primitive_decode(out, "read_uint8", dest); return;
            case TypeKind::short_: append_primitive_decode(out, "read_int16", dest); return;
            case TypeKind::ushort: append_primitive_decode(out, "read_uint16", dest); return;
            case TypeKind::long_: append_primitive_decode(out, "read_int32", dest); return;
            case TypeKind::ulong: append_primitive_decode(out, "read_uint32", dest); return;
            case TypeKind::long_long: append_primitive_decode(out, "read_int64", dest); return;
            case TypeKind::ulong_long: append_primitive_decode(out, "read_uint64", dest); return;
            case TypeKind::float_: append_primitive_decode(out, "read_float32", dest); return;
            case TypeKind::double_: append_primitive_decode(out, "read_float64", dest); return;
            case TypeKind::string: append_primitive_decode(out, "read_string", dest); return;
            case TypeKind::sequence: {
                if (!ts.elem_type) {
                    throw GenerateFailure{"cannot decode " + dest + ": sequence has no element type"};
                }
                if (ts.elem_type->kind == TypeKind::octet) {
                    append_primitive_decode(out, "read_bytes", dest);
                    return;
                }
                std::string n_var = next_tmp("n");
                out.push_back("auto " + n_var + " = d->read_uint32();");
                out.push_back("if (!" + n_var + ") { return std::nullopt; }");
                out.push_back(dest + ".resize(*" + n_var + ");");
                std::string elem_var = next_tmp("elem");
                out.push_back("for (auto& " + elem_var + " : " + dest + ") {");
                append_decode(out, *ts.elem_type, elem_var);
                out.push_back("}");
                return;
            }
            case TypeKind::array: {
                if (!ts.elem_type) {
                    throw GenerateFailure{"cannot decode " + dest + ": array has no element type"};
                }
                std::string elem_var = next_tmp("elem");
                out.push_back("for (auto& " + elem_var + " : " + dest + ") {");
                append_decode(out, *ts.elem_type, elem_var);
                out.push_back("}");
                return;
            }
            case TypeKind::struct_:
            case TypeKind::enum_: {
                if (const Enum* en = find_enum(ts.ref_name); en != nullptr) {
                    std::string ev_var = next_tmp("ev");
                    out.push_back("auto " + ev_var + " = d->read_int32();");
                    out.push_back("if (!" + ev_var + ") { return std::nullopt; }");
                    out.push_back(dest + " = static_cast<" + bare_ref_name(ts.ref_name) + ">(*" + ev_var + ");");
                    return;
                }
                const Struct* s = find_struct(ts.ref_name);
                if (s == nullptr) {
                    throw GenerateFailure{"cannot decode " + dest + ": unknown struct " + ts.ref_name};
                }
                std::string bare = bare_ref_name(ts.ref_name);
                if (visited_.count(bare) != 0) {
                    throw GenerateFailure{"cannot decode " + dest + ": cyclic struct " + ts.ref_name};
                }
                visited_.insert(bare);
                for (const auto& f : s->fields) {
                    append_decode(out, f.type, dest + "." + f.name);
                }
                visited_.erase(bare);
                return;
            }
        }
        throw GenerateFailure{"cannot decode " + dest + ": unsupported type"};
    }

    void append_primitive_decode(std::vector<std::string>& out, const std::string& reader,
                                  const std::string& dest) {
        std::string var = next_tmp("f");
        out.push_back("auto " + var + " = d->" + reader + "();");
        out.push_back("if (!" + var + ") { return std::nullopt; }");
        out.push_back(dest + " = *" + var + ";");
    }

    // ── Emission ──────────────────────────────────────────────────────────

    void emit_module(const Module& m) {
        for (const auto& td : m.typedefs) {
            emit_typedef(td);
        }
        for (const auto& e : m.enums) {
            emit_enum(e);
        }
        for (const auto& s : m.structs) {
            emit_struct(s);
        }
        for (const auto& sub : m.modules) {
            // Sub-module structs are emitted in the same namespace for
            // simplicity, matching go-DDS's own emitModule recursion.
            emit_module(*sub);
        }
    }

    void emit_typedef(const Typedef& td) {
        line("// " + td.name + " is a type alias generated from IDL typedef " + td.name + ".");
        line("using " + td.name + " = " + cpp_type(td.type) + ";");
        line("");
    }

    void emit_enum(const Enum& e) {
        line("// " + e.name + " is generated from IDL enum " + e.name + ".");
        line("enum class " + e.name + " : int32_t {");
        for (std::size_t i = 0; i < e.values.size(); ++i) {
            line("    " + e.values[i] + " = " + std::to_string(i) + ",");
        }
        line("};");
        line("");
    }

    void emit_struct(const Struct& s) {
        line("// " + s.name + " is generated from IDL struct " + s.name + ".");
        line("struct " + s.name + " {");
        for (const auto& f : s.fields) {
            line("    " + cpp_type(f.type) + " " + f.name + "{};");
        }
        line("};");
        line("");
        emit_codec(s);
    }

    void emit_codec(const Struct& s) {
        std::string codec_name = s.name + "Codec";
        line("// " + codec_name + " encodes/decodes " + s.name + " using CDR/XCDR1 (dds::cdr).");
        line("struct " + codec_name + " {");
        line("    static std::vector<uint8_t> marshal(const " + s.name + "& v) {");
        line("        dds::cdr::Encoder e;");
        for (const auto& f : s.fields) {
            std::vector<std::string> stmts;
            append_encode(stmts, f.type, "v." + f.name);
            write_lines(stmts, 2);
        }
        line("        return e.bytes();");
        line("    }");
        line("");
        line("    static std::optional<" + s.name + "> unmarshal(const std::vector<uint8_t>& data) {");
        line("        auto d = dds::cdr::Decoder::create(data);");
        line("        if (!d) { return std::nullopt; }");
        line("        " + s.name + " v;");
        for (const auto& f : s.fields) {
            std::vector<std::string> stmts;
            append_decode(stmts, f.type, "v." + f.name);
            write_lines(stmts, 2);
        }
        line("        return v;");
        line("    }");
        line("");
        std::vector<std::string> key_fields;
        for (const auto& f : s.fields) {
            if (f.key) {
                key_fields.push_back(f.name);
            }
        }
        line("    // key_fields returns the field names marked @key in the IDL source.");
        line("    static std::vector<std::string> key_fields() {");
        if (key_fields.empty()) {
            line("        return {};");
        } else {
            std::string joined;
            for (std::size_t i = 0; i < key_fields.size(); ++i) {
                if (i != 0) {
                    joined += ", ";
                }
                joined += "\"" + key_fields[i] + "\"";
            }
            line("        return { " + joined + " };");
        }
        line("    }");
        line("};");
        line("");
    }

    // ── Low-level output ──────────────────────────────────────────────────

    void line(const std::string& s) {
        if (s.empty()) {
            out_ += "\n";
            return;
        }
        out_ += s + "\n";
    }

    // write_lines appends stmts (already produced by append_encode/
    // append_decode) at base_indent levels of 4-space indentation, tracking
    // brace nesting incrementally: a line ending in exactly "{" increases
    // the indent for subsequent lines; a lone "}" line first decreases,
    // then is written at the new (shallower) level.
    void write_lines(const std::vector<std::string>& stmts, int base_indent) {
        int indent = base_indent;
        for (const auto& raw : stmts) {
            int this_indent = indent;
            bool is_closer = (raw == "}");
            if (is_closer) {
                --this_indent;
            }
            out_ += std::string(static_cast<std::size_t>(this_indent) * 4, ' ') + raw + "\n";
            if (!raw.empty() && raw.back() == '{') {
                indent = this_indent + 1;
            } else if (is_closer) {
                indent = this_indent;
            } else {
                indent = this_indent;
            }
        }
    }

    const Module& root_;
    std::string out_;
    std::set<std::string> visited_;
    int tmp_counter_{0};
};

} // namespace

GenerateResult generate(const Module& m) {
    GenerateResult result;
    try {
        Generator g(m);
        result.source = g.generate();
    } catch (const GenerateFailure& f) {
        result.error = f.message;
    }
    return result;
}

} // namespace dds::idl
