// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Tests for dds::xtypes — a C++ port of github.com/SoundMatt/go-DDS's
// `xtypes` package (tools/xtypes/xtypes.go / xtypes_test.go), the
// correctness oracle named in cpp-DDS's ROADMAP.md ("Tier 3 — xtypes,
// tsn, idl, cdr", `xtypes`).
//
// fusa:test REQ-XTYPE-001 REQ-XTYPE-002 REQ-XTYPE-003 REQ-XTYPE-004
// fusa:test REQ-XTYPE-005 REQ-XTYPE-006 REQ-TREG-001 REQ-TREG-002
// fusa:test REQ-TREG-003
//
// ── How every *_CANONICAL_JSON / *_HASH_HEX constant below was derived ───────
//
// go-DDS's xtypes.canonical()/canonicalField() are unexported, so — exactly
// as test_rtps_cdr.cpp and test_safety_e2e.cpp do for their own packages —
// the vectors were generated by calling those *actual* functions white-box,
// from a scratch _test.go file placed temporarily inside a fresh clone of
// go-DDS's tools/xtypes package (never committed to go-DDS, never pushed
// anywhere):
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS/tools/xtypes
//   cat > zzz_scratch_cppdds_vectors_test.go <<'EOF'
//   package xtypes
//
//   import (
//       "encoding/hex"
//       "encoding/json"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSXTypesReferenceVectors(t *testing.T) {
//       print1 := func(label string, td *TypeDescriptor) {
//           b, err := json.Marshal(canonical(td))
//           if err != nil { t.Fatal(err) }
//           id := Identify(td)
//           fmt.Printf("%s_CANONICAL_JSON = %s\n", label, string(b))
//           fmt.Printf("%s_HASH_HEX = %s\n", label, hex.EncodeToString(id.Hash[:]))
//       }
//       // ... one TypeDescriptor literal + print1(...) call per vector below.
//   }
//   EOF
//   go test . -run TestPrintCppDDSXTypesReferenceVectors -v
//
// Reproduced 2026-07-27 against go-DDS commit 1272f294de25bbe5ed6d840e488e0130d30a1adb.
// Raw captured output:
//
//   VEHICLE_SPEED_CANONICAL_JSON = {"fields":[{"kind":"float64","name":"kmh","optional":false},{"kind":"string","name":"unit","optional":true}],"name":"VehicleSpeed","version":1}
//   VEHICLE_SPEED_HASH_HEX = e3e6843cefcdbb5c
//   VEHICLE_SPEED_REORDERED_CANONICAL_JSON = {"fields":[{"kind":"float64","name":"kmh","optional":false},{"kind":"string","name":"unit","optional":true}],"name":"VehicleSpeed","version":1}
//   VEHICLE_SPEED_REORDERED_HASH_HEX = e3e6843cefcdbb5c
//   EMPTY_CANONICAL_JSON = {"fields":[],"name":"Empty","version":0}
//   EMPTY_HASH_HEX = 44d8fa4ee9a4d7bf
//   POINT_STRUCT_CANONICAL_JSON = {"fields":[{"fields":[{"kind":"float64","name":"x","optional":false},{"kind":"float64","name":"y","optional":false}],"kind":"struct","name":"position","optional":false}],"name":"Point","version":0}
//   POINT_STRUCT_HASH_HEX = 05e2b4d3dafa8816
//   BATCH_SEQ_CANONICAL_JSON = {"fields":[{"element":{"kind":"float64","name":"item","optional":false},"kind":"seq","name":"items","optional":false}],"name":"Batch","version":0}
//   BATCH_SEQ_HASH_HEX = 6c411b4dc24b2024
//   ALL_KINDS_CANONICAL_JSON = {"fields":[{"kind":"bool","name":"b","optional":false},{"kind":"bytes","name":"by","optional":true},{"kind":"float64","name":"f64","optional":false},{"kind":"int32","name":"i32","optional":false},{"kind":"int64","name":"i64","optional":false},{"kind":"string","name":"s","optional":false}],"name":"AllKinds","version":7}
//   ALL_KINDS_HASH_HEX = b275e59b018b485d
//   ESCAPED_NAME_CANONICAL_JSON = {"fields":[{"kind":"bool","name":"tab\there","optional":false}],"name":"Weird\"Na\\me<T>&Co","version":0}
//   ESCAPED_NAME_HASH_HEX = 5c90f3ef3f90b7c9

#include <dds/xtypes/xtypes.hpp>
#include <catch2/catch_test_macros.hpp>

using namespace dds::xtypes;

namespace {

TypeDescriptor speed_desc() {
    TypeDescriptor td;
    td.name    = "VehicleSpeed";
    td.version = 1;
    td.fields  = {
        FieldDescriptor{"kmh", TypeKind::Float64, false, {}, nullptr},
        FieldDescriptor{"unit", TypeKind::String, true, {}, nullptr},
    };
    return td;
}

} // namespace

// ── TypeKind::to_string ────────────────────────────────────────────────────

TEST_CASE("to_string(TypeKind): all named kinds plus out-of-range fallback",
          "[xtypes][REQ-XTYPE-001]") {
    CHECK(to_string(TypeKind::Bool) == "bool");
    CHECK(to_string(TypeKind::Int32) == "int32");
    CHECK(to_string(TypeKind::Int64) == "int64");
    CHECK(to_string(TypeKind::Float64) == "float64");
    CHECK(to_string(TypeKind::String) == "string");
    CHECK(to_string(TypeKind::Bytes) == "bytes");
    CHECK(to_string(TypeKind::Struct) == "struct");
    CHECK(to_string(TypeKind::Seq) == "seq");
    CHECK(to_string(static_cast<TypeKind>(99)) == "TypeKind(99)");
}

// ── canonical_json / identify — byte-exact against go-DDS reference vectors ──

TEST_CASE("identify: VehicleSpeed matches go-DDS canonical JSON and hash",
          "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor td = speed_desc();
    CHECK(detail::canonical_json(td) ==
          "{\"fields\":[{\"kind\":\"float64\",\"name\":\"kmh\",\"optional\":false},"
          "{\"kind\":\"string\",\"name\":\"unit\",\"optional\":true}],"
          "\"name\":\"VehicleSpeed\",\"version\":1}");
    auto id = identify(td);
    CHECK(id.name == "VehicleSpeed");
    // e3e6843cefcdbb5c
    std::array<uint8_t, 8> want{0xe3, 0xe6, 0x84, 0x3c, 0xef, 0xcd, 0xbb, 0x5c};
    CHECK(id.hash == want);
}

TEST_CASE("identify: field declaration order does not affect canonical JSON or hash",
          "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor reordered;
    reordered.name    = "VehicleSpeed";
    reordered.version = 1;
    reordered.fields  = {
        FieldDescriptor{"unit", TypeKind::String, true, {}, nullptr},
        FieldDescriptor{"kmh", TypeKind::Float64, false, {}, nullptr},
    };
    CHECK(detail::canonical_json(reordered) == detail::canonical_json(speed_desc()));
    CHECK(identify(reordered).hash == identify(speed_desc()).hash);
}

TEST_CASE("identify: empty-fields descriptor emits \"fields\":[] not null",
          "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor td;
    td.name = "Empty";
    CHECK(detail::canonical_json(td) == "{\"fields\":[],\"name\":\"Empty\",\"version\":0}");
    std::array<uint8_t, 8> want{0x44, 0xd8, 0xfa, 0x4e, 0xe9, 0xa4, 0xd7, 0xbf};
    CHECK(identify(td).hash == want);
}

TEST_CASE("identify: nested struct field", "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor point;
    point.name   = "Point";
    point.fields = {FieldDescriptor{
        "position", TypeKind::Struct, false,
        {FieldDescriptor{"x", TypeKind::Float64, false, {}, nullptr},
         FieldDescriptor{"y", TypeKind::Float64, false, {}, nullptr}},
        nullptr}};
    CHECK(detail::canonical_json(point) ==
          "{\"fields\":[{\"fields\":[{\"kind\":\"float64\",\"name\":\"x\",\"optional\":false},"
          "{\"kind\":\"float64\",\"name\":\"y\",\"optional\":false}],\"kind\":\"struct\","
          "\"name\":\"position\",\"optional\":false}],\"name\":\"Point\",\"version\":0}");
    std::array<uint8_t, 8> want{0x05, 0xe2, 0xb4, 0xd3, 0xda, 0xfa, 0x88, 0x16};
    CHECK(identify(point).hash == want);
}

TEST_CASE("identify: sequence field with element descriptor", "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor batch;
    batch.name   = "Batch";
    auto element = std::make_shared<FieldDescriptor>(
        FieldDescriptor{"item", TypeKind::Float64, false, {}, nullptr});
    batch.fields = {FieldDescriptor{"items", TypeKind::Seq, false, {}, element}};
    CHECK(detail::canonical_json(batch) ==
          "{\"fields\":[{\"element\":{\"kind\":\"float64\",\"name\":\"item\",\"optional\":false},"
          "\"kind\":\"seq\",\"name\":\"items\",\"optional\":false}],\"name\":\"Batch\",\"version\":0}");
    std::array<uint8_t, 8> want{0x6c, 0x41, 0x1b, 0x4d, 0xc2, 0x4b, 0x20, 0x24};
    CHECK(identify(batch).hash == want);
}

TEST_CASE("identify: every primitive TypeKind plus an optional bytes field",
          "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor td;
    td.name    = "AllKinds";
    td.version = 7;
    td.fields  = {
        FieldDescriptor{"b", TypeKind::Bool, false, {}, nullptr},
        FieldDescriptor{"i32", TypeKind::Int32, false, {}, nullptr},
        FieldDescriptor{"i64", TypeKind::Int64, false, {}, nullptr},
        FieldDescriptor{"f64", TypeKind::Float64, false, {}, nullptr},
        FieldDescriptor{"s", TypeKind::String, false, {}, nullptr},
        FieldDescriptor{"by", TypeKind::Bytes, true, {}, nullptr},
    };
    CHECK(detail::canonical_json(td) ==
          "{\"fields\":[{\"kind\":\"bool\",\"name\":\"b\",\"optional\":false},"
          "{\"kind\":\"bytes\",\"name\":\"by\",\"optional\":true},"
          "{\"kind\":\"float64\",\"name\":\"f64\",\"optional\":false},"
          "{\"kind\":\"int32\",\"name\":\"i32\",\"optional\":false},"
          "{\"kind\":\"int64\",\"name\":\"i64\",\"optional\":false},"
          "{\"kind\":\"string\",\"name\":\"s\",\"optional\":false}],"
          "\"name\":\"AllKinds\",\"version\":7}");
    std::array<uint8_t, 8> want{0xb2, 0x75, 0xe5, 0x9b, 0x01, 0x8b, 0x48, 0x5d};
    CHECK(identify(td).hash == want);
}

TEST_CASE("identify: JSON string escaping (quote, backslash, tab, HTML-unsafe chars)",
          "[xtypes][wire][REQ-XTYPE-002]") {
    TypeDescriptor td;
    td.name   = "Weird\"Na\\me<T>&Co";
    td.fields = {FieldDescriptor{"tab\there", TypeKind::Bool, false, {}, nullptr}};
    CHECK(detail::canonical_json(td) ==
          "{\"fields\":[{\"kind\":\"bool\",\"name\":\"tab\\there\",\"optional\":false}],"
          "\"name\":\"Weird\\\"Na\\\\me\\u003cT\\u003e\\u0026Co\",\"version\":0}");
    std::array<uint8_t, 8> want{0x5c, 0x90, 0xf3, 0xef, 0x3f, 0x90, 0xb7, 0xc9};
    CHECK(identify(td).hash == want);
}

// ── identify — behavioral (mirrors go-DDS's xtypes_test.go) ─────────────────

TEST_CASE("identify: deterministic for the same descriptor", "[xtypes][REQ-XTYPE-002]") {
    TypeDescriptor td = speed_desc();
    CHECK(identify(td).hash == identify(td).hash);
}

TEST_CASE("identify: different type names produce different hashes", "[xtypes][REQ-XTYPE-002]") {
    TypeDescriptor a;
    a.name   = "TypeA";
    a.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    TypeDescriptor b;
    b.name   = "TypeB";
    b.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    CHECK(identify(a).hash != identify(b).hash);
}

TEST_CASE("identify: different nested struct field names change the hash",
          "[xtypes][REQ-XTYPE-002]") {
    TypeDescriptor nested;
    nested.name   = "Point";
    nested.fields = {FieldDescriptor{
        "position", TypeKind::Struct, false,
        {FieldDescriptor{"x", TypeKind::Float64, false, {}, nullptr},
         FieldDescriptor{"y", TypeKind::Float64, false, {}, nullptr}},
        nullptr}};
    TypeDescriptor different;
    different.name   = "Point";
    different.fields = {FieldDescriptor{
        "position", TypeKind::Struct, false,
        {FieldDescriptor{"x", TypeKind::Float64, false, {}, nullptr},
         FieldDescriptor{"z", TypeKind::Float64, false, {}, nullptr}},
        nullptr}};
    CHECK(identify(nested).hash != identify(different).hash);
}

TEST_CASE("identify: different sequence element kind changes the hash", "[xtypes][REQ-XTYPE-002]") {
    auto elemF = std::make_shared<FieldDescriptor>(
        FieldDescriptor{"item", TypeKind::Float64, false, {}, nullptr});
    auto elemS =
        std::make_shared<FieldDescriptor>(FieldDescriptor{"item", TypeKind::String, false, {}, nullptr});
    TypeDescriptor withSeq;
    withSeq.name   = "Batch";
    withSeq.fields = {FieldDescriptor{"items", TypeKind::Seq, false, {}, elemF}};
    TypeDescriptor withDiff;
    withDiff.name   = "Batch";
    withDiff.fields = {FieldDescriptor{"items", TypeKind::Seq, false, {}, elemS}};
    CHECK(identify(withSeq).hash != identify(withDiff).hash);
}

// ── new_type_object ───────────────────────────────────────────────────────

TEST_CASE("new_type_object: sets a non-zero content-addressed id", "[xtypes][REQ-XTYPE-005]") {
    TypeDescriptor td = speed_desc();
    auto           to = new_type_object(td);
    CHECK(to->id.name == td.name);
    CHECK(to->id.hash != std::array<uint8_t, 8>{});
    CHECK(to->descriptor.name == td.name);
}

// ── DynamicData ───────────────────────────────────────────────────────────

TEST_CASE("DynamicData: set/get round-trips a declared field", "[xtypes][REQ-XTYPE-003]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    REQUIRE_FALSE(d.set("kmh", Value::of_double(120.0)));
    auto v = d.get("kmh");
    REQUIRE(v.has_value());
    CHECK(v->as_double() == 120.0);
}

TEST_CASE("DynamicData: set on an unknown field returns ErrUnknownField", "[xtypes][REQ-XTYPE-003]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK(d.set("nonexistent", Value::of_int64(1)) == ErrUnknownField());
}

TEST_CASE("DynamicData: get on a declared-but-unset field returns nullopt", "[xtypes][REQ-XTYPE-003]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK_FALSE(d.get("kmh").has_value());
}

TEST_CASE("DynamicData: type_descriptor returns the backing pointer", "[xtypes][REQ-XTYPE-003]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK(d.type_descriptor() == &td);
}

TEST_CASE("DynamicData: to_json emits set fields with sorted keys", "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    REQUIRE_FALSE(d.set("unit", Value::of_string("kmh")));
    REQUIRE_FALSE(d.set("kmh", Value::of_double(99.5)));
    // std::map key order: "kmh" < "unit".
    CHECK(d.to_json() == "{\"kmh\":99.5,\"unit\":\"kmh\"}");
}

TEST_CASE("DynamicData: from_json round-trips through to_json", "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    REQUIRE_FALSE(d.set("kmh", Value::of_double(80.0)));
    REQUIRE_FALSE(d.set("unit", Value::of_string("kmh")));
    auto json = d.to_json();

    DynamicData d2(&td);
    REQUIRE_FALSE(d2.from_json(json));
    auto v = d2.get("kmh");
    REQUIRE(v.has_value());
    // JSON numbers always unmarshal as Value::Kind::Double, matching Go's
    // json.Unmarshal-into-`any` behavior exactly.
    REQUIRE(v->as_double().has_value());
    CHECK(v->as_double().value() == 80.0);
}

TEST_CASE("DynamicData: from_json ignores unknown fields (forward compatibility)",
          "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    std::string    raw = R"({"kmh":50,"unit":"kmh","future_field":true})";
    REQUIRE_FALSE(d.from_json(raw));
    CHECK_FALSE(d.get("future_field").has_value());
    auto kmh = d.get("kmh");
    REQUIRE(kmh.has_value());
    CHECK(kmh->as_double().value() == 50.0);
}

TEST_CASE("DynamicData: from_json rejects malformed JSON", "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK(d.from_json("{not-json}") == ErrInvalidJSON());
}

TEST_CASE("DynamicData: from_json rejects a non-object top level", "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK(d.from_json("[1,2,3]") == ErrInvalidJSON());
    CHECK(d.from_json("42") == ErrInvalidJSON());
}

TEST_CASE("DynamicData: from_json validates the whole document even under an unknown key",
          "[xtypes][REQ-XTYPE-004]") {
    // "future_field"'s value is malformed; even though it would be skipped
    // (unknown field), Go's json.Unmarshal(&raw map[string]json.RawMessage)
    // parses the whole document up front, so the call still fails overall.
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    CHECK(d.from_json(R"({"kmh":1,"future_field":not_valid})") == ErrInvalidJSON());
}

TEST_CASE("DynamicData: from_json skips (does not store) a nested object under a declared field",
          "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td = speed_desc();
    DynamicData    d(&td);
    REQUIRE_FALSE(d.from_json(R"({"kmh":{"nested":true},"unit":"kmh"})"));
    CHECK_FALSE(d.get("kmh").has_value());
    CHECK(d.get("unit")->as_string() != nullptr);
}

TEST_CASE("DynamicData: Bytes field serializes to base64 on to_json (Go []byte marshal quirk)",
          "[xtypes][REQ-XTYPE-004]") {
    TypeDescriptor td;
    td.name   = "WithBytes";
    td.fields = {FieldDescriptor{"data", TypeKind::Bytes, false, {}, nullptr}};
    DynamicData d(&td);
    REQUIRE_FALSE(d.set("data", Value::of_bytes({0x01, 0x02, 0x03})));
    CHECK(d.to_json() == "{\"data\":\"AQID\"}");
}

// ── TypeRegistry ──────────────────────────────────────────────────────────

TEST_CASE("TypeRegistry: register then lookup", "[xtypes][REQ-TREG-001]") {
    TypeRegistry r;
    TypeDescriptor td = speed_desc();
    auto           to = new_type_object(td);
    REQUIRE_FALSE(r.register_type(to));
    auto got = r.lookup("VehicleSpeed");
    REQUIRE(got != nullptr);
    CHECK(got->id == to->id);
}

TEST_CASE("TypeRegistry: re-registering an identical TypeObject is a no-op",
          "[xtypes][REQ-TREG-002]") {
    TypeRegistry r;
    TypeDescriptor td = speed_desc();
    auto           to = new_type_object(td);
    REQUIRE_FALSE(r.register_type(to));
    CHECK_FALSE(r.register_type(to));
}

TEST_CASE("TypeRegistry: registering a name conflict with a different hash fails",
          "[xtypes][REQ-TREG-002]") {
    TypeRegistry r;
    TypeDescriptor td1;
    td1.name    = "MyType";
    td1.version = 1;
    td1.fields  = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    REQUIRE_FALSE(r.register_type(new_type_object(td1)));

    TypeDescriptor td2;
    td2.name    = "MyType";
    td2.version = 2;
    td2.fields  = {FieldDescriptor{"x", TypeKind::String, false, {}, nullptr}};
    CHECK(r.register_type(new_type_object(td2)) == ErrTypeMismatch());
}

TEST_CASE("TypeRegistry: lookup of an unregistered name returns nullptr", "[xtypes][REQ-TREG-001]") {
    TypeRegistry r;
    CHECK(r.lookup("Nonexistent") == nullptr);
}

TEST_CASE("TypeRegistry: all() returns a name-sorted snapshot", "[xtypes][REQ-TREG-003]") {
    TypeRegistry r;
    for (const char* name : {"Ztype", "Atype", "Mtype"}) {
        TypeDescriptor td;
        td.name = name;
        REQUIRE_FALSE(r.register_type(new_type_object(td)));
    }
    auto all = r.all();
    REQUIRE(all.size() == 3);
    CHECK(all[0]->id.name == "Atype");
    CHECK(all[1]->id.name == "Mtype");
    CHECK(all[2]->id.name == "Ztype");
}

// ── check_compatibility ───────────────────────────────────────────────────

TEST_CASE("check_compatibility: identical descriptor is compatible with itself",
          "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor td  = speed_desc();
    auto           res = check_compatibility(td, td);
    CHECK(res.compatible);
}

TEST_CASE("check_compatibility: added optional field is compatible", "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor writer;
    writer.name   = "T";
    writer.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    TypeDescriptor reader;
    reader.name   = "T";
    reader.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr},
                      FieldDescriptor{"y", TypeKind::Int32, true, {}, nullptr}};
    CHECK(check_compatibility(writer, reader).compatible);
}

TEST_CASE("check_compatibility: added required field missing from writer is incompatible",
          "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor writer;
    writer.name   = "T";
    writer.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    TypeDescriptor reader;
    reader.name   = "T";
    reader.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr},
                      FieldDescriptor{"y", TypeKind::Int32, false, {}, nullptr}};
    CHECK_FALSE(check_compatibility(writer, reader).compatible);
}

TEST_CASE("check_compatibility: optional field absent from writer is compatible",
          "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor writer;
    writer.name   = "T";
    writer.fields = {FieldDescriptor{"kmh", TypeKind::Float64, false, {}, nullptr}};
    TypeDescriptor reader;
    reader.name   = "T";
    reader.fields = {FieldDescriptor{"kmh", TypeKind::Float64, false, {}, nullptr},
                      FieldDescriptor{"unit", TypeKind::String, true, {}, nullptr}};
    CHECK(check_compatibility(writer, reader).compatible);
}

TEST_CASE("check_compatibility: field kind mismatch is incompatible", "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor writer;
    writer.name   = "T";
    writer.fields = {FieldDescriptor{"speed", TypeKind::Int32, false, {}, nullptr}};
    TypeDescriptor reader;
    reader.name   = "T";
    reader.fields = {FieldDescriptor{"speed", TypeKind::Float64, false, {}, nullptr}};
    CHECK_FALSE(check_compatibility(writer, reader).compatible);
}

TEST_CASE("check_compatibility: extra writer field is forward-compatible", "[xtypes][REQ-XTYPE-006]") {
    TypeDescriptor writer;
    writer.name   = "T";
    writer.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr},
                      FieldDescriptor{"extra", TypeKind::String, false, {}, nullptr}};
    TypeDescriptor reader;
    reader.name   = "T";
    reader.fields = {FieldDescriptor{"x", TypeKind::Int32, false, {}, nullptr}};
    CHECK(check_compatibility(writer, reader).compatible);
}
