// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Tests for Tier-1 phase 7, "Reliable delivery — HEARTBEAT/ACKNACK" (see
// ROADMAP.md). Three groups:
//
//  1. Byte-exact wire compatibility for Heartbeat/AckNack/Gap::encode
//     against github.com/SoundMatt/go-DDS's marshalHeartbeat/marshalAckNack/
//     marshalGAP — the correctness oracle named in cpp-DDS's ROADMAP.md.
//
//     ── How every *_HEX constant below was derived ──────────────────────
//
//     go-DDS's marshal* functions are unexported, so — following the exact
//     precedent set by tests/test_rtps_types.cpp and tests/test_rtps_sedp.cpp
//     — the vectors were generated by calling those *actual* functions
//     white-box, from a scratch _test.go file placed temporarily inside a
//     fresh clone of go-DDS's rtps package (never committed to go-DDS,
//     never pushed anywhere):
//
//       git clone https://github.com/SoundMatt/go-DDS.git
//       cd go-DDS
//       cat > rtps/zzz_scratch_reliable_vectors_test.go <<'EOF'
//       package rtps
//
//       import (
//           "encoding/hex"
//           "fmt"
//           "testing"
//       )
//
//       func TestPrintCppDDSReliableReferenceVectors(t *testing.T) {
//           readerEID := EntityId{0x00, 0x00, 0x00, 0x04}
//           writerEID := EntityId{0x00, 0x00, 0x42, 0x03}
//
//           hb := Heartbeat{
//               ReaderEntityId: readerEID,
//               WriterEntityId: writerEID,
//               FirstSN:        SequenceNumber{High: 0, Low: 1},
//               LastSN:         SequenceNumber{High: 0, Low: 5},
//               Count:          7,
//           }
//           fmt.Println("HEARTBEAT_SAMPLE_HEX =", hex.EncodeToString(marshalHeartbeat(hb)))
//
//           an := AckNack{
//               ReaderEntityId: readerEID,
//               WriterEntityId: writerEID,
//               Base:           SequenceNumber{High: 0, Low: 3},
//               Bitmap:         0x0000000B, // bits 0,1,3 set -> SNs 3,4,6 missing
//               Count:          9,
//           }
//           fmt.Println("ACKNACK_SAMPLE_HEX =", hex.EncodeToString(marshalAckNack(an)))
//
//           g := Gap{
//               ReaderEntityId: readerEID,
//               WriterEntityId: writerEID,
//               GapStart:       SequenceNumber{High: 0, Low: 3},
//               GapEnd:         SequenceNumber{High: 0, Low: 5},
//           }
//           fmt.Println("GAP_SAMPLE_HEX =", hex.EncodeToString(marshalGAP(g)))
//
//           prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//           fmt.Println("HEARTBEAT_FULL_MESSAGE_HEX =", hex.EncodeToString(wrapInRTPSMessage(prefix, marshalHeartbeat(hb))))
//       }
//       EOF
//       go test ./rtps -run TestPrintCppDDSReliableReferenceVectors -v
//
//     That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//       HEARTBEAT_SAMPLE_HEX       = 07011c0000000004000042030000000001000000000000000500000007000000
//       ACKNACK_SAMPLE_HEX         = 06011c0000000004000042030000000003000000200000000b00000009000000
//       GAP_SAMPLE_HEX             = 08011c0000000004000042030000000003000000000000000600000000000000
//       HEARTBEAT_FULL_MESSAGE_HEX = 5254505302030127010f996ecafebabe0000000107011c0000000004000042030000000001000000000000000500000007000000
//
//  2. Ordinary behavioral unit tests for RecvTracker (reliable.hpp) — no
//     golden vector requirement, see that header's own file-level scope
//     note for why.
//
//  3. End-to-end behavioral tests driving a real dds::rtps::Participant
//     over real loopback UDP, with a raw UdpSocket standing in for the
//     remote peer (matching the existing "Participant's bridge loop
//     announces existing local endpoints to a newly discovered peer" test
//     pattern in test_rtps_participant.cpp) — proving the actual
//     production code path: HEARTBEAT-after-write-and-periodic,
//     ACKNACK-on-detected-gap (from both a DATA arrival and a HEARTBEAT),
//     and retransmit-or-GAP-from-history on receipt of ACKNACK.

#include <catch2/catch_test_macros.hpp>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

#include <dds/rtps/participant.hpp>
#include <dds/rtps/persist.hpp>
#include <dds/rtps/reliable.hpp>

using namespace dds;
using namespace dds::rtps;
using namespace std::chrono_literals;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

EntityId sample_reader_entity() { return EntityId{{0x00, 0x00, 0x00, 0x04}}; }
EntityId sample_writer_entity() { return EntityId{{0x00, 0x00, 0x42, 0x03}}; }
GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}

// Creates a fresh, uniquely-named directory under the OS temp dir for one
// test's persist_load/persist_flush round-trip, standing in for go-DDS's
// t.TempDir() (Catch2 has no built-in equivalent). Not cleaned up
// automatically — matches Go's own t.TempDir() only in spirit, not in
// cleanup guarantees, but this is test-local, disposable scratch space.
std::string make_temp_dir(const std::string& name) {
    static std::atomic<uint64_t> counter{0};
    auto path = std::filesystem::temp_directory_path() /
                ("cppdds_test_" + name + "_" + std::to_string(counter.fetch_add(1)) + "_" +
                 std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
    std::filesystem::create_directories(path);
    return path.string();
}

} // namespace

// ── 1. Byte-exact wire vectors ───────────────────────────────────────────────

TEST_CASE("Heartbeat::encode matches go-DDS reference vector", "[rtps][reliable]") {
    Heartbeat hb;
    hb.reader_entity_id = sample_reader_entity();
    hb.writer_entity_id = sample_writer_entity();
    hb.first_sn           = SequenceNumber{0, 1};
    hb.last_sn             = SequenceNumber{0, 5};
    hb.count                = 7;

    std::vector<uint8_t> out;
    hb.encode(out);
    CHECK(to_hex(out) == "07011c0000000004000042030000000001000000000000000500000007000000");
}

TEST_CASE("Heartbeat::decode round-trips the reference vector", "[rtps][reliable]") {
    auto bytes = hex_to_bytes("07011c0000000004000042030000000001000000000000000500000007000000");
    auto hb    = Heartbeat::decode(bytes.data(), bytes.size());
    REQUIRE(hb.has_value());
    CHECK(hb->reader_entity_id == sample_reader_entity());
    CHECK(hb->writer_entity_id == sample_writer_entity());
    CHECK(hb->first_sn == SequenceNumber{0, 1});
    CHECK(hb->last_sn == SequenceNumber{0, 5});
    CHECK(hb->count == 7);

    std::vector<uint8_t> re_encoded;
    hb->encode(re_encoded);
    CHECK(re_encoded == bytes);
}

TEST_CASE("Heartbeat::decode rejects short/malformed buffers", "[rtps][reliable]") {
    std::array<uint8_t, 3> too_short{};
    CHECK_FALSE(Heartbeat::decode(too_short.data(), too_short.size()).has_value());

    auto wrong_id = hex_to_bytes("06011c0000000004000042030000000001000000000000000500000007000000");
    CHECK_FALSE(Heartbeat::decode(wrong_id.data(), wrong_id.size()).has_value());

    auto truncated_body = hex_to_bytes("07011c00000000040000420300000000010000000000000005000000");
    CHECK_FALSE(Heartbeat::decode(truncated_body.data(), truncated_body.size()).has_value());
}

TEST_CASE("full RTPS message wrapping a Heartbeat matches go-DDS reference vector", "[rtps][reliable]") {
    Heartbeat hb;
    hb.reader_entity_id = sample_reader_entity();
    hb.writer_entity_id = sample_writer_entity();
    hb.first_sn           = SequenceNumber{0, 1};
    hb.last_sn             = SequenceNumber{0, 5};
    hb.count                = 7;

    std::vector<uint8_t> submsg;
    hb.encode(submsg);
    auto full = wrap_in_rtps_message(sample_prefix(), kVendorIdGoDDS, submsg);
    CHECK(to_hex(full) ==
          "5254505302030127010f996ecafebabe0000000107011c0000000004000042030000000001000000000000000500000007"
          "000000");
}

TEST_CASE("AckNack::encode matches go-DDS reference vector", "[rtps][reliable]") {
    AckNack an;
    an.reader_entity_id = sample_reader_entity();
    an.writer_entity_id = sample_writer_entity();
    an.base                = SequenceNumber{0, 3};
    an.bitmap               = 0x0000000B; // bits 0,1,3 set -> SNs 3,4,6 missing
    an.count                = 9;

    std::vector<uint8_t> out;
    an.encode(out);
    CHECK(to_hex(out) == "06011c0000000004000042030000000003000000200000000b00000009000000");
}

TEST_CASE("AckNack::decode round-trips the reference vector", "[rtps][reliable]") {
    auto bytes = hex_to_bytes("06011c0000000004000042030000000003000000200000000b00000009000000");
    auto an    = AckNack::decode(bytes.data(), bytes.size());
    REQUIRE(an.has_value());
    CHECK(an->reader_entity_id == sample_reader_entity());
    CHECK(an->writer_entity_id == sample_writer_entity());
    CHECK(an->base == SequenceNumber{0, 3});
    CHECK(an->bitmap == 0x0000000Bu);
    CHECK(an->count == 9);

    std::vector<uint8_t> re_encoded;
    an->encode(re_encoded);
    CHECK(re_encoded == bytes);
}

TEST_CASE("AckNack::decode rejects short/malformed buffers", "[rtps][reliable]") {
    std::array<uint8_t, 3> too_short{};
    CHECK_FALSE(AckNack::decode(too_short.data(), too_short.size()).has_value());

    auto wrong_id = hex_to_bytes("07011c0000000004000042030000000003000000200000000b00000009000000");
    CHECK_FALSE(AckNack::decode(wrong_id.data(), wrong_id.size()).has_value());
}

TEST_CASE("Gap::encode matches go-DDS reference vector", "[rtps][reliable]") {
    Gap g;
    g.reader_entity_id = sample_reader_entity();
    g.writer_entity_id = sample_writer_entity();
    g.gap_start           = SequenceNumber{0, 3};
    g.gap_end              = SequenceNumber{0, 5};

    std::vector<uint8_t> out;
    g.encode(out);
    CHECK(to_hex(out) == "08011c0000000004000042030000000003000000000000000600000000000000");
}

// ── 2. RecvTracker behavioral unit tests ─────────────────────────────────────

TEST_CASE("RecvTracker: sn_to_u64/u64_to_sn round-trip without 32-bit aliasing", "[rtps][reliable]") {
    constexpr uint64_t high = uint64_t(1) << 33;
    auto                sn   = u64_to_sn(high + 1);
    CHECK(sn_to_u64(sn) == high + 1);
    CHECK(sn_to_u64(u64_to_sn(1)) == 1u);
}

TEST_CASE("RecvTracker: record on first contact anchors expected at that SN", "[rtps][reliable]") {
    RecvTracker t;
    CHECK(t.record(5));
    auto [base, bitmap, need_ack] = t.missing(5);
    CHECK(base == 6); // 5 consumed, watermark advanced past it
    CHECK(bitmap == 0);
    CHECK_FALSE(need_ack);
}

TEST_CASE("RecvTracker: init_expected seeds the watermark and is a no-op afterward", "[rtps][reliable]") {
    RecvTracker t;
    t.init_expected(10);
    auto [base1, bitmap1, need1] = t.missing(9);
    CHECK(base1 == 10);
    CHECK_FALSE(need1); // last_sn < base -> fully caught up
    (void)bitmap1;

    t.init_expected(999); // no-op: tracker already initialized
    auto [base2, bitmap2, need2] = t.missing(10);
    CHECK(base2 == 10);
    CHECK(bitmap2 == 1u); // SN 10 itself missing
    CHECK(need2);
}

TEST_CASE("RecvTracker: a gap is reported via the bitmap and re-NACKed until filled", "[rtps][reliable]") {
    RecvTracker t;
    t.init_expected(1);
    CHECK(t.record(1));
    CHECK(t.record(3)); // gap at 2
    CHECK(t.record(4));

    auto [base, bitmap, need_ack] = t.missing(4);
    CHECK(base == 2);
    CHECK(bitmap == 0b001u); // only bit 0 (SN 2) missing
    CHECK(need_ack);

    // Re-querying without filling the gap re-reports the same NACK, matching
    // go-DDS's "re-NACKed on every HEARTBEAT until it arrives" contract.
    auto [base2, bitmap2, need_ack2] = t.missing(4);
    CHECK(base2 == 2);
    CHECK(bitmap2 == 0b001u);
    CHECK(need_ack2);

    // Filling the gap advances the watermark past the buffered successors.
    CHECK(t.record(2));
    auto [base3, bitmap3, need_ack3] = t.missing(4);
    CHECK(base3 == 5);
    CHECK(bitmap3 == 0);
    CHECK_FALSE(need_ack3);
}

TEST_CASE("RecvTracker: record returns false for already-delivered or already-buffered SNs",
          "[rtps][reliable]") {
    RecvTracker t;
    t.init_expected(1);
    CHECK(t.record(1));
    CHECK_FALSE(t.record(1)); // already delivered (below watermark)
    CHECK(t.record(3));       // buffered ahead
    CHECK_FALSE(t.record(3)); // already buffered
}

TEST_CASE("RecvTracker: missing caps the reported window at 32 bits", "[rtps][reliable]") {
    RecvTracker t;
    t.init_expected(0);
    auto [base, bitmap, need_ack] = t.missing(1000);
    CHECK(base == 0);
    CHECK(need_ack);
    CHECK(bitmap == 0xFFFFFFFFu); // all 32 bits in [0,31] missing
}

TEST_CASE("RecvTracker: missing on an uninitialized tracker reports no gap", "[rtps][reliable]") {
    RecvTracker t;
    auto [base, bitmap, need_ack] = t.missing(5);
    CHECK(base == 0);
    CHECK(bitmap == 0);
    CHECK_FALSE(need_ack);
}

TEST_CASE("RecvTracker: next_ack_count is monotonically increasing", "[rtps][reliable]") {
    RecvTracker t;
    CHECK(t.next_ack_count() == 1);
    CHECK(t.next_ack_count() == 2);
    CHECK(t.next_ack_count() == 3);
}

// ── persist_load / persist_flush round-trip tests ────────────────────────────
// Mirrors go-DDS's rtps/persist_test.go behavioral coverage.

TEST_CASE("persist_load returns nullopt when dir is empty", "[rtps][persist]") {
    CHECK_FALSE(persist_load("", "any/topic").has_value());
}

TEST_CASE("persist_flush is a no-op when dir is empty", "[rtps][persist]") {
    persist_flush("", "any/topic", {1, 2, 3}); // must not throw/crash
    SUCCEED();
}

TEST_CASE("persist_flush silently ignores an invalid directory", "[rtps][persist]") {
    persist_flush("/nonexistent/dir/for/cppdds/tests", "any/topic", {1, 2, 3}); // must not throw/crash
    SUCCEED();
}

TEST_CASE("persist round-trip reproduces the original payload", "[rtps][persist]") {
    const std::string dir = make_temp_dir("cppdds_persist_roundtrip");
    std::vector<uint8_t> want{'h', 'e', 'l', 'l', 'o'};
    persist_flush(dir, "test/topic", want);
    auto got = persist_load(dir, "test/topic");
    REQUIRE(got.has_value());
    CHECK(*got == want);
}

TEST_CASE("persist_load returns nullopt for a missing file", "[rtps][persist]") {
    const std::string dir = make_temp_dir("cppdds_persist_missing");
    CHECK_FALSE(persist_load(dir, "no/such/topic").has_value());
}

TEST_CASE("persist_path replaces unsafe path characters", "[rtps][reliable]") {
    auto path = persist_path("/tmp/data", "a/b:c\\d");
    for (char ch : {'/', ':', '\\'}) {
        // Only check the basename portion (after the last real separator we
        // introduced via the dir argument) so "/tmp/data" itself doesn't
        // trip the '/' check.
        auto pos = path.find("topic-");
        REQUIRE(pos != std::string::npos);
        CHECK(path.find(ch, pos) == std::string::npos);
    }
}

// ── 3. End-to-end reliable delivery over real loopback UDP ──────────────────

namespace {

// Registers a fake remote writer (writer_prefix/writer_eid) as SEDP-matched
// to every local reader on topic_name, standing in for a peer participant
// that has already been discovered — matching the existing
// "SedpService::matched_reader_locators_for_topic filters by topic and
// dedupes" test's pattern of feeding SedpService::handle_packet directly.
void announce_fake_remote_writer(Participant& p, const GuidPrefix& writer_prefix, const EntityId& writer_eid,
                                  const std::string& topic_name, uint16_t writer_data_port) {
    auto data = build_endpoint_data(EndpointInfo{GUID{writer_prefix, writer_eid}, topic_name, true},
                                     writer_data_port);
    auto announcement = build_sedp_announcement(writer_prefix, kVendorIdCppDDS, kEntityIdSEDPPubWriter,
                                                 kEntityIdSEDPPubReader, SequenceNumber{0, 1}, data);
    p.sedp().handle_packet(announcement, "127.0.0.1");
}

// Registers a fake remote reader as SEDP-matched to a local writer on
// topic_name, with its data-receive locator pointing at reader_data_port
// (typically a raw UdpSocket standing in for the remote reader).
void announce_fake_remote_reader(Participant& p, const GuidPrefix& reader_prefix, const EntityId& reader_eid,
                                  const std::string& topic_name, uint16_t reader_data_port) {
    auto data = build_endpoint_data(EndpointInfo{GUID{reader_prefix, reader_eid}, topic_name, false},
                                     reader_data_port);
    auto announcement = build_sedp_announcement(reader_prefix, kVendorIdCppDDS, kEntityIdSEDPSubWriter,
                                                 kEntityIdSEDPSubReader, SequenceNumber{0, 1}, data);
    p.sedp().handle_packet(announcement, "127.0.0.1");
}

// Sends a DATA submessage for seq/payload, addressed as if from
// (writer_prefix, writer_eid), to dst_port on 127.0.0.1 via sock.
void send_fake_data(UdpSocket& sock, const GuidPrefix& writer_prefix, const EntityId& writer_eid, uint64_t seq,
                     const std::vector<uint8_t>& payload, int dst_port) {
    DataSubmessage ds;
    ds.reader_entity_id = kEntityIdUnknown;
    ds.writer_entity_id = writer_eid;
    ds.seq_num            = u64_to_sn(seq);
    ds.payload             = cdr_wrap_payload(payload);
    std::vector<uint8_t> submsg;
    ds.encode(submsg);
    auto msg = wrap_in_rtps_message(writer_prefix, kVendorIdCppDDS, submsg);
    sock.send_to("127.0.0.1", dst_port, msg.data(), msg.size());
}

// Polls sock for up to ~3s for a datagram whose first submessage id (at
// Header::kSize, i.e. byte 20) equals want_submessage_id.
std::optional<UdpPacket> recv_submessage(UdpSocket& sock, uint8_t want_submessage_id) {
    for (int attempt = 0; attempt < 60; ++attempt) {
        auto pkt = sock.recv();
        if (pkt && pkt->data.size() > Header::kSize && pkt->data[Header::kSize] == want_submessage_id) {
            return pkt;
        }
    }
    return std::nullopt;
}

} // namespace

TEST_CASE("Reliable reader NACKs a gap detected from a DATA arrival and delivers the retransmit",
          "[rtps][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode = true;
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto [sub, sub_ec] = p->new_subscriber("RelTopic", reliable_qos());
    REQUIRE_FALSE(sub_ec);

    auto fake_writer_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_writer_sock.has_value());
    const GuidPrefix fake_writer_prefix{{0xF1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_writer_eid = entity_id_for_writer(1);

    announce_fake_remote_writer(*p, fake_writer_prefix, fake_writer_eid, "RelTopic",
                                 static_cast<uint16_t>(fake_writer_sock->port()));

    auto ch = sub->channel();

    // SN 1 arrives normally.
    send_fake_data(*fake_writer_sock, fake_writer_prefix, fake_writer_eid, 1, {0xAA}, p->data_unicast_port());
    auto s1 = ch->recv_until(std::chrono::steady_clock::now() + 3s);
    REQUIRE(s1.has_value());
    CHECK(s1->sequence_number == 1);

    // SN 2 is "lost" (never sent). SN 3 arrives next, exposing the gap.
    send_fake_data(*fake_writer_sock, fake_writer_prefix, fake_writer_eid, 3, {0xCC}, p->data_unicast_port());
    auto s3 = ch->recv_until(std::chrono::steady_clock::now() + 3s);
    REQUIRE(s3.has_value());
    CHECK(s3->sequence_number == 3);

    // The reader must have sent an ACKNACK back to the fake writer's socket
    // requesting SN 2.
    auto ack_pkt = recv_submessage(*fake_writer_sock, kSubmessageIdAckNack);
    REQUIRE(ack_pkt.has_value());
    auto an = AckNack::decode(ack_pkt->data.data() + Header::kSize, ack_pkt->data.size() - Header::kSize);
    REQUIRE(an.has_value());
    CHECK(sn_to_u64(an->base) == 2u);
    CHECK((an->bitmap & 0x1u) == 0x1u); // bit 0 (SN 2) set

    // Simulate the writer's retransmission of SN 2.
    send_fake_data(*fake_writer_sock, fake_writer_prefix, fake_writer_eid, 2, {0xBB}, p->data_unicast_port());
    auto s2 = ch->recv_until(std::chrono::steady_clock::now() + 3s);
    REQUIRE(s2.has_value());
    CHECK(s2->sequence_number == 2);
    CHECK(s2->payload == std::vector<uint8_t>{0xBB});

    p->close();
}

TEST_CASE("Reliable reader NACKs a gap on HEARTBEAT even without new DATA", "[rtps][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode = true;
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto [sub, sub_ec] = p->new_subscriber("HbTopic", reliable_qos());
    REQUIRE_FALSE(sub_ec);

    auto fake_writer_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_writer_sock.has_value());
    const GuidPrefix fake_writer_prefix{{0xF2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_writer_eid = entity_id_for_writer(1);

    announce_fake_remote_writer(*p, fake_writer_prefix, fake_writer_eid, "HbTopic",
                                 static_cast<uint16_t>(fake_writer_sock->port()));

    // A HEARTBEAT advertising [1,3] with no prior DATA at all: the reader
    // anchors its watermark at FirstSN=1 and must NACK the whole range.
    Heartbeat hb;
    hb.reader_entity_id = kEntityIdUnknown;
    hb.writer_entity_id = fake_writer_eid;
    hb.first_sn           = SequenceNumber{0, 1};
    hb.last_sn             = SequenceNumber{0, 3};
    hb.count                = 1;
    std::vector<uint8_t> submsg;
    hb.encode(submsg);
    auto msg = wrap_in_rtps_message(fake_writer_prefix, kVendorIdCppDDS, submsg);
    fake_writer_sock->send_to("127.0.0.1", p->data_unicast_port(), msg.data(), msg.size());

    auto ack_pkt = recv_submessage(*fake_writer_sock, kSubmessageIdAckNack);
    REQUIRE(ack_pkt.has_value());
    auto an = AckNack::decode(ack_pkt->data.data() + Header::kSize, ack_pkt->data.size() - Header::kSize);
    REQUIRE(an.has_value());
    CHECK(sn_to_u64(an->base) == 1u);
    CHECK(an->bitmap == 0b111u); // SNs 1,2,3 all missing

    p->close();
}

TEST_CASE("Reliable writer sends HEARTBEAT after every write and periodically", "[rtps][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode         = true;
    opts.heartbeat_period   = 40ms; // fast periodic tick for the test
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto fake_reader_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_reader_sock.has_value());
    const GuidPrefix fake_reader_prefix{{0xF3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_reader_eid = entity_id_for_reader(1);

    auto [pub, pub_ec] = p->new_publisher("HbWriterTopic", reliable_qos());
    REQUIRE_FALSE(pub_ec);

    announce_fake_remote_reader(*p, fake_reader_prefix, fake_reader_eid, "HbWriterTopic",
                                 static_cast<uint16_t>(fake_reader_sock->port()));

    CHECK_FALSE(pub->write(std::vector<uint8_t>{1, 2, 3}));

    // The immediate post-write HEARTBEAT.
    auto hb_pkt = recv_submessage(*fake_reader_sock, kSubmessageIdHeartbeat);
    REQUIRE(hb_pkt.has_value());
    auto hb = Heartbeat::decode(hb_pkt->data.data() + Header::kSize, hb_pkt->data.size() - Header::kSize);
    REQUIRE(hb.has_value());
    CHECK(sn_to_u64(hb->first_sn) == 1u);
    CHECK(sn_to_u64(hb->last_sn) == 1u);
    // count is >= 1 rather than pinned to exactly 1: the background
    // periodic-heartbeat thread starts at writer construction and could in
    // principle race the immediate post-write heartbeat for who increments
    // hb_count_ first (though never before the first write, since history
    // is empty and send_heartbeat() no-ops until then).
    CHECK(hb->count >= 1);

    // A second, periodic HEARTBEAT with a higher count, without any new write.
    auto hb_pkt2 = recv_submessage(*fake_reader_sock, kSubmessageIdHeartbeat);
    REQUIRE(hb_pkt2.has_value());
    auto hb2 = Heartbeat::decode(hb_pkt2->data.data() + Header::kSize, hb_pkt2->data.size() - Header::kSize);
    REQUIRE(hb2.has_value());
    CHECK(hb2->count > hb->count);

    p->close();
}

TEST_CASE("Reliable writer retransmits a NACKed sample from history on ACKNACK",
          "[rtps][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode = true;
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto fake_reader_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_reader_sock.has_value());
    const GuidPrefix fake_reader_prefix{{0xF4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_reader_eid = entity_id_for_reader(1);

    auto [pub, pub_ec] = p->new_publisher("RetransmitTopic", reliable_qos());
    REQUIRE_FALSE(pub_ec);

    announce_fake_remote_reader(*p, fake_reader_prefix, fake_reader_eid, "RetransmitTopic",
                                 static_cast<uint16_t>(fake_reader_sock->port()));

    CHECK_FALSE(pub->write(std::vector<uint8_t>{0xDE, 0xAD}));
    // Drain the post-write HEARTBEAT so it doesn't get mistaken for the
    // retransmit DATA below.
    REQUIRE(recv_submessage(*fake_reader_sock, kSubmessageIdHeartbeat).has_value());

    // Find the publisher's own writer EntityId the way the rest of this
    // suite does: entity_id_for_writer(1) is the first writer this
    // participant allocates.
    const EntityId writer_eid = entity_id_for_writer(1);

    AckNack an;
    an.reader_entity_id = fake_reader_eid;
    an.writer_entity_id = writer_eid;
    an.base                = SequenceNumber{0, 1};
    an.bitmap               = 0x1u; // SN 1 missing
    an.count                = 1;
    std::vector<uint8_t> submsg;
    an.encode(submsg);
    auto msg = wrap_in_rtps_message(fake_reader_prefix, kVendorIdCppDDS, submsg);
    fake_reader_sock->send_to("127.0.0.1", p->data_unicast_port(), msg.data(), msg.size());

    auto retransmit_pkt = recv_submessage(*fake_reader_sock, kSubmessageIdData);
    REQUIRE(retransmit_pkt.has_value());
    auto ds = DataSubmessage::decode(retransmit_pkt->data.data() + Header::kSize,
                                      retransmit_pkt->data.size() - Header::kSize);
    REQUIRE(ds.has_value());
    CHECK(sn_to_u64(ds->seq_num) == 1u);
    auto raw = cdr_unwrap_payload(ds->payload);
    REQUIRE(raw.has_value());
    CHECK(*raw == std::vector<uint8_t>{0xDE, 0xAD});

    p->close();
}

TEST_CASE("Reliable writer sends GAP for a NACKed range already evicted from history",
          "[rtps][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode      = true;
    opts.history_depth   = 4; // force fast eviction
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto fake_reader_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_reader_sock.has_value());
    const GuidPrefix fake_reader_prefix{{0xF5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_reader_eid = entity_id_for_reader(1);

    auto [pub, pub_ec] = p->new_publisher("GapTopic", reliable_qos());
    REQUIRE_FALSE(pub_ec);

    announce_fake_remote_reader(*p, fake_reader_prefix, fake_reader_eid, "GapTopic",
                                 static_cast<uint16_t>(fake_reader_sock->port()));

    // Write 6 samples into a depth-4 history: retained window becomes [3,6],
    // evicting SN 1 and 2.
    for (int i = 0; i < 6; ++i) {
        CHECK_FALSE(pub->write(std::vector<uint8_t>{static_cast<uint8_t>(i)}));
        REQUIRE(recv_submessage(*fake_reader_sock, kSubmessageIdHeartbeat).has_value());
    }

    const EntityId writer_eid = entity_id_for_writer(1);

    AckNack an;
    an.reader_entity_id = fake_reader_eid;
    an.writer_entity_id = writer_eid;
    an.base                = SequenceNumber{0, 1}; // SN 1 (evicted)
    an.bitmap               = 0x3u;                  // SN 1 and SN 2 (both evicted)
    an.count                = 1;
    std::vector<uint8_t> submsg;
    an.encode(submsg);
    auto msg = wrap_in_rtps_message(fake_reader_prefix, kVendorIdCppDDS, submsg);
    fake_reader_sock->send_to("127.0.0.1", p->data_unicast_port(), msg.data(), msg.size());

    auto gap_pkt = recv_submessage(*fake_reader_sock, kSubmessageIdGap);
    REQUIRE(gap_pkt.has_value());

    // Gap has no public decode (matching go-DDS's own send-only asymmetry —
    // see types.hpp's Gap doc comment); verify the wire layout directly,
    // matching Gap::encode's documented body layout: readerEID(4) +
    // writerEID(4) + gapStart.high(4) + gapStart.low(4) +
    // gapList.bitmapBase.high(4) + gapList.bitmapBase.low(4) + numBits(4).
    const uint8_t* body = gap_pkt->data.data() + Header::kSize + SubmessageHeader::kSize;
    auto            get_u32_le = [](const uint8_t* ptr) {
        return static_cast<uint32_t>(ptr[0]) | (static_cast<uint32_t>(ptr[1]) << 8) |
               (static_cast<uint32_t>(ptr[2]) << 16) | (static_cast<uint32_t>(ptr[3]) << 24);
    };
    CHECK(get_u32_le(body + 8) == 0u);  // gapStart.high
    CHECK(get_u32_le(body + 12) == 1u); // gapStart.low = ack_base = 1
    CHECK(get_u32_le(body + 16) == 0u); // gapEnd(+1).high
    CHECK(get_u32_le(body + 20) == 3u); // bitmapBase.low = gap_end+1 = 3 -> gap_end = 2

    p->close();
}
