// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Tests for Tier-1 phase 8, "Fragmentation" (see ROADMAP.md). Four groups:
//
//  1. Byte-exact wire compatibility for DataFrag::encode/decode and
//     split_into_fragments_n against github.com/SoundMatt/go-DDS's
//     marshalDataFrag/parseDataFrag/splitIntoFragmentsN — the correctness
//     oracle named in cpp-DDS's ROADMAP.md.
//
//     ── How every *_HEX constant below was derived ──────────────────────
//
//     go-DDS's marshalDataFrag/splitIntoFragmentsN/fragmentAssembler are
//     unexported, so — following the exact precedent set by
//     tests/test_rtps_types.cpp and tests/test_rtps_reliable.cpp — the
//     vectors were generated by calling those *actual* functions white-box,
//     from a scratch _test.go file placed temporarily inside a fresh clone
//     of go-DDS's rtps package (never committed to go-DDS, never pushed
//     anywhere):
//
//       git clone https://github.com/SoundMatt/go-DDS.git
//       cd go-DDS
//       cat > rtps/zzz_scratch_fragment_vectors_test.go <<'EOF'
//       package rtps
//
//       import (
//           "encoding/hex"
//           "fmt"
//           "testing"
//       )
//
//       func TestPrintCppDDSFragmentReferenceVectors(t *testing.T) {
//           readerEID := EntityId{0x00, 0x00, 0x00, 0x04}
//           writerEID := EntityId{0x00, 0x00, 0x42, 0x03}
//
//           f := DataFrag{
//               WriterEntityId:      writerEID,
//               ReaderEntityId:      readerEID,
//               WriterSeqNum:        SequenceNumber{High: 0, Low: 9},
//               FragmentStartingNum: 1,
//               FragmentsInSubmsg:   1,
//               FragmentSize:        4,
//               DataSize:            10,
//               Payload:             []byte{0xDE, 0xAD, 0xBE, 0xEF},
//           }
//           fmt.Println("DATAFRAG_SAMPLE_HEX =", hex.EncodeToString(marshalDataFrag(f)))
//
//           prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//           fmt.Println("DATAFRAG_FULL_MESSAGE_HEX =", hex.EncodeToString(wrapInRTPSMessage(prefix, marshalDataFrag(f))))
//
//           payload := make([]byte, 13)
//           for i := range payload {
//               payload[i] = byte(0xA0 + i)
//           }
//           wrapped := cdrWrapPayload(payload)
//           fmt.Println("CDR_WRAPPED_HEX =", hex.EncodeToString(wrapped))
//
//           frags := splitIntoFragmentsN(writerEID, SequenceNumber{High: 0, Low: 42}, wrapped, 5)
//           fmt.Println("NUM_FRAGS =", len(frags))
//           for i, fr := range frags {
//               fmt.Printf("FRAG_%d_HEX = %s\n", i, hex.EncodeToString(marshalDataFrag(fr)))
//           }
//
//           var fa fragmentAssembler
//           var result []byte
//           for _, fr := range frags {
//               if out := fa.receive(fr); out != nil {
//                   result = out
//               }
//           }
//           fmt.Println("REASSEMBLED_MATCHES_WRAPPED =", hex.EncodeToString(result) == hex.EncodeToString(wrapped))
//
//           var fa2 fragmentAssembler
//           var result2 []byte
//           for i := len(frags) - 1; i >= 0; i-- {
//               if out := fa2.receive(frags[i]); out != nil {
//                   result2 = out
//               }
//           }
//           fmt.Println("REASSEMBLED_OUT_OF_ORDER_MATCHES =", hex.EncodeToString(result2) == hex.EncodeToString(wrapped))
//       }
//       EOF
//       go test ./rtps -run TestPrintCppDDSFragmentReferenceVectors -v
//
//     That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//       DATAFRAG_SAMPLE_HEX       = 16012400000000000000000400004203000000000900000001000000010004000a000000deadbeef
//       DATAFRAG_FULL_MESSAGE_HEX = 5254505302030127010f996ecafebabe0000000116012400000000000000000400004203000000000900000001000000010004000a000000deadbeef
//       CDR_WRAPPED_HEX           = 01000000a0a1a2a3a4a5a6a7a8a9aaabac
//       NUM_FRAGS                 = 4
//       FRAG_0_HEX = 16012500000000000000000000004203000000002a00000001000000010005001100000001000000a0
//       FRAG_1_HEX = 16012500000000000000000000004203000000002a000000020000000100050011000000a1a2a3a4a5
//       FRAG_2_HEX = 16012500000000000000000000004203000000002a000000030000000100050011000000a6a7a8a9aa
//       FRAG_3_HEX = 16012200000000000000000000004203000000002a000000040000000100050011000000abac
//       REASSEMBLED_MATCHES_WRAPPED           = true
//       REASSEMBLED_OUT_OF_ORDER_MATCHES      = true
//
//  2. Behavioral tests for FragmentAssembler (fragment.hpp) reproducing the
//     go-DDS reference vectors above end-to-end (feed FRAG_0..3 back in,
//     confirm the reassembled bytes equal CDR_WRAPPED_HEX — both in-order
//     and out-of-order) plus edge cases (stale eviction, malformed input
//     rejection) with no independent golden-vector requirement (the key
//     scheme itself is not wire-visible — see fragment.hpp's own
//     file-level scope note).
//
//  3. End-to-end tests driving a real dds::rtps::Participant over real
//     loopback UDP (matching the existing patterns in
//     test_rtps_participant.cpp and test_rtps_reliable.cpp): a large
//     Writer::write is fragmented on send and reassembled on receive by a
//     second Participant's real data_loop(), and a reliable writer
//     re-fragments a large payload correctly on ACKNACK-triggered
//     retransmit.

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <optional>
#include <string_view>
#include <thread>
#include <vector>

#include <dds/rtps/participant.hpp>

using namespace dds;
using namespace dds::rtps;
using namespace std::chrono_literals;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

EntityId sample_reader_entity() { return EntityId{{0x00, 0x00, 0x00, 0x04}}; }
EntityId sample_writer_entity() { return EntityId{{0x00, 0x00, 0x42, 0x03}}; }
GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}
GUID sample_writer_guid() { return GUID{sample_prefix(), sample_writer_entity()}; }

Locator make_udp4_locator(const std::array<uint8_t, 4>& quad, uint16_t port) {
    Locator l;
    l.kind = Locator::kKindUDPv4;
    l.port  = port;
    std::copy(quad.begin(), quad.end(), l.address.begin() + 12);
    return l;
}
Locator loopback_locator(uint16_t port) { return make_udp4_locator({127, 0, 0, 1}, port); }

// go-DDS reference vectors — see the file-level comment above for the
// exact reproduction command.
constexpr const char* kDataFragSampleHex =
    "16012400000000000000000400004203000000000900000001000000010004000a000000deadbeef";
constexpr const char* kDataFragFullMessageHex =
    "5254505302030127010f996ecafebabe0000000116012400000000000000000400004203000000000900000001000000"
    "010004000a000000deadbeef";
constexpr const char* kCdrWrappedHex = "01000000a0a1a2a3a4a5a6a7a8a9aaabac";
constexpr const char* kFrag0Hex =
    "16012500000000000000000000004203000000002a00000001000000010005001100000001000000a0";
constexpr const char* kFrag1Hex =
    "16012500000000000000000000004203000000002a000000020000000100050011000000a1a2a3a4a5";
constexpr const char* kFrag2Hex =
    "16012500000000000000000000004203000000002a000000030000000100050011000000a6a7a8a9aa";
constexpr const char* kFrag3Hex = "16012200000000000000000000004203000000002a000000040000000100050011000000abac";

// Registers a fake remote reader as SEDP-matched to a local writer on
// topic_name, with its data-receive locator pointing at reader_data_port
// (typically a raw UdpSocket standing in for the remote reader). Matches
// test_rtps_reliable.cpp's identical helper.
void announce_fake_remote_reader(Participant& p, const GuidPrefix& reader_prefix, const EntityId& reader_eid,
                                  const std::string& topic_name, uint16_t reader_data_port) {
    auto data = build_endpoint_data(EndpointInfo{GUID{reader_prefix, reader_eid}, topic_name, false},
                                     reader_data_port);
    auto announcement = build_sedp_announcement(reader_prefix, kVendorIdCppDDS, kEntityIdSEDPSubWriter,
                                                 kEntityIdSEDPSubReader, SequenceNumber{0, 1}, data);
    p.sedp().handle_packet(announcement, "127.0.0.1");
}

// Polls sock for up to ~3s for a datagram whose first submessage id (at
// Header::kSize, i.e. byte 20) equals want_submessage_id. Matches
// test_rtps_reliable.cpp's identical helper.
std::optional<UdpPacket> recv_submessage(UdpSocket& sock, uint8_t want_submessage_id) {
    for (int attempt = 0; attempt < 60; ++attempt) {
        auto pkt = sock.recv();
        if (pkt && pkt->data.size() > Header::kSize && pkt->data[Header::kSize] == want_submessage_id) {
            return pkt;
        }
    }
    return std::nullopt;
}

} // namespace

// ── 1. Byte-exact wire vectors ───────────────────────────────────────────────

TEST_CASE("DataFrag::encode matches go-DDS reference vector", "[rtps][fragment]") {
    DataFrag f;
    f.reader_entity_id       = sample_reader_entity();
    f.writer_entity_id       = sample_writer_entity();
    f.writer_seq_num         = SequenceNumber{0, 9};
    f.fragment_starting_num  = 1;
    f.fragments_in_submsg    = 1;
    f.fragment_size          = 4;
    f.data_size              = 10;
    f.payload                = {0xDE, 0xAD, 0xBE, 0xEF};

    std::vector<uint8_t> out;
    f.encode(out);
    CHECK(to_hex(out) == kDataFragSampleHex);
}

TEST_CASE("DataFrag::decode round-trips the reference vector", "[rtps][fragment]") {
    auto bytes = hex_to_bytes(kDataFragSampleHex);
    auto f     = DataFrag::decode(bytes.data(), bytes.size());
    REQUIRE(f.has_value());
    CHECK(f->reader_entity_id == sample_reader_entity());
    CHECK(f->writer_entity_id == sample_writer_entity());
    CHECK(f->writer_seq_num == SequenceNumber{0, 9});
    CHECK(f->fragment_starting_num == 1);
    CHECK(f->fragments_in_submsg == 1);
    CHECK(f->fragment_size == 4);
    CHECK(f->data_size == 10);
    CHECK(f->payload == std::vector<uint8_t>{0xDE, 0xAD, 0xBE, 0xEF});
}

TEST_CASE("DataFrag::decode rejects short/malformed buffers", "[rtps][fragment]") {
    auto bytes = hex_to_bytes(kDataFragSampleHex);
    for (std::size_t n = 0; n < 36; ++n) {
        CHECK_FALSE(DataFrag::decode(bytes.data(), n).has_value());
    }
    // Wrong submessage id.
    auto wrong_id = bytes;
    wrong_id[0]   = kSubmessageIdData;
    CHECK_FALSE(DataFrag::decode(wrong_id.data(), wrong_id.size()).has_value());
}

TEST_CASE("full RTPS message wrapping a DataFrag matches go-DDS reference vector", "[rtps][fragment]") {
    DataFrag f;
    f.reader_entity_id       = sample_reader_entity();
    f.writer_entity_id       = sample_writer_entity();
    f.writer_seq_num         = SequenceNumber{0, 9};
    f.fragment_starting_num  = 1;
    f.fragments_in_submsg    = 1;
    f.fragment_size          = 4;
    f.data_size              = 10;
    f.payload                = {0xDE, 0xAD, 0xBE, 0xEF};

    std::vector<uint8_t> submsg;
    f.encode(submsg);
    auto msg = wrap_in_rtps_message(sample_prefix(), kVendorIdGoDDS, submsg);
    CHECK(to_hex(msg) == kDataFragFullMessageHex);
}

TEST_CASE("split_into_fragments_n matches go-DDS reference vectors", "[rtps][fragment]") {
    auto payload = hex_to_bytes(kCdrWrappedHex);
    CHECK(payload.size() == 17);

    auto frags = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, payload, 5);
    REQUIRE(frags.size() == 4);

    const char* expected[4] = {kFrag0Hex, kFrag1Hex, kFrag2Hex, kFrag3Hex};
    for (std::size_t i = 0; i < 4; ++i) {
        std::vector<uint8_t> out;
        frags[i].encode(out);
        CHECK(to_hex(out) == expected[i]);
    }

    // Field sanity, independent of the raw hex.
    CHECK(frags[0].fragment_starting_num == 1);
    CHECK(frags[1].fragment_starting_num == 2);
    CHECK(frags[2].fragment_starting_num == 3);
    CHECK(frags[3].fragment_starting_num == 4);
    for (const auto& f : frags) {
        CHECK(f.fragments_in_submsg == 1);
        CHECK(f.fragment_size == 5);
        CHECK(f.data_size == payload.size());
        CHECK(f.reader_entity_id == kEntityIdUnknown);
        CHECK(f.writer_entity_id == sample_writer_entity());
    }
    CHECK(frags[0].payload.size() == 5);
    CHECK(frags[1].payload.size() == 5);
    CHECK(frags[2].payload.size() == 5);
    CHECK(frags[3].payload.size() == 2); // 17 = 5+5+5+2
}

TEST_CASE("split_into_fragments uses the default kMaxFragmentPayload size", "[rtps][fragment]") {
    std::vector<uint8_t> payload(static_cast<std::size_t>(kMaxFragmentPayload) + 1, 0x42);
    auto frags = split_into_fragments(sample_writer_entity(), SequenceNumber{0, 1}, payload);
    REQUIRE(frags.size() == 2);
    CHECK(frags[0].payload.size() == kMaxFragmentPayload);
    CHECK(frags[1].payload.size() == 1);
}

TEST_CASE("split_into_fragments_n on a payload that fits in one fragment returns a single DataFrag",
          "[rtps][fragment]") {
    std::vector<uint8_t> payload{1, 2, 3};
    auto frags = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 1}, payload, 5);
    REQUIRE(frags.size() == 1);
    CHECK(frags[0].payload == payload);
    CHECK(frags[0].data_size == 3);
}

// ── 2. FragmentAssembler behavioral tests ────────────────────────────────────

TEST_CASE("FragmentAssembler reassembles the go-DDS reference fragments in order", "[rtps][fragment]") {
    auto wrapped = hex_to_bytes(kCdrWrappedHex);
    auto frags   = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, wrapped, 5);
    REQUIRE(frags.size() == 4);

    FragmentAssembler fa;
    std::optional<std::vector<uint8_t>> result;
    for (const auto& f : frags) {
        auto out = fa.receive(sample_writer_guid(), f);
        if (out) result = std::move(out);
    }
    REQUIRE(result.has_value());
    CHECK(*result == wrapped);
}

TEST_CASE("FragmentAssembler reassembles out-of-order fragments identically", "[rtps][fragment]") {
    auto wrapped = hex_to_bytes(kCdrWrappedHex);
    auto frags   = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, wrapped, 5);
    REQUIRE(frags.size() == 4);

    FragmentAssembler fa;
    std::optional<std::vector<uint8_t>> result;
    for (auto it = frags.rbegin(); it != frags.rend(); ++it) {
        auto out = fa.receive(sample_writer_guid(), *it);
        if (out) result = std::move(out);
    }
    REQUIRE(result.has_value());
    CHECK(*result == wrapped);
}

TEST_CASE("FragmentAssembler returns nullopt until every fragment has arrived", "[rtps][fragment]") {
    auto wrapped = hex_to_bytes(kCdrWrappedHex);
    auto frags   = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, wrapped, 5);
    REQUIRE(frags.size() == 4);

    FragmentAssembler fa;
    for (std::size_t i = 0; i + 1 < frags.size(); ++i) {
        CHECK_FALSE(fa.receive(sample_writer_guid(), frags[i]).has_value());
    }
    CHECK(fa.receive(sample_writer_guid(), frags.back()).has_value());
}

TEST_CASE("FragmentAssembler does not complete reassembly on a duplicate fragment, and still "
          "completes once the genuinely missing fragment arrives",
          "[rtps][fragment]") {
    // Regression test: a retransmitted/duplicate DATA_FRAG for an index
    // that already arrived must not be counted a second time toward
    // completion. Before this fix, resending frags[0] in place of the
    // still-missing frags[3] made `received >= total` true early, and the
    // assembler handed back a payload with frags[3]'s byte range still
    // zero-filled instead of ever actually receiving it.
    auto wrapped = hex_to_bytes(kCdrWrappedHex);
    auto frags   = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, wrapped, 5);
    REQUIRE(frags.size() == 4);

    FragmentAssembler fa;
    CHECK_FALSE(fa.receive(sample_writer_guid(), frags[0]).has_value());
    CHECK_FALSE(fa.receive(sample_writer_guid(), frags[1]).has_value());
    CHECK_FALSE(fa.receive(sample_writer_guid(), frags[2]).has_value());

    // Duplicate of an already-received fragment (frags[0] again) must not
    // fake completion — frags[3] never arrived.
    CHECK_FALSE(fa.receive(sample_writer_guid(), frags[0]).has_value());

    // The genuinely missing fragment now arrives and completion succeeds
    // with fully correct data (not zero-filled in frags[3]'s range).
    auto result = fa.receive(sample_writer_guid(), frags[3]);
    REQUIRE(result.has_value());
    CHECK(*result == wrapped);
}

TEST_CASE("FragmentAssembler rejects a fragment claiming an implausibly large DataSize", "[rtps][fragment]") {
    DataFrag f;
    f.writer_entity_id      = sample_writer_entity();
    f.writer_seq_num        = SequenceNumber{0, 1};
    f.fragment_starting_num = 1;
    f.fragments_in_submsg   = 1;
    f.fragment_size         = 4;
    f.data_size              = kMaxReassemblyBytes + 1;
    f.payload                = {1, 2, 3, 4};

    FragmentAssembler fa;
    CHECK_FALSE(fa.receive(sample_writer_guid(), f).has_value());
}

TEST_CASE("FragmentAssembler ignores a fragment with a zero fragment_size/data_size/fragments_in_submsg",
          "[rtps][fragment]") {
    FragmentAssembler fa;

    DataFrag zero_frag_size;
    zero_frag_size.writer_entity_id      = sample_writer_entity();
    zero_frag_size.fragment_starting_num = 1;
    zero_frag_size.fragments_in_submsg   = 1;
    zero_frag_size.fragment_size          = 0;
    zero_frag_size.data_size              = 10;
    CHECK_FALSE(fa.receive(sample_writer_guid(), zero_frag_size).has_value());

    DataFrag zero_data_size = zero_frag_size;
    zero_data_size.fragment_size = 4;
    zero_data_size.data_size     = 0;
    CHECK_FALSE(fa.receive(sample_writer_guid(), zero_data_size).has_value());

    DataFrag zero_frags_in_submsg    = zero_data_size;
    zero_frags_in_submsg.data_size    = 10;
    zero_frags_in_submsg.fragments_in_submsg = 0;
    CHECK_FALSE(fa.receive(sample_writer_guid(), zero_frags_in_submsg).has_value());
}

TEST_CASE("FragmentAssembler keys reassembly by full writer GUID, not entity id alone", "[rtps][fragment]") {
    // Two different remote participants using the same writer EntityId
    // ordinal (a common situation — entity ids are assigned sequentially
    // per participant starting at 1) must not have their fragment streams
    // cross-contaminate. See fragment.hpp's file-level scope note on why
    // this port's key is a full GUID unlike go-DDS's own EntityId-only key.
    auto wrapped = hex_to_bytes(kCdrWrappedHex);
    auto frags   = split_into_fragments_n(sample_writer_entity(), SequenceNumber{0, 42}, wrapped, 5);
    REQUIRE(frags.size() == 4);

    GUID guid_a{GuidPrefix{{1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}, sample_writer_entity()};
    GUID guid_b{GuidPrefix{{2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}, sample_writer_entity()};

    FragmentAssembler fa;
    // Feed participant A's first three fragments, then all of participant
    // B's fragments (which must reassemble independently and completely),
    // then A's last fragment (which must then also complete).
    CHECK_FALSE(fa.receive(guid_a, frags[0]).has_value());
    CHECK_FALSE(fa.receive(guid_a, frags[1]).has_value());
    CHECK_FALSE(fa.receive(guid_a, frags[2]).has_value());

    std::optional<std::vector<uint8_t>> b_result;
    for (const auto& f : frags) {
        auto out = fa.receive(guid_b, f);
        if (out) b_result = std::move(out);
    }
    REQUIRE(b_result.has_value());
    CHECK(*b_result == wrapped);

    auto a_result = fa.receive(guid_a, frags[3]);
    REQUIRE(a_result.has_value());
    CHECK(*a_result == wrapped);
}

// ── 3. End-to-end fragmentation over real loopback UDP ───────────────────────

TEST_CASE("A large Writer::write is fragmented on send and reassembled on receive across two Participants",
          "[rtps][fragment][participant]") {
    ParticipantOptions opts;
    opts.test_mode = true;
    auto [pa, eca] = Participant::create(0, opts);
    auto [pb, ecb] = Participant::create(0, opts);
    REQUIRE_FALSE(eca);
    REQUIRE_FALSE(ecb);

    auto [sub, sub_ec] = pa->new_subscriber("FragTopic", default_qos());
    REQUIRE_FALSE(sub_ec);
    auto [pub, pub_ec] = pb->new_publisher("FragTopic", default_qos());
    REQUIRE_FALSE(pub_ec);

    ParticipantProxy proxy_b;
    proxy_b.guid                = GUID{pb->guid_prefix(), kEntityIdParticipant};
    proxy_b.metatraffic_unicast = loopback_locator(static_cast<uint16_t>(pb->meta_unicast_port()));
    proxy_b.default_unicast     = loopback_locator(static_cast<uint16_t>(pb->data_unicast_port()));
    pa->sedp().on_new_peer(proxy_b);

    ParticipantProxy proxy_a;
    proxy_a.guid                = GUID{pa->guid_prefix(), kEntityIdParticipant};
    proxy_a.metatraffic_unicast = loopback_locator(static_cast<uint16_t>(pa->meta_unicast_port()));
    proxy_a.default_unicast     = loopback_locator(static_cast<uint16_t>(pa->data_unicast_port()));
    pb->sedp().on_new_peer(proxy_a);

    bool matched = false;
    for (int attempt = 0; attempt < 60 && !matched; ++attempt) {
        std::this_thread::sleep_for(50ms);
        matched = !pb->sedp().matched_reader_locators_for_topic("FragTopic").empty();
    }
    REQUIRE(matched);

    // Well over kMaxFragmentPayload once CDR-wrapped, so this must produce
    // multiple DATA_FRAG submessages on the wire.
    std::vector<uint8_t> payload(5000);
    for (std::size_t i = 0; i < payload.size(); ++i) payload[i] = static_cast<uint8_t>(i);

    CHECK_FALSE(pub->write(payload));

    auto ch     = sub->channel();
    auto sample = ch->recv_until(std::chrono::steady_clock::now() + 5s);
    REQUIRE(sample.has_value());
    CHECK(sample->topic == "FragTopic");
    CHECK(sample->payload == payload);

    pa->close();
    pb->close();
}

TEST_CASE("A payload right at kMaxFragmentPayload after CDR wrapping is not fragmented", "[rtps][fragment]") {
    // cdr_wrap_payload adds a 4-byte encapsulation header (see cdr.hpp), so
    // a payload of exactly kMaxFragmentPayload - 4 bytes wraps to exactly
    // kMaxFragmentPayload and must NOT be fragmented (go-DDS's own
    // `len(wrapped) > fragSize` check is a strict greater-than).
    std::vector<uint8_t> payload(static_cast<std::size_t>(kMaxFragmentPayload) - 4, 0x11);
    auto wrapped = cdr_wrap_payload(payload);
    CHECK(wrapped.size() == kMaxFragmentPayload);
    CHECK_FALSE(wrapped.size() > kMaxFragmentPayload);
}

TEST_CASE("Reliable writer re-fragments a large payload on ACKNACK-triggered retransmit",
          "[rtps][fragment][reliable][participant]") {
    ParticipantOptions opts;
    opts.test_mode = true;
    auto [p, ec] = Participant::create(0, opts);
    REQUIRE_FALSE(ec);

    auto fake_reader_sock = UdpSocket::bind_unicast(0);
    REQUIRE(fake_reader_sock.has_value());
    const GuidPrefix fake_reader_prefix{{0xF5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
    const EntityId    fake_reader_eid = entity_id_for_reader(1);

    auto [pub, pub_ec] = p->new_publisher("FragRetransmitTopic", reliable_qos());
    REQUIRE_FALSE(pub_ec);

    announce_fake_remote_reader(*p, fake_reader_prefix, fake_reader_eid, "FragRetransmitTopic",
                                 static_cast<uint16_t>(fake_reader_sock->port()));

    std::vector<uint8_t> payload(5000);
    for (std::size_t i = 0; i < payload.size(); ++i) payload[i] = static_cast<uint8_t>(i * 7);

    CHECK_FALSE(pub->write(payload));

    // Drain every DATA_FRAG fragment plus the trailing HEARTBEAT from the
    // initial write before sending the ACKNACK, so they aren't mistaken
    // for the retransmit below.
    for (;;) {
        auto pkt = fake_reader_sock->recv();
        REQUIRE(pkt.has_value());
        REQUIRE(pkt->data.size() > Header::kSize);
        if (pkt->data[Header::kSize] == kSubmessageIdHeartbeat) break;
        REQUIRE(pkt->data[Header::kSize] == kSubmessageIdDataFrag);
    }

    const EntityId writer_eid = entity_id_for_writer(1);

    AckNack an;
    an.reader_entity_id = fake_reader_eid;
    an.writer_entity_id = writer_eid;
    an.base                = SequenceNumber{0, 1};
    an.bitmap               = 0x1u; // SN 1 missing
    an.count                = 1;
    std::vector<uint8_t> submsg;
    an.encode(submsg);
    auto msg = wrap_in_rtps_message(fake_reader_prefix, kVendorIdCppDDS, submsg);
    fake_reader_sock->send_to("127.0.0.1", p->data_unicast_port(), msg.data(), msg.size());

    // Collect every retransmitted DATA_FRAG fragment for SN 1 and
    // reassemble locally, confirming the *complete* payload is resent (not
    // just fragment #1, unlike go-DDS's own known limitation — see
    // fragment.hpp's file-level scope note).
    GUID writer_guid{p->guid_prefix(), writer_eid};
    FragmentAssembler fa;
    std::optional<std::vector<uint8_t>> reassembled;
    for (int received = 0; received < 64 && !reassembled; ++received) {
        auto pkt = recv_submessage(*fake_reader_sock, kSubmessageIdDataFrag);
        REQUIRE(pkt.has_value());
        auto df = DataFrag::decode(pkt->data.data() + Header::kSize, pkt->data.size() - Header::kSize);
        REQUIRE(df.has_value());
        CHECK(sn_to_u64(df->writer_seq_num) == 1u);
        reassembled = fa.receive(writer_guid, *df);
    }
    REQUIRE(reassembled.has_value());
    auto raw = cdr_unwrap_payload(*reassembled);
    REQUIRE(raw.has_value());
    CHECK(*raw == payload);

    p->close();
}
