// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Tests for dds::security::HMACPlugin — byte-exact wire format against
// github.com/SoundMatt/go-DDS's `security` package (security/security.go),
// the correctness oracle named in cpp-DDS's ROADMAP.md ("Tier 2 — safety
// and security", `security`).
//
// fusa:test REQ-SECURITY-001 REQ-SECURITY-003 REQ-SECURITY-004
// fusa:test REQ-SECURITY-007
//
// ── How every *_HEX constant below was derived ───────────────────────────────
//
// HMACPlugin::seal is fully deterministic (no randomness), so the vectors
// were generated by calling go-DDS's *actual, exported* security.HMACPlugin
// API directly from a scratch _test.go file placed temporarily inside a
// fresh clone of go-DDS's security package (never committed to go-DDS,
// never pushed anywhere) — exactly as test_safety_e2e.cpp's header vectors
// were derived, and unlike that file, no white-box helper substitution was
// even necessary here since there's no time.Now()/rand.Reader in the path:
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS/security
//   cat > zzz_scratch_cppdds_vectors_test.go <<'EOF'
//   package security
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSSecurityReferenceVectors(t *testing.T) {
//       hmacKey := make([]byte, 32)
//       for i := range hmacKey {
//           hmacKey[i] = byte(i)
//       }
//       hp := NewHMACPlugin(hmacKey)
//
//       sealedHello, _ := hp.Seal([]byte("hello"))
//       fmt.Println("HMAC_KEY_HEX          =", hex.EncodeToString(hmacKey))
//       fmt.Println("HMAC_SEALED_HELLO_HEX =", hex.EncodeToString(sealedHello))
//
//       sealedEmpty, _ := hp.Seal([]byte{})
//       fmt.Println("HMAC_SEALED_EMPTY_HEX =", hex.EncodeToString(sealedEmpty))
//
//       longMsg := make([]byte, 1024)
//       for i := range longMsg {
//           longMsg[i] = byte(i)
//       }
//       sealedLong, _ := hp.Seal(longMsg)
//       fmt.Println("HMAC_SEALED_LONG_HEX  =", hex.EncodeToString(sealedLong))
//   }
//   EOF
//   go test . -run TestPrintCppDDSSecurityReferenceVectors -v
//
// That produced (go-DDS main @ time of writing, module
// github.com/SoundMatt/go-DDS/security, commit 1272f294de25 —
// "Kubernetes operator (Milestone 15, v1.1)"):
//
//   HMAC_KEY_HEX          = 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
//   HMAC_SEALED_HELLO_HEX = 68656c6c6f53c40272a70c15ca4ee0af4df1f155fd6c41e00ce2307d8987ecd4bb36a7e990
//   HMAC_SEALED_EMPTY_HEX = d38b42096d80f45f826b44a9d5607de72496a415d3f4a1a8c88e3bb9da8dc1cb
//   HMAC_SEALED_LONG_HEX  = <1024-byte plaintext><32-byte HMAC tag> — see below.
//
// The tag on the empty-message vector (d38b4209...) is also independently
// verifiable as HMAC-SHA256 of an empty message under the all-zero-through-
// 0x1f key using RFC 4231's construction, cross-checked against this repo's
// own from-scratch dds::security::detail::hmac_sha256 (see
// tests/test_security_aesgcm.cpp's sibling SHA-256/HMAC known-answer tests
// in the crypto layer) plus RFC 4231 test vectors 1/2 verified during
// development.

#include <dds/security/security.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <string>
#include <vector>

using namespace dds::security;

namespace {

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string        s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

std::vector<uint8_t> from_hex(const std::string& hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(c - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::vector<uint8_t> str_bytes(const std::string& s) { return {s.begin(), s.end()}; }

} // namespace

// ── byte-exact wire format vs. go-DDS ────────────────────────────────────────

TEST_CASE("HMACPlugin::seal matches go-DDS reference vector (hello)",
          "[security][hmac][REQ-SECURITY-003]") {
    auto key = from_hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
    HMACPlugin p(key);
    auto [sealed, ec] = p.seal(str_bytes("hello"));
    REQUIRE_FALSE(ec);
    CHECK(to_hex(sealed) == "68656c6c6f53c40272a70c15ca4ee0af4df1f155fd6c41e00ce2307d8987ecd4bb36a7e990");
}

TEST_CASE("HMACPlugin::seal matches go-DDS reference vector (empty)",
          "[security][hmac][REQ-SECURITY-003]") {
    auto key = from_hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
    HMACPlugin p(key);
    auto [sealed, ec] = p.seal({});
    REQUIRE_FALSE(ec);
    CHECK(sealed.size() == 32);
    CHECK(to_hex(sealed) == "d38b42096d80f45f826b44a9d5607de72496a415d3f4a1a8c88e3bb9da8dc1cb");
}

TEST_CASE("HMACPlugin::seal matches go-DDS reference vector (1024-byte long message)",
          "[security][hmac][REQ-SECURITY-003]") {
    auto key = from_hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
    HMACPlugin p(key);

    std::vector<uint8_t> longmsg(1024);
    for (std::size_t i = 0; i < longmsg.size(); i++) longmsg[i] = static_cast<uint8_t>(i);

    auto [sealed, ec] = p.seal(longmsg);
    REQUIRE_FALSE(ec);
    REQUIRE(sealed.size() == longmsg.size() + 32);

    // Tag is the trailing 32 bytes; go-DDS's reference vector tag.
    std::vector<uint8_t> tag(sealed.end() - 32, sealed.end());
    CHECK(to_hex(tag) == "b7461b582e6d4e287bcc2f9f853344bc3fcbf7dd4e5c87e4fab2b4fcd50c7c05");
}

// ── round trip ────────────────────────────────────────────────────────────────

TEST_CASE("HMACPlugin round trip: various payload sizes", "[security][hmac][REQ-SECURITY-001]") {
    auto key = new_random_key(32);
    HMACPlugin p(key);

    std::vector<std::vector<uint8_t>> cases = {
        {}, str_bytes("hello world"), std::vector<uint8_t>(1024, 0)};
    for (auto& c : cases) {
        auto [sealed, ec1] = p.seal(c);
        REQUIRE_FALSE(ec1);
        auto [opened, ec2] = p.open(sealed);
        REQUIRE_FALSE(ec2);
        CHECK(opened == c);
    }
}

TEST_CASE("HMACPlugin::seal appends exactly 32 bytes", "[security][hmac][REQ-SECURITY-003]") {
    auto key = new_random_key(32);
    HMACPlugin p(key);
    auto plain          = str_bytes("payload");
    auto [sealed, ec] = p.seal(plain);
    REQUIRE_FALSE(ec);
    CHECK(sealed.size() == plain.size() + 32);
}

// ── tamper / wrong-key / too-short rejection ─────────────────────────────────

TEST_CASE("HMACPlugin::open detects tampering", "[security][hmac][REQ-SECURITY-004]") {
    auto key = new_random_key(32);
    HMACPlugin p(key);
    auto [sealed, ec1] = p.seal(str_bytes("important data"));
    REQUIRE_FALSE(ec1);
    sealed[0] = static_cast<uint8_t>(sealed[0] ^ 0xFF);

    auto [opened, ec2] = p.open(sealed);
    CHECK(ec2 == ErrHMACVerificationFailed());
    CHECK(opened.empty());
}

TEST_CASE("HMACPlugin::open rejects wrong key", "[security][hmac][REQ-SECURITY-004]") {
    auto k1 = new_random_key(32);
    auto k2 = new_random_key(32);
    HMACPlugin p1(k1);
    HMACPlugin p2(k2);
    auto [sealed, ec1] = p1.seal(str_bytes("secret"));
    REQUIRE_FALSE(ec1);

    auto [opened, ec2] = p2.open(sealed);
    CHECK(ec2 == ErrHMACVerificationFailed());
}

TEST_CASE("HMACPlugin::open rejects payload shorter than the tag",
          "[security][hmac][REQ-SECURITY-004]") {
    auto key = new_random_key(32);
    HMACPlugin p(key);
    auto [opened, ec] = p.open(str_bytes("short"));
    CHECK(ec == ErrHMACTooShort());
}

// ── key isolation ─────────────────────────────────────────────────────────────

TEST_CASE("HMACPlugin copies key material at construction (REQ-SECURITY-007)",
          "[security][hmac][REQ-SECURITY-007]") {
    auto key  = new_random_key(32);
    auto orig = key;
    HMACPlugin p(key);
    for (auto& b : key) b = static_cast<uint8_t>(b ^ 0xFF); // mutate caller's copy

    auto [sealed, ec1] = p.seal(str_bytes("test"));
    REQUIRE_FALSE(ec1);
    auto [opened, ec2] = p.open(sealed);
    REQUIRE_FALSE(ec2);
    CHECK(opened == str_bytes("test"));

    // Plugin constructed with the ORIGINAL key must reject the caller's
    // now-mutated key — proves the plugin didn't retain a reference/alias.
    HMACPlugin p_orig(orig);
    auto [sealed2, ec3] = p_orig.seal(str_bytes("test"));
    REQUIRE_FALSE(ec3);
    CHECK(sealed == sealed2);
}

// ── new_random_key ────────────────────────────────────────────────────────────

TEST_CASE("new_random_key returns requested length", "[security][REQ-SECURITY-007]") {
    for (std::size_t n : {std::size_t{16}, std::size_t{32}, std::size_t{64}}) {
        CHECK(new_random_key(n).size() == n);
    }
}

TEST_CASE("new_random_key produces distinct output across calls", "[security][REQ-SECURITY-007]") {
    auto a = new_random_key(32);
    auto b = new_random_key(32);
    CHECK(a != b);
}

// ── NullPlugin ────────────────────────────────────────────────────────────────

TEST_CASE("NullPlugin is the identity transform", "[security][REQ-SECURITY-002]") {
    NullPlugin p;
    auto in              = str_bytes("test");
    auto [sealed, ec1] = p.seal(in);
    REQUIRE_FALSE(ec1);
    CHECK(sealed == in);
    auto [opened, ec2] = p.open(sealed);
    REQUIRE_FALSE(ec2);
    CHECK(opened == in);
}
