// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Byte-exact wire compatibility tests for dds::rtps SPDP (build/parse
// ParticipantProxy data, full announcement message framing) against
// github.com/SoundMatt/go-DDS's `rtps` package (rtps/spdp.go) — the
// correctness oracle named in cpp-DDS's ROADMAP.md ("Tier 1 — RTPS wire
// protocol", phase 4: "SPDP") — plus behavioral tests of the known-peers
// table (SpdpService).
//
// ── How every *_HEX constant below was derived ──────────────────────────────
//
// spdpService.buildParticipantData / parseParticipantData and the
// wrapInRTPSMessage/marshalDataSubmessage helpers they compose are all
// unexported (or, for the latter two, package-private), and buildParticipantData
// is itself a method on spdpService which needs a *participant. As with
// phases 1–3, the vectors were generated by calling those *actual*
// functions white-box, from a scratch _test.go file placed temporarily
// inside a fresh clone of go-DDS's rtps package (never committed to
// go-DDS, never pushed anywhere), constructing only the participant fields
// buildParticipantData actually reads (guidPrefix, metaSock.port,
// dataSock.port — DiscoveryPlugin left nil, matching this phase's scope):
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS
//   cat > rtps/zzz_scratch_spdp_vectors_test.go <<'EOF'
//   package rtps
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "net"
//       "testing"
//   )
//
//   func TestPrintCppDDSSPDPReferenceVectors(t *testing.T) {
//       prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//       p := &participant{
//           guidPrefix: prefix,
//           metaSock:   &udpSocket{port: 7410},
//           dataSock:   &udpSocket{port: 7411},
//       }
//       s := newSPDPService(p)
//
//       payload := s.buildParticipantData()
//       fmt.Println("SPDP_PARTICIPANT_DATA_HEX =", hex.EncodeToString(payload))
//
//       submsg := marshalDataSubmessage(EntityIdSPDPWriter, EntityIdSPDPReader, SequenceNumber{High: 0, Low: 1}, payload)
//       msg := wrapInRTPSMessage(p.guidPrefix, submsg)
//       fmt.Println("SPDP_ANNOUNCEMENT_MSG_HEX =", hex.EncodeToString(msg))
//
//       from := &net.UDPAddr{IP: net.ParseIP("192.168.1.50"), Port: 7410}
//       proxy := parseParticipantData(prefix, payload, from)
//       fmt.Printf("SPDP_PROXY_GUID_PREFIX_HEX = %x\n", proxy.guid.Prefix[:])
//       fmt.Printf("SPDP_PROXY_GUID_ENTITY_HEX = %x\n", proxy.guid.Entity[:])
//       fmt.Printf("SPDP_PROXY_META_LOCATOR kind=%d port=%d addr=%x\n", proxy.metatrafficUnicast.Kind, proxy.metatrafficUnicast.Port, proxy.metatrafficUnicast.Address)
//       fmt.Printf("SPDP_PROXY_DATA_LOCATOR kind=%d port=%d addr=%x\n", proxy.defaultUnicast.Kind, proxy.defaultUnicast.Port, proxy.defaultUnicast.Address)
//       fmt.Printf("SPDP_PROXY_BUILTIN_EPS = %d\n", proxy.builtinEndpoints)
//       fmt.Printf("SPDP_PROXY_LEASE_SEC = %v\n", proxy.leaseDuration.Seconds())
//
//       // Second vector: different prefix/ports/sequence number.
//       prefix2 := GuidPrefix{0xAA, 0xBB, 0xCC, 0xDD, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}
//       p2 := &participant{
//           guidPrefix: prefix2,
//           metaSock:   &udpSocket{port: 7660},
//           dataSock:   &udpSocket{port: 7661},
//       }
//       s2 := newSPDPService(p2)
//       payload2 := s2.buildParticipantData()
//       fmt.Println("SPDP_PARTICIPANT_DATA2_HEX =", hex.EncodeToString(payload2))
//       submsg2 := marshalDataSubmessage(EntityIdSPDPWriter, EntityIdSPDPReader, SequenceNumber{High: 0, Low: 42}, payload2)
//       msg2 := wrapInRTPSMessage(p2.guidPrefix, submsg2)
//       fmt.Println("SPDP_ANNOUNCEMENT_MSG2_HEX =", hex.EncodeToString(msg2))
//   }
//   EOF
//   go test ./rtps -run TestPrintCppDDSSPDPReferenceVectors -v
//
// That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//   SPDP_PARTICIPANT_DATA_HEX = 030000001500040002030000160004000127000050001000010f996ecafebabe00000001000001c1580004003f0000003200180001000000f21c0000000000000000000000000000000000002f00180001000000f31c000000000000000000000000000000000000020008000a0000000000000001000000
//   SPDP_ANNOUNCEMENT_MSG_HEX = 5254505302030127010f996ecafebabe0000000115058c0000001000000100c7000100c20000000001000000030000001500040002030000160004000127000050001000010f996ecafebabe00000001000001c1580004003f0000003200180001000000f21c0000000000000000000000000000000000002f00180001000000f31c000000000000000000000000000000000000020008000a0000000000000001000000
//   SPDP_PROXY_GUID_PREFIX_HEX = 010f996ecafebabe00000001
//   SPDP_PROXY_GUID_ENTITY_HEX = 000001c1
//   SPDP_PROXY_META_LOCATOR kind=1 port=7410 addr=000000000000000000000000c0a80132
//   SPDP_PROXY_DATA_LOCATOR kind=1 port=7411 addr=000000000000000000000000c0a80132
//   SPDP_PROXY_BUILTIN_EPS = 63
//   SPDP_PROXY_LEASE_SEC = 10
//   SPDP_PARTICIPANT_DATA2_HEX = 030000001500040002030000160004000127000050001000aabbccdd0102030405060708000001c1580004003f0000003200180001000000ec1d0000000000000000000000000000000000002f00180001000000ed1d000000000000000000000000000000000000020008000a0000000000000001000000
//   SPDP_ANNOUNCEMENT_MSG2_HEX = 5254505302030127aabbccdd010203040506070815058c0000001000000100c7000100c2000000002a000000030000001500040002030000160004000127000050001000aabbccdd0102030405060708000001c1580004003f0000003200180001000000ec1d0000000000000000000000000000000000002f00180001000000ed1d000000000000000000000000000000000000020008000a0000000000000001000000
//
// The scratch file was deleted immediately after and never committed —
// `git status` in the go-DDS clone was confirmed clean afterward.
//
// Note: 192.168.1.50 = 0xC0.0xA8.0x01.0x32, which is exactly the trailing
// 4 bytes of SPDP_PROXY_META_LOCATOR/DATA_LOCATOR's address above — that's
// the from-address fill-in for the 0.0.0.0 locators buildParticipantData
// emits (it doesn't know its own externally-visible IP), asserted below.
//
// The SpdpService peer-table/eviction/self-filtering tests below are
// ordinary behavioral tests (go-DDS has no dedicated unit test isolating
// just the known-peers-table logic either — it's exercised indirectly
// through full participant integration tests, which is a later Tier-1
// phase here), not wire-format conformance vectors. The two-participant
// discovery test overrides SpdpConfig::dest_address/dest_port to target
// the peer's bound socket directly over loopback rather than the real
// SPDP multicast group/port, for the same reason test_rtps_transport.cpp's
// own multicast test does: true multicast delivery is not guaranteed in a
// sandboxed CI runner (see rtps/transport.hpp's
// UdpSocket::bind_multicast_receive doc comment).

#include <chrono>
#include <cctype>
#include <string>
#include <thread>
#include <vector>

#include <catch2/catch_test_macros.hpp>

#include <dds/rtps/spdp.hpp>

using namespace dds::rtps;
using namespace std::chrono_literals;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}

GuidPrefix sample_prefix2() {
    return GuidPrefix{{0xAA, 0xBB, 0xCC, 0xDD, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}};
}

SpdpLocalInfo sample_local_info() {
    SpdpLocalInfo info;
    info.guid_prefix         = sample_prefix();
    info.meta_unicast_port    = 7410;
    info.default_unicast_port = 7411;
    info.vendor_id             = kVendorIdGoDDS; // pin to go-DDS's vendor ID for byte-exact match
    info.advertised_lease_duration = std::chrono::seconds(10);
    return info;
}

} // namespace

// ── build_participant_data ───────────────────────────────────────────────────

TEST_CASE("build_participant_data matches go-DDS reference vector", "[rtps][spdp]") {
    auto info = sample_local_info();
    CHECK(to_hex(build_participant_data(info)) ==
          "030000001500040002030000160004000127000050001000010f996ecafebabe000000010000"
          "01c1580004003f0000003200180001000000f21c000000000000000000000000000000000000"
          "2f00180001000000f31c000000000000000000000000000000000000020008000a0000000000"
          "000001000000");
}

TEST_CASE("build_participant_data matches go-DDS reference vector for a second sample",
          "[rtps][spdp]") {
    SpdpLocalInfo info;
    info.guid_prefix          = sample_prefix2();
    info.meta_unicast_port     = 7660;
    info.default_unicast_port  = 7661;
    info.vendor_id              = kVendorIdGoDDS;
    info.advertised_lease_duration = std::chrono::seconds(10);

    CHECK(to_hex(build_participant_data(info)) ==
          "030000001500040002030000160004000127000050001000aabbccdd01020304050607080000"
          "01c1580004003f0000003200180001000000ec1d000000000000000000000000000000000000"
          "2f00180001000000ed1d000000000000000000000000000000000000020008000a0000000000"
          "000001000000");
}

// ── build_spdp_announcement / wrap_in_rtps_message ───────────────────────────

TEST_CASE("build_spdp_announcement matches go-DDS reference vector", "[rtps][spdp]") {
    auto info = sample_local_info();
    auto msg  = build_spdp_announcement(info, SequenceNumber{0, 1});
    CHECK(to_hex(msg) ==
          "5254505302030127010f996ecafebabe0000000115058c0000001000000100c7000100c20000"
          "000001000000030000001500040002030000160004000127000050001000010f996ecafebabe"
          "00000001000001c1580004003f0000003200180001000000f21c000000000000000000000000"
          "0000000000002f00180001000000f31c00000000000000000000000000000000000002000800"
          "0a0000000000000001000000");
}

TEST_CASE("build_spdp_announcement matches go-DDS reference vector for a second sample",
          "[rtps][spdp]") {
    SpdpLocalInfo info;
    info.guid_prefix          = sample_prefix2();
    info.meta_unicast_port     = 7660;
    info.default_unicast_port  = 7661;
    info.vendor_id              = kVendorIdGoDDS;
    info.advertised_lease_duration = std::chrono::seconds(10);

    auto msg = build_spdp_announcement(info, SequenceNumber{0, 42});
    CHECK(to_hex(msg) ==
          "5254505302030127aabbccdd010203040506070815058c0000001000000100c7000100c20000"
          "00002a000000030000001500040002030000160004000127000050001000aabbccdd01020304"
          "05060708000001c1580004003f0000003200180001000000ec1d000000000000000000000000"
          "0000000000002f00180001000000ed1d00000000000000000000000000000000000002000800"
          "0a0000000000000001000000");
}

// ── parse_participant_data ───────────────────────────────────────────────────

TEST_CASE("parse_participant_data round-trips build_participant_data's output "
          "and fills in the from-address for 0.0.0.0 locators",
          "[rtps][spdp]") {
    auto info    = sample_local_info();
    auto payload = build_participant_data(info);

    auto proxy = parse_participant_data(sample_prefix(), payload.data(), payload.size(),
                                          "192.168.1.50");
    REQUIRE(proxy.has_value());

    CHECK(proxy->guid.prefix == sample_prefix());
    CHECK(proxy->guid.entity == kEntityIdParticipant);

    CHECK(proxy->metatraffic_unicast.kind == Locator::kKindUDPv4);
    CHECK(proxy->metatraffic_unicast.port == 7410);
    CHECK(proxy->metatraffic_unicast.address ==
          std::array<uint8_t, 16>{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 168, 1, 50});

    CHECK(proxy->default_unicast.kind == Locator::kKindUDPv4);
    CHECK(proxy->default_unicast.port == 7411);
    CHECK(proxy->default_unicast.address ==
          std::array<uint8_t, 16>{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 168, 1, 50});

    CHECK(proxy->builtin_endpoints == 0x3F);
    CHECK(proxy->lease_duration == std::chrono::seconds(10));
}

TEST_CASE("parse_participant_data rejects an invalid PL_CDR_LE header", "[rtps][spdp]") {
    auto bad = hex_to_bytes("01000000deadbeef"); // CDR_LE scheme, not PL_CDR_LE
    CHECK_FALSE(parse_participant_data(sample_prefix(), bad.data(), bad.size(), "127.0.0.1")
                    .has_value());
}

TEST_CASE("parse_participant_data leaves lease_duration at 0 when the PID is absent",
          "[rtps][spdp]") {
    PLCDREncoder enc;
    enc.add_param(kPidProtocolVersion, std::vector<uint8_t>{2, 3, 0, 0});
    auto payload = enc.finish();

    auto proxy = parse_participant_data(sample_prefix(), payload.data(), payload.size(),
                                          "127.0.0.1");
    REQUIRE(proxy.has_value());
    CHECK(proxy->lease_duration == std::chrono::seconds(0));
}

// ── wrap_in_rtps_message ──────────────────────────────────────────────────────

TEST_CASE("wrap_in_rtps_message prepends the 20-byte Header", "[rtps][spdp]") {
    std::vector<uint8_t> submsg{0xDE, 0xAD, 0xBE, 0xEF};
    auto msg = wrap_in_rtps_message(sample_prefix(), kVendorIdGoDDS, submsg);
    REQUIRE(msg.size() == Header::kSize + submsg.size());

    auto hdr = Header::decode(msg.data(), msg.size());
    REQUIRE(hdr.has_value());
    CHECK(hdr->guid_prefix == sample_prefix());
    CHECK(hdr->vendor_id == kVendorIdGoDDS);
    std::vector<uint8_t> tail(msg.begin() + Header::kSize, msg.end());
    CHECK(tail == submsg);
}

// ── SpdpService: known-peers table (behavioral) ──────────────────────────────

namespace {

// Builds a minimal SpdpService with two loopback unicast sockets bound to
// OS-assigned ports; dest_address/dest_port are left at the caller-supplied
// config values so tests can point announcements directly at a peer.
std::optional<SpdpService> make_service(SpdpConfig config) {
    auto send_sock = UdpSocket::bind_unicast(0);
    auto recv_sock = UdpSocket::bind_unicast(0);
    if (!send_sock || !recv_sock) return std::nullopt;
    return std::optional<SpdpService>(std::in_place, std::move(config), std::move(*send_sock),
                                       std::move(*recv_sock));
}

} // namespace

TEST_CASE("SpdpService::handle_packet ignores its own announcements", "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    auto msg = build_spdp_announcement(cfg.local, SequenceNumber{0, 1});
    svc->handle_packet(msg, "127.0.0.1");
    CHECK(svc->peers().empty());
    CHECK(svc->announces_received() == 0);
}

TEST_CASE("SpdpService::handle_packet stores a peer from a remote announcement",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    SpdpLocalInfo remote;
    remote.guid_prefix          = sample_prefix2();
    remote.meta_unicast_port     = 9000;
    remote.default_unicast_port  = 9001;

    auto msg = build_spdp_announcement(remote, SequenceNumber{0, 1});
    svc->handle_packet(msg, "10.0.0.5");

    auto peers = svc->peers();
    REQUIRE(peers.size() == 1);
    CHECK(peers[0].guid.prefix == sample_prefix2());
    CHECK(peers[0].metatraffic_unicast.port == 9000);
    CHECK(peers[0].default_unicast.port == 9001);
    CHECK(svc->announces_received() == 1);
}

TEST_CASE("SpdpService::handle_packet ignores a DATA submessage from a non-SPDP writer",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    SpdpLocalInfo remote;
    remote.guid_prefix = sample_prefix2();

    DataSubmessage ds;
    ds.reader_entity_id = kEntityIdSPDPReader;
    ds.writer_entity_id = kEntityIdSEDPPubWriter; // not the SPDP writer
    ds.seq_num           = SequenceNumber{0, 1};
    ds.payload            = build_participant_data(remote);
    std::vector<uint8_t> submsg;
    ds.encode(submsg);
    auto msg = wrap_in_rtps_message(remote.guid_prefix, kVendorIdCppDDS, submsg);

    svc->handle_packet(msg, "10.0.0.5");
    CHECK(svc->peers().empty());
}

TEST_CASE("SpdpService::evict_expired removes a peer whose advertised lease has elapsed",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    SpdpLocalInfo remote;
    remote.guid_prefix                 = sample_prefix2();
    remote.advertised_lease_duration    = std::chrono::seconds(1); // short, for a fast test

    auto msg = build_spdp_announcement(remote, SequenceNumber{0, 1});
    svc->handle_packet(msg, "10.0.0.5");
    REQUIRE(svc->peers().size() == 1);

    std::this_thread::sleep_for(1100ms);
    svc->evict_expired();

    CHECK(svc->peers().empty());
    CHECK(svc->peer_evictions() == 1);
}

TEST_CASE("SpdpService::evict_expired falls back to the configured peer_lease_duration "
          "when the peer's announcement omitted the lease PID",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix     = sample_prefix();
    cfg.peer_lease_duration    = std::chrono::seconds(1);
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    // Hand-build a payload with no pidParticipantLeaseDuration, so
    // parse_participant_data leaves ParticipantProxy::lease_duration at 0
    // and store_peer must apply config_.peer_lease_duration.
    PLCDREncoder enc;
    enc.add_param(kPidProtocolVersion, std::vector<uint8_t>{2, 3, 0, 0});
    GUID g;
    g.prefix = sample_prefix2();
    g.entity = kEntityIdParticipant;
    enc.add_guid(kPidParticipantGUID, g);
    auto payload = enc.finish();

    DataSubmessage ds;
    ds.reader_entity_id = kEntityIdSPDPReader;
    ds.writer_entity_id = kEntityIdSPDPWriter;
    ds.seq_num           = SequenceNumber{0, 1};
    ds.payload            = payload;
    std::vector<uint8_t> submsg;
    ds.encode(submsg);
    auto msg = wrap_in_rtps_message(sample_prefix2(), kVendorIdCppDDS, submsg);

    svc->handle_packet(msg, "10.0.0.5");
    REQUIRE(svc->peers().size() == 1);

    std::this_thread::sleep_for(1100ms);
    svc->evict_expired();
    CHECK(svc->peers().empty());
}

TEST_CASE("SpdpService::send_announcement transmits a decodable SPDP announcement",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix     = sample_prefix();
    cfg.local.meta_unicast_port = 12345;

    auto send_sock = UdpSocket::bind_unicast(0);
    auto recv_sock = UdpSocket::bind_unicast(0);
    REQUIRE(send_sock.has_value());
    REQUIRE(recv_sock.has_value());

    // Point the announcement directly at recv_sock's loopback port, sidestepping
    // real multicast delivery (see file-level test-scope note above).
    cfg.dest_address = "127.0.0.1";
    cfg.dest_port    = recv_sock->port();

    SpdpService svc(cfg, std::move(*send_sock), std::move(*recv_sock));
    svc.send_announcement();
    CHECK(svc.announces_sent() == 1);
}

TEST_CASE("Two SpdpService instances discover each other over loopback", "[rtps][spdp]") {
    auto a_send = UdpSocket::bind_unicast(0);
    auto a_recv = UdpSocket::bind_unicast(0);
    auto b_send = UdpSocket::bind_unicast(0);
    auto b_recv = UdpSocket::bind_unicast(0);
    REQUIRE(a_send.has_value());
    REQUIRE(a_recv.has_value());
    REQUIRE(b_send.has_value());
    REQUIRE(b_recv.has_value());

    const int a_recv_port = a_recv->port();
    const int b_recv_port = b_recv->port();

    SpdpConfig cfg_a;
    cfg_a.local.guid_prefix          = sample_prefix();
    cfg_a.local.meta_unicast_port     = static_cast<uint16_t>(a_send->port());
    cfg_a.local.default_unicast_port  = static_cast<uint16_t>(a_send->port());
    cfg_a.announce_period              = 100ms; // faster than the 2s production default, for test speed
    cfg_a.dest_address                 = "127.0.0.1";
    cfg_a.dest_port                    = b_recv_port;

    SpdpConfig cfg_b;
    cfg_b.local.guid_prefix          = sample_prefix2();
    cfg_b.local.meta_unicast_port     = static_cast<uint16_t>(b_send->port());
    cfg_b.local.default_unicast_port  = static_cast<uint16_t>(b_send->port());
    cfg_b.announce_period              = 100ms;
    cfg_b.dest_address                 = "127.0.0.1";
    cfg_b.dest_port                    = a_recv_port;

    SpdpService svc_a(cfg_a, std::move(*a_send), std::move(*a_recv));
    SpdpService svc_b(cfg_b, std::move(*b_send), std::move(*b_recv));

    svc_a.start();
    svc_b.start();

    bool a_sees_b = false;
    bool b_sees_a = false;
    for (int attempt = 0; attempt < 60 && !(a_sees_b && b_sees_a); ++attempt) {
        std::this_thread::sleep_for(50ms);
        if (!svc_a.peers().empty()) a_sees_b = true;
        if (!svc_b.peers().empty()) b_sees_a = true;
    }

    svc_a.stop();
    svc_b.stop();

    REQUIRE(a_sees_b);
    REQUIRE(b_sees_a);

    auto peers_a = svc_a.peers();
    REQUIRE(peers_a.size() == 1);
    CHECK(peers_a[0].guid.prefix == sample_prefix2());
    CHECK(peers_a[0].builtin_endpoints == 0x3F);

    auto peers_b = svc_b.peers();
    REQUIRE(peers_b.size() == 1);
    CHECK(peers_b[0].guid.prefix == sample_prefix());
}

TEST_CASE("SpdpService::start/stop is idempotent and safe to call repeatedly",
          "[rtps][spdp]") {
    SpdpConfig cfg;
    cfg.local.guid_prefix = sample_prefix();
    cfg.announce_period    = 500ms;
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    svc->start();
    svc->start(); // no-op: already running
    std::this_thread::sleep_for(20ms);
    svc->stop();
    svc->stop(); // no-op: already stopped
}
