// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Tests for dds::cdr — a C++ port of github.com/SoundMatt/go-DDS's
// top-level `cdr` package (tools/cdr/cdr.go / cdr_test.go), the
// correctness oracle named in cpp-DDS's ROADMAP.md ("Tier 3 — xtypes,
// tsn, idl, cdr", `cdr`). Deliberately a separate suite from
// test_rtps_cdr.cpp, which covers the unrelated discovery-scoped
// dds::rtps::PLCDREncoder/PLCDRDecoder pair — see include/dds/cdr/cdr.hpp
// for why these two libraries must not be conflated.
//
// fusa:test REQ-CDR-001 REQ-CDR-002 REQ-CDR-003 REQ-CDR-004 REQ-CDR-005
//
// ── How every hex reference vector below was derived ─────────────────────────
//
// go-DDS's cdr.Encoder/cdr.Decoder are fully exported, so the vectors were
// generated by calling those *actual* functions directly from a scratch
// _test.go file placed temporarily inside a fresh clone of go-DDS's
// tools/cdr package (never committed to go-DDS, never pushed anywhere) —
// the same derivation convention used by test_xtypes.cpp/test_rtps_cdr.cpp/
// test_safety_e2e.cpp:
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS/tools/cdr
//   cat > zzz_scratch_cppdds_vectors_test.go <<'EOF'
//   package cdr
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSCDRReferenceVectors(t *testing.T) {
//       printBytes := func(label string, e *Encoder) {
//           fmt.Printf("%s = %s\n", label, hex.EncodeToString(e.Bytes()))
//       }
//       // ... one Encoder + printBytes(...) call per vector below, plus a
//       // few direct NewDecoder(...) calls for the header-acceptance/
//       // rejection vectors.
//   }
//   EOF
//   go test . -run TestPrintCppDDSCDRReferenceVectors -v
//
// Reproduced 2026-07-27 against go-DDS commit
// 1691286d7857885f0fb8aab0d5303e945ec144fd. Raw captured output:
//
//   BOOL_TRUE = 0100000001
//   BOOL_FALSE = 0100000000
//   UINT8 = 01000000ff
//   INT8 = 01000000f9
//   INT16 = 010000002efb
//   UINT16 = 01000000cdab
//   INT32 = 01000000eb32a4f8
//   UINT32 = 01000000efbeadde
//   INT64 = 010000000000000016e94fb3fdffffff
//   UINT64 = 0100000000000000efbeaddebebafeca
//   FLOAT32 = 01000000c3f54840
//   FLOAT64 = 01000000000000009b91048b0abf0540
//   STRING_"" = 010000000100000000
//   STRING_"hello" = 010000000600000068656c6c6f00
//   STRING_"go-DDS IDL" = 010000000b000000676f2d4444532049444c00
//   STRING_"unicode: 日本語" = 0100000013000000756e69636f64653a20e697a5e69cace8aa9e00
//   BYTES = 01000000040000000001ff80
//   BYTES_EMPTY = 0100000000000000
//   ALIGN_BOOL_INT32 = 01000000010000002a000000
//   ALIGN_UINT8_INT64 = 01000000010000000012863897010000
//   ALIGN_INT16_INT16_INT32 = 010000000100020003000000
//   MULTI_FIELD = 01000000060000004543552d310000000000000000e0574000128638970100000100000007000000
//   ALIGN_BOOL_STRING = 010000000100000003000000686900
//   EMPTY = 01000000
//   BE_SCHEME_ACCEPTED = true (remaining=0)
//   BAD_SCHEME_ERROR = "cdr: unsupported encapsulation scheme 0xffff"
//   TOO_SHORT_ERROR = "cdr: data too short for encapsulation header (1 bytes)"

#include <dds/cdr/cdr.hpp>
#include <catch2/catch_test_macros.hpp>

#include <cmath>

using namespace dds::cdr;

namespace {

std::string to_hex(const std::vector<uint8_t>& b) {
    static const char* digits = "0123456789abcdef";
    std::string out;
    out.reserve(b.size() * 2);
    for (uint8_t byte : b) {
        out.push_back(digits[byte >> 4]);
        out.push_back(digits[byte & 0x0F]);
    }
    return out;
}

} // namespace

// ── Byte-exact reference-vector tests ────────────────────────────────────────

TEST_CASE("cdr: encoder byte-exact primitives match go-DDS", "[cdr][vectors]") {
    {
        Encoder e;
        e.write_bool(true);
        REQUIRE(to_hex(e.bytes()) == "0100000001");
    }
    {
        Encoder e;
        e.write_bool(false);
        REQUIRE(to_hex(e.bytes()) == "0100000000");
    }
    {
        Encoder e;
        e.write_uint8(0xFF);
        REQUIRE(to_hex(e.bytes()) == "01000000ff");
    }
    {
        Encoder e;
        e.write_int8(-7);
        REQUIRE(to_hex(e.bytes()) == "01000000f9");
    }
    {
        Encoder e;
        e.write_int16(-1234);
        REQUIRE(to_hex(e.bytes()) == "010000002efb");
    }
    {
        Encoder e;
        e.write_uint16(0xABCD);
        REQUIRE(to_hex(e.bytes()) == "01000000cdab");
    }
    {
        Encoder e;
        e.write_int32(-123456789);
        REQUIRE(to_hex(e.bytes()) == "01000000eb32a4f8");
    }
    {
        Encoder e;
        e.write_uint32(0xDEADBEEF);
        REQUIRE(to_hex(e.bytes()) == "01000000efbeadde");
    }
    {
        Encoder e;
        e.write_int64(-9876543210LL);
        REQUIRE(to_hex(e.bytes()) == "010000000000000016e94fb3fdffffff");
    }
    {
        Encoder e;
        e.write_uint64(0xCAFEBABEDEADBEEFULL);
        REQUIRE(to_hex(e.bytes()) == "0100000000000000efbeaddebebafeca");
    }
    {
        Encoder e;
        e.write_float32(3.14F);
        REQUIRE(to_hex(e.bytes()) == "01000000c3f54840");
    }
    {
        Encoder e;
        e.write_float64(2.718281828);
        REQUIRE(to_hex(e.bytes()) == "01000000000000009b91048b0abf0540");
    }
}

TEST_CASE("cdr: encoder byte-exact strings/bytes match go-DDS", "[cdr][vectors]") {
    {
        Encoder e;
        e.write_string("");
        REQUIRE(to_hex(e.bytes()) == "010000000100000000");
    }
    {
        Encoder e;
        e.write_string("hello");
        REQUIRE(to_hex(e.bytes()) == "010000000600000068656c6c6f00");
    }
    {
        Encoder e;
        e.write_string("go-DDS IDL");
        REQUIRE(to_hex(e.bytes()) == "010000000b000000676f2d4444532049444c00");
    }
    {
        Encoder e;
        e.write_string("unicode: \xE6\x97\xA5\xE6\x9C\xAC\xE8\xAA\x9E"); // "unicode: 日本語"
        REQUIRE(to_hex(e.bytes()) == "0100000013000000756e69636f64653a20e697a5e69cace8aa9e00");
    }
    {
        Encoder e;
        e.write_bytes({0x00, 0x01, 0xFF, 0x80});
        REQUIRE(to_hex(e.bytes()) == "01000000040000000001ff80");
    }
    {
        Encoder e;
        e.write_bytes({});
        REQUIRE(to_hex(e.bytes()) == "0100000000000000");
    }
}

TEST_CASE("cdr: encoder byte-exact alignment matches go-DDS", "[cdr][vectors]") {
    {
        Encoder e;
        e.write_bool(true);
        e.write_int32(42);
        REQUIRE(to_hex(e.bytes()) == "01000000010000002a000000");
    }
    {
        Encoder e;
        e.write_uint8(1);
        e.write_int64(1749000000000LL);
        REQUIRE(to_hex(e.bytes()) == "01000000010000000012863897010000");
    }
    {
        Encoder e;
        e.write_int16(1);
        e.write_int16(2);
        e.write_int32(3);
        REQUIRE(to_hex(e.bytes()) == "010000000100020003000000");
    }
    {
        Encoder e;
        e.write_string("ECU-1");
        e.write_float64(95.5);
        e.write_int64(1749000000000LL);
        e.write_bool(true);
        e.write_uint32(7);
        REQUIRE(to_hex(e.bytes()) ==
                "01000000060000004543552d310000000000000000e0574000128638970100000100000007000000");
    }
    {
        Encoder e;
        e.write_bool(true);
        e.write_string("hi");
        REQUIRE(to_hex(e.bytes()) == "010000000100000003000000686900");
    }
    {
        Encoder e;
        REQUIRE(to_hex(e.bytes()) == "01000000");
        REQUIRE(e.len() == 4);
    }
}

TEST_CASE("cdr: decoder accepts CDR_LE and CDR_BE encapsulation schemes", "[cdr][vectors]") {
    // CDR_BE-scheme header (0x0000) is accepted by Decoder::create (decoded
    // as LE regardless of the header) -- go-DDS: NewDecoder's accept-both quirk.
    std::vector<uint8_t> be_header{0x00, 0x00, 0x00, 0x00};
    auto d = Decoder::create(be_header);
    REQUIRE(d.has_value());
    REQUIRE(d->remaining() == 0);
}

TEST_CASE("cdr: decoder rejects unsupported scheme and short buffer", "[cdr][vectors]") {
    REQUIRE_FALSE(Decoder::create(std::vector<uint8_t>{0xFF, 0xFF, 0x00, 0x00}).has_value());
    REQUIRE_FALSE(Decoder::create(std::vector<uint8_t>{0x00}).has_value());
}

// ── Behavioral parity with go-DDS's own cdr_test.go matrix ───────────────────

TEST_CASE("cdr: bool round trip", "[cdr]") {
    Encoder e;
    e.write_bool(true);
    e.write_bool(false);
    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    auto v1 = d->read_bool();
    REQUIRE(v1.has_value());
    REQUIRE(*v1 == true);
    auto v2 = d->read_bool();
    REQUIRE(v2.has_value());
    REQUIRE(*v2 == false);
}

TEST_CASE("cdr: uint8 round trip", "[cdr]") {
    Encoder e;
    e.write_uint8(0xFF);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_uint8();
    REQUIRE(v.has_value());
    REQUIRE(*v == 0xFF);
}

TEST_CASE("cdr: int8 round trip", "[cdr]") {
    Encoder e;
    e.write_int8(-7);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_int8();
    REQUIRE(v.has_value());
    REQUIRE(*v == -7);
}

TEST_CASE("cdr: int16 round trip", "[cdr]") {
    Encoder e;
    e.write_int16(-1234);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_int16();
    REQUIRE(v.has_value());
    REQUIRE(*v == -1234);
}

TEST_CASE("cdr: uint16 round trip", "[cdr]") {
    Encoder e;
    e.write_uint16(0xABCD);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_uint16();
    REQUIRE(v.has_value());
    REQUIRE(*v == 0xABCD);
}

TEST_CASE("cdr: int32 round trip", "[cdr]") {
    Encoder e;
    e.write_int32(-123456789);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_int32();
    REQUIRE(v.has_value());
    REQUIRE(*v == -123456789);
}

TEST_CASE("cdr: uint32 round trip", "[cdr]") {
    Encoder e;
    e.write_uint32(0xDEADBEEF);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_uint32();
    REQUIRE(v.has_value());
    REQUIRE(*v == 0xDEADBEEF);
}

TEST_CASE("cdr: int64 round trip", "[cdr]") {
    Encoder e;
    e.write_int64(-9876543210LL);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_int64();
    REQUIRE(v.has_value());
    REQUIRE(*v == -9876543210LL);
}

TEST_CASE("cdr: uint64 round trip", "[cdr]") {
    Encoder e;
    e.write_uint64(0xCAFEBABEDEADBEEFULL);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_uint64();
    REQUIRE(v.has_value());
    REQUIRE(*v == 0xCAFEBABEDEADBEEFULL);
}

TEST_CASE("cdr: float32 round trip", "[cdr]") {
    Encoder e;
    e.write_float32(3.14F);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_float32();
    REQUIRE(v.has_value());
    REQUIRE(std::abs(*v - 3.14F) <= 0.001F);
}

TEST_CASE("cdr: float64 round trip", "[cdr]") {
    Encoder e;
    e.write_float64(2.718281828);
    auto d = Decoder::create(e.bytes());
    auto v = d->read_float64();
    REQUIRE(v.has_value());
    REQUIRE(std::abs(*v - 2.718281828) <= 1e-9);
}

TEST_CASE("cdr: string round trip", "[cdr]") {
    std::vector<std::string> cases = {"", "hello", "go-DDS IDL", "unicode: \xE6\x97\xA5\xE6\x9C\xAC\xE8\xAA\x9E"};
    for (const auto& s : cases) {
        Encoder e;
        e.write_string(s);
        auto d = Decoder::create(e.bytes());
        REQUIRE(d.has_value());
        auto v = d->read_string();
        REQUIRE(v.has_value());
        REQUIRE(*v == s);
    }
}

TEST_CASE("cdr: bytes round trip", "[cdr]") {
    std::vector<uint8_t> data = {0x00, 0x01, 0xFF, 0x80};
    Encoder e;
    e.write_bytes(data);
    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    auto v = d->read_bytes();
    REQUIRE(v.has_value());
    REQUIRE(*v == data);
}

TEST_CASE("cdr: alignment between bool and int32", "[cdr]") {
    Encoder e;
    e.write_bool(true);
    e.write_int32(42);
    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    auto b = d->read_bool();
    auto n = d->read_int32();
    REQUIRE(b.has_value());
    REQUIRE(*b == true);
    REQUIRE(n.has_value());
    REQUIRE(*n == 42);
}

TEST_CASE("cdr: multi-field struct simulation round trip", "[cdr]") {
    Encoder e;
    e.write_string("ECU-1");
    e.write_float64(95.5);
    e.write_int64(1749000000000LL);
    e.write_bool(true);
    e.write_uint32(7);

    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    auto s = d->read_string();
    REQUIRE(s.has_value());
    auto f = d->read_float64();
    REQUIRE(f.has_value());
    auto ts = d->read_int64();
    REQUIRE(ts.has_value());
    auto ok = d->read_bool();
    REQUIRE(ok.has_value());
    auto n = d->read_uint32();
    REQUIRE(n.has_value());

    REQUIRE(*s == "ECU-1");
    REQUIRE(std::abs(*f - 95.5) <= 1e-9);
    REQUIRE(*ts == 1749000000000LL);
    REQUIRE(*ok == true);
    REQUIRE(*n == 7);
}

TEST_CASE("cdr: decoder rejects buffer too short for header", "[cdr]") {
    std::vector<uint8_t> data = {0x00}; // shorter than 4-byte header
    auto d = Decoder::create(data);
    REQUIRE_FALSE(d.has_value());
}

TEST_CASE("cdr: decoder rejects bad scheme", "[cdr]") {
    std::vector<uint8_t> data = {0xFF, 0xFF, 0x00, 0x00};
    auto d = Decoder::create(data);
    REQUIRE_FALSE(d.has_value());
}

TEST_CASE("cdr: encoder len tracks header and writes", "[cdr]") {
    Encoder e;
    REQUIRE(e.len() == 4); // encapsulation header is 4 bytes
    e.write_int32(42);
    REQUIRE(e.len() == 8);
}

TEST_CASE("cdr: decoder remaining tracks consumed bytes", "[cdr]") {
    Encoder e;
    e.write_int32(1);
    e.write_int32(2);
    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    REQUIRE(d->remaining() == 8); // two int32 fields = 8 bytes
    auto v = d->read_int32();
    REQUIRE(v.has_value());
    REQUIRE(d->remaining() == 4);
}

TEST_CASE("cdr: decoder underrun on second read past end", "[cdr]") {
    Encoder e;
    e.write_int32(1);
    auto d = Decoder::create(e.bytes());
    REQUIRE(d.has_value());
    auto v1 = d->read_int32();
    REQUIRE(v1.has_value());
    auto v2 = d->read_int32(); // underrun
    REQUIRE_FALSE(v2.has_value());
}

// Covers the need()-return-nullopt branch in every typed read_*() method
// that has no prior underrun test above, mirroring go-DDS's
// TestDecoder_Underrun_AllTypes.
TEST_CASE("cdr: decoder underrun on every primitive read", "[cdr]") {
    auto empty_decoder = []() {
        Encoder e;
        auto d = Decoder::create(e.bytes());
        REQUIRE(d.has_value());
        return *d;
    };

    SECTION("read_bool") {
        auto d = empty_decoder();
        REQUIRE_FALSE(d.read_bool().has_value());
    }
    SECTION("read_uint8") {
        auto d = empty_decoder();
        REQUIRE_FALSE(d.read_uint8().has_value());
    }
    SECTION("read_int16") {
        auto d = empty_decoder();
        REQUIRE_FALSE(d.read_int16().has_value());
    }
    SECTION("read_uint16") {
        auto d = empty_decoder();
        REQUIRE_FALSE(d.read_uint16().has_value());
    }
    SECTION("read_string_data_underrun") {
        // Write a uint32 length = 4, but no actual string bytes follow.
        Encoder e;
        e.write_uint32(4);
        auto d = Decoder::create(e.bytes());
        REQUIRE(d.has_value());
        REQUIRE_FALSE(d->read_string().has_value());
    }
    SECTION("read_string_zero_length") {
        // CDR string with explicit length=0 covers the n==0 defensive branch.
        Encoder e;
        e.write_uint32(0);
        auto d = Decoder::create(e.bytes());
        REQUIRE(d.has_value());
        auto s = d->read_string();
        REQUIRE(s.has_value());
        REQUIRE(*s == "");
    }
    SECTION("read_bytes_data_underrun") {
        // Write a uint32 length = 4, but no actual bytes follow.
        Encoder e;
        e.write_uint32(4);
        auto d = Decoder::create(e.bytes());
        REQUIRE(d.has_value());
        REQUIRE_FALSE(d->read_bytes().has_value());
    }
}
