// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Byte-exact wire compatibility tests for dds::rtps::PLCDREncoder/Decoder
// (and the CDR_LE payload wrap/unwrap helpers) against
// github.com/SoundMatt/go-DDS's `rtps` package (rtps/cdr.go +
// rtps/message.go's cdrWrapPayload/cdrUnwrapPayload) — the correctness
// oracle named in cpp-DDS's ROADMAP.md ("Tier 1 — RTPS wire protocol",
// phase 2: "Discovery-scoped CDR/PL_CDR encoding").
//
// ── How every *_HEX constant below was derived ──────────────────────────────
//
// go-DDS's plCDREncoder/plCDRDecoder methods (newPLCDREncoder, addParam,
// addUint32, addLocator, addGUID, addString, addBytes, finish,
// newPLCDRDecoder, next, decodeString, decodeGUID) and message.go's
// cdrWrapPayload/cdrUnwrapPayload are all unexported, so they cannot be
// called from an external `go run` program. As with test_rtps_types.cpp,
// the vectors were generated by calling those *actual* functions
// white-box, from a scratch _test.go file placed temporarily inside a
// fresh clone of go-DDS's rtps package (never committed to go-DDS, never
// pushed anywhere):
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS
//   cat > rtps/zzz_scratch_cdr_vectors_test.go <<'EOF'
//   package rtps
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSCDRReferenceVectors(t *testing.T) {
//       enc := newPLCDREncoder()
//       enc.addUint32(pidBuiltinEndpointSet, 0x0000003F)
//       fmt.Println("CDR_ADD_UINT32_HEX =", hex.EncodeToString(enc.finish()))
//
//       loc := Locator{Kind: LocatorKindUDPv4, Port: 7412}
//       copy(loc.Address[12:], []byte{192, 168, 1, 10})
//       enc2 := newPLCDREncoder()
//       enc2.addLocator(pidDefaultUnicastLocator, loc)
//       fmt.Println("CDR_ADD_LOCATOR_HEX =", hex.EncodeToString(enc2.finish()))
//
//       prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//       g := GUID{Prefix: prefix, Entity: EntityIdParticipant}
//       enc3 := newPLCDREncoder()
//       enc3.addGUID(pidParticipantGUID, g)
//       fmt.Println("CDR_ADD_GUID_HEX =", hex.EncodeToString(enc3.finish()))
//
//       enc4 := newPLCDREncoder()
//       enc4.addString(pidTopicName, "Square")
//       fmt.Println("CDR_ADD_STRING_HEX =", hex.EncodeToString(enc4.finish()))
//
//       enc5 := newPLCDREncoder()
//       enc5.addString(pidTypeName, "Sq")
//       fmt.Println("CDR_ADD_STRING_NOPAD_HEX =", hex.EncodeToString(enc5.finish()))
//
//       enc6 := newPLCDREncoder()
//       enc6.addString(pidTopicName, "")
//       fmt.Println("CDR_ADD_STRING_EMPTY_HEX =", hex.EncodeToString(enc6.finish()))
//
//       enc7 := newPLCDREncoder()
//       enc7.addBytes(pidDiscoveryToken, []byte{0xAA, 0xBB, 0xCC})
//       fmt.Println("CDR_ADD_BYTES_HEX =", hex.EncodeToString(enc7.finish()))
//
//       enc8 := newPLCDREncoder()
//       enc8.addParam(pidPad, nil)
//       fmt.Println("CDR_ADD_PARAM_ZEROLEN_HEX =", hex.EncodeToString(enc8.finish()))
//
//       enc9 := newPLCDREncoder()
//       enc9.addParam(pidProtocolVersion, []byte{2, 3, 0, 0})
//       enc9.addParam(pidVendorId, []byte{goVendorId[0], goVendorId[1], 0, 0})
//       enc9.addGUID(pidParticipantGUID, GUID{Prefix: prefix, Entity: EntityIdParticipant})
//       enc9.addUint32(pidBuiltinEndpointSet, 0x0000003F)
//       loc2 := Locator{Kind: LocatorKindUDPv4, Port: 7400}
//       copy(loc2.Address[12:], []byte{239, 255, 0, 1})
//       enc9.addLocator(pidMetatrafficMulticastLocator, loc2)
//       enc9.addParam(pidParticipantLeaseDuration, []byte{100, 0, 0, 0, 0, 0, 0, 0})
//       full := enc9.finish()
//       fmt.Println("CDR_SPDP_SHAPED_HEX =", hex.EncodeToString(full))
//
//       payload := []byte{0xDE, 0xAD, 0xBE, 0xEF}
//       wrapped := cdrWrapPayload(payload)
//       fmt.Println("CDR_WRAP_PAYLOAD_HEX =", hex.EncodeToString(wrapped))
//   }
//   EOF
//   go test ./rtps -run TestPrintCppDDSCDRReferenceVectors -v
//
// That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//   CDR_ADD_UINT32_HEX        = 03000000580004003f00000001000000
//   CDR_ADD_LOCATOR_HEX       = 030000002f00180001000000f41c0000000000000000000000000000c0a8010a01000000
//   CDR_ADD_GUID_HEX          = 0300000050001000010f996ecafebabe00000001000001c101000000
//   CDR_ADD_STRING_HEX        = 0300000005000c0007000000537175617265000001000000
//   CDR_ADD_STRING_NOPAD_HEX  = 0300000007000800030000005371000001000000
//   CDR_ADD_STRING_EMPTY_HEX  = 0300000005000800010000000000000001000000
//   CDR_ADD_BYTES_HEX         = 0300000001800400aabbcc0001000000
//   CDR_ADD_PARAM_ZEROLEN_HEX = 030000000000000001000000
//   CDR_SPDP_SHAPED_HEX       = 030000001500040002030000160004000127000050001000010f996ecafebabe00000001000001c1580004003f0000003300180001000000e81c0000000000000000000000000000efff000102000800640000000000000001000000
//   CDR_WRAP_PAYLOAD_HEX      = 01000000deadbeef
//
// (The full derivation also exercised the decoder — newPLCDRDecoder +
// next() — by round-tripping CDR_SPDP_SHAPED_HEX and confirming it yields
// exactly the (pid, value) pairs asserted below, and cdrUnwrapPayload on
// CDR_WRAP_PAYLOAD_HEX round-trips to the original payload.)

#include <dds/rtps/cdr.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cctype>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

using namespace dds::rtps;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}

} // namespace

// ── PLCDREncoder ──────────────────────────────────────────────────────────

TEST_CASE("PLCDREncoder::add_uint32 matches go-DDS reference vector", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_uint32(kPidBuiltinEndpointSet, 0x0000003F);
    CHECK(to_hex(enc.finish()) == "03000000580004003f00000001000000");
}

TEST_CASE("PLCDREncoder::add_locator matches go-DDS reference vector", "[rtps][cdr]") {
    Locator l;
    l.kind = Locator::kKindUDPv4;
    l.port = 7412;
    l.address = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 168, 1, 10};

    PLCDREncoder enc;
    enc.add_locator(kPidDefaultUnicastLocator, l);
    CHECK(to_hex(enc.finish()) ==
          "030000002f00180001000000f41c0000000000000000000000000000c0a8010a01000000");
}

TEST_CASE("PLCDREncoder::add_guid matches go-DDS reference vector", "[rtps][cdr]") {
    GUID g;
    g.prefix = sample_prefix();
    g.entity = kEntityIdParticipant;

    PLCDREncoder enc;
    enc.add_guid(kPidParticipantGUID, g);
    CHECK(to_hex(enc.finish()) ==
          "0300000050001000010f996ecafebabe00000001000001c101000000");
}

TEST_CASE("PLCDREncoder::add_string pads to 4-byte boundary, matching go-DDS", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_string(kPidTopicName, "Square");
    CHECK(to_hex(enc.finish()) == "0300000005000c0007000000537175617265000001000000");
}

TEST_CASE("PLCDREncoder::add_string emits zero padding when already aligned", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_string(kPidTypeName, "Sq");
    CHECK(to_hex(enc.finish()) == "0300000007000800030000005371000001000000");
}

TEST_CASE("PLCDREncoder::add_string handles the empty string", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_string(kPidTopicName, "");
    CHECK(to_hex(enc.finish()) == "0300000005000800010000000000000001000000");
}

TEST_CASE("PLCDREncoder::add_bytes matches go-DDS reference vector", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_bytes(kPidDiscoveryToken, {0xAA, 0xBB, 0xCC});
    CHECK(to_hex(enc.finish()) == "0300000001800400aabbcc0001000000");
}

TEST_CASE("PLCDREncoder::add_param handles a zero-length value", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_param(kPidPad, nullptr, 0);
    CHECK(to_hex(enc.finish()) == "030000000000000001000000");
}

TEST_CASE("PLCDREncoder builds a full SPDP-shaped parameter list matching go-DDS", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_param(kPidProtocolVersion, std::vector<uint8_t>{2, 3, 0, 0});
    enc.add_param(kPidVendorId, std::vector<uint8_t>{kVendorIdGoDDS.bytes[0], kVendorIdGoDDS.bytes[1], 0, 0});

    GUID g;
    g.prefix = sample_prefix();
    g.entity = kEntityIdParticipant;
    enc.add_guid(kPidParticipantGUID, g);

    enc.add_uint32(kPidBuiltinEndpointSet, 0x0000003F);

    Locator loc;
    loc.kind = Locator::kKindUDPv4;
    loc.port = 7400;
    loc.address = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 239, 255, 0, 1};
    enc.add_locator(kPidMetatrafficMulticastLocator, loc);

    enc.add_param(kPidParticipantLeaseDuration,
                   std::vector<uint8_t>{100, 0, 0, 0, 0, 0, 0, 0});

    auto out = enc.finish();
    CHECK(to_hex(out) ==
          "030000001500040002030000160004000127000050001000010f996ecafebabe0000000"
          "1000001c1580004003f0000003300180001000000e81c00000000000000000000000000"
          "00efff000102000800640000000000000001000000");
}

// ── PLCDRDecoder ──────────────────────────────────────────────────────────

TEST_CASE("PLCDRDecoder round-trips the SPDP-shaped reference vector", "[rtps][cdr]") {
    auto bytes = hex_to_bytes(
        "030000001500040002030000160004000127000050001000010f996ecafebabe0000000"
        "1000001c1580004003f0000003300180001000000e81c00000000000000000000000000"
        "00efff000102000800640000000000000001000000");

    auto dec = PLCDRDecoder::create(bytes.data(), bytes.size());
    REQUIRE(dec.has_value());

    struct Expected {
        uint16_t pid;
        std::string value_hex;
    };
    const std::vector<Expected> expected = {
        {kPidProtocolVersion, "02030000"},
        {kPidVendorId, "01270000"},
        {kPidParticipantGUID, "010f996ecafebabe00000001000001c1"},
        {kPidBuiltinEndpointSet, "3f000000"},
        {kPidMetatrafficMulticastLocator, "01000000e81c0000000000000000000000000000efff0001"},
        {kPidParticipantLeaseDuration, "6400000000000000"},
    };

    for (const auto& want : expected) {
        auto p = dec->next();
        REQUIRE(p.has_value());
        CHECK(p->pid == want.pid);
        std::vector<uint8_t> value(p->value, p->value + p->value_len);
        CHECK(to_hex(value) == want.value_hex);
    }
    // Sentinel reached: no more parameters.
    CHECK_FALSE(dec->next().has_value());
}

TEST_CASE("PLCDRDecoder::create rejects a bad scheme or short buffer", "[rtps][cdr]") {
    auto bad_scheme = hex_to_bytes("01000000"); // CDR_LE, not PL_CDR_LE
    CHECK_FALSE(PLCDRDecoder::create(bad_scheme.data(), bad_scheme.size()).has_value());

    std::array<uint8_t, 3> too_short{};
    CHECK_FALSE(PLCDRDecoder::create(too_short.data(), too_short.size()).has_value());
}

TEST_CASE("PLCDRDecoder::next rejects a truncated parameter value", "[rtps][cdr]") {
    // Header + a param claiming length 8 but only 2 bytes follow.
    auto bytes = hex_to_bytes("0300000005000800aabb");
    auto dec = PLCDRDecoder::create(bytes.data(), bytes.size());
    REQUIRE(dec.has_value());
    CHECK_FALSE(dec->next().has_value());
}

// ── decode_string / decode_guid ──────────────────────────────────────────

TEST_CASE("decode_string reads back an add_string-encoded value", "[rtps][cdr]") {
    PLCDREncoder enc;
    enc.add_string(kPidTopicName, "Square");
    auto out = enc.finish();

    auto dec = PLCDRDecoder::create(out.data(), out.size());
    REQUIRE(dec.has_value());
    auto p = dec->next();
    REQUIRE(p.has_value());
    CHECK(p->pid == kPidTopicName);

    auto s = decode_string(p->value, p->value_len);
    REQUIRE(s.has_value());
    CHECK(*s == "Square");
}

TEST_CASE("decode_string rejects a too-short buffer", "[rtps][cdr]") {
    std::array<uint8_t, 3> too_short{};
    CHECK_FALSE(decode_string(too_short.data(), too_short.size()).has_value());
}

TEST_CASE("decode_guid reads back an add_guid-encoded value", "[rtps][cdr]") {
    GUID g;
    g.prefix = sample_prefix();
    g.entity = kEntityIdParticipant;

    PLCDREncoder enc;
    enc.add_guid(kPidParticipantGUID, g);
    auto out = enc.finish();

    auto dec = PLCDRDecoder::create(out.data(), out.size());
    REQUIRE(dec.has_value());
    auto p = dec->next();
    REQUIRE(p.has_value());

    auto decoded = decode_guid(p->value, p->value_len);
    REQUIRE(decoded.has_value());
    CHECK(*decoded == g);
}

// ── CDR_LE payload wrap/unwrap ────────────────────────────────────────────

TEST_CASE("cdr_wrap_payload matches go-DDS reference vector", "[rtps][cdr]") {
    std::vector<uint8_t> payload{0xDE, 0xAD, 0xBE, 0xEF};
    CHECK(to_hex(cdr_wrap_payload(payload)) == "01000000deadbeef");
}

TEST_CASE("cdr_unwrap_payload round-trips cdr_wrap_payload's output", "[rtps][cdr]") {
    std::vector<uint8_t> payload{0xDE, 0xAD, 0xBE, 0xEF};
    auto wrapped = cdr_wrap_payload(payload);
    auto unwrapped = cdr_unwrap_payload(wrapped);
    REQUIRE(unwrapped.has_value());
    CHECK(*unwrapped == payload);
}

TEST_CASE("cdr_unwrap_payload accepts both CDR_LE and PL_CDR_LE schemes", "[rtps][cdr]") {
    auto cdr_bytes = hex_to_bytes("01000000deadbeef");
    auto r1 = cdr_unwrap_payload(cdr_bytes);
    REQUIRE(r1.has_value());
    CHECK(to_hex(*r1) == "deadbeef");

    auto plcdr_bytes = hex_to_bytes("03000000deadbeef");
    auto r2 = cdr_unwrap_payload(plcdr_bytes);
    REQUIRE(r2.has_value());
    CHECK(to_hex(*r2) == "deadbeef");
}

TEST_CASE("cdr_unwrap_payload rejects a bad scheme or short buffer", "[rtps][cdr]") {
    auto bad_scheme = hex_to_bytes("99000000deadbeef");
    CHECK_FALSE(cdr_unwrap_payload(bad_scheme).has_value());

    std::array<uint8_t, 3> too_short{};
    CHECK_FALSE(cdr_unwrap_payload(too_short.data(), too_short.size()).has_value());
}
