// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Byte-exact wire compatibility tests for dds::rtps types against
// github.com/SoundMatt/go-DDS's `rtps` package — the correctness oracle
// named in cpp-DDS's ROADMAP.md ("Tier 1 — RTPS wire protocol").
//
// ── How every *_HEX constant below was derived ──────────────────────────────
//
// go-DDS's marshal* functions (marshalLocator, marshalHeader,
// marshalDataSubmessage, ...) are unexported, so they cannot be called from
// an external `go run` program. To avoid re-deriving the wire layout by
// hand (which would just test this port against itself), the vectors were
// generated by calling those *actual* functions white-box, from a scratch
// _test.go file placed temporarily inside a fresh clone of go-DDS's rtps
// package (never committed to go-DDS, never pushed anywhere):
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS
//   cat > rtps/zzz_scratch_vectors_test.go <<'EOF'
//   package rtps
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSReferenceVectors(t *testing.T) {
//       prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//       entity := EntityId{0x00, 0x00, 0x42, 0x03} // entityIdForWriter(0x000042)
//       guidBytes := append(append([]byte{}, prefix[:]...), entity[:]...)
//       fmt.Println("GUID_SAMPLE_1_HEX =", hex.EncodeToString(guidBytes))
//
//       locV4 := Locator{Kind: LocatorKindUDPv4, Port: 7412}
//       copy(locV4.Address[12:], []byte{192, 168, 1, 10})
//       fmt.Println("LOCATOR_UDPV4_SAMPLE_HEX =", hex.EncodeToString(marshalLocator(locV4)))
//
//       locV6 := Locator{Kind: LocatorKindUDPv6, Port: 7413}
//       locV6.Address = [16]byte{0xfe, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01}
//       fmt.Println("LOCATOR_UDPV6_SAMPLE_HEX =", hex.EncodeToString(marshalLocator(locV6)))
//
//       hdr := Header{ProtocolVersion: [2]byte{2, 3}, VendorId: goVendorId, GuidPrefix: prefix}
//       hdrBytes := marshalHeader(hdr)
//       fmt.Println("HEADER_SAMPLE_HEX =", hex.EncodeToString(hdrBytes))
//
//       writerEID := EntityId{0x00, 0x00, 0x42, 0x03}
//       readerEID := EntityId{0x00, 0x00, 0x00, 0x04}
//       seq := SequenceNumber{High: 0, Low: 5}
//       payload := []byte{0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01}
//       dataSubmsg := marshalDataSubmessage(writerEID, readerEID, seq, payload)
//       fmt.Println("DATA_SUBMESSAGE_SAMPLE_HEX =", hex.EncodeToString(dataSubmsg))
//
//       full := wrapInRTPSMessage(prefix, dataSubmsg)
//       fmt.Println("FULL_MESSAGE_SAMPLE_HEX =", hex.EncodeToString(full))
//   }
//   EOF
//   go test ./rtps -run TestPrintCppDDSReferenceVectors -v
//
// That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//   GUID_SAMPLE_1_HEX          = 010f996ecafebabe0000000100004203
//   ENTITY_PARTICIPANT_HEX     = 000001c1   (EntityIdParticipant,        guid.go)
//   ENTITY_SPDP_WRITER_HEX     = 000100c2   (EntityIdSPDPWriter,         guid.go)
//   ENTITY_SPDP_READER_HEX     = 000100c7   (EntityIdSPDPReader,         guid.go)
//   ENTITY_SEDP_PUB_WRITER_HEX = 000003c2   (EntityIdSEDPPubWriter,      guid.go)
//   ENTITY_SEDP_PUB_READER_HEX = 000003c7   (EntityIdSEDPPubReader,      guid.go)
//   ENTITY_SEDP_SUB_WRITER_HEX = 000004c2   (EntityIdSEDPSubWriter,      guid.go)
//   ENTITY_SEDP_SUB_READER_HEX = 000004c7   (EntityIdSEDPSubReader,      guid.go)
//   ENTITY_UNKNOWN_HEX         = 00000000   (EntityIdUnknown,            guid.go)
//   LOCATOR_UDPV4_SAMPLE_HEX   = 01000000f41c0000000000000000000000000000c0a8010a
//   LOCATOR_UDPV6_SAMPLE_HEX   = 02000000f51c0000fe800000000000000000000000000001
//   HEADER_SAMPLE_HEX          = 5254505302030127010f996ecafebabe00000001
//   DATA_SUBMESSAGE_SAMPLE_HEX = 15051a000000100000000004000042030000000005000000deadbeef0001
//   FULL_MESSAGE_SAMPLE_HEX    = 5254505302030127010f996ecafebabe0000000115051a000000100000000004000042030000000005000000deadbeef0001
//
// The well-known EntityId constants (ENTITY_* above) are read directly out
// of guid.go's var block, not marshalled (GUID/EntityId have no dedicated
// marshal function beyond raw concatenation — see GUID::encode).

#include <dds/rtps/types.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cctype>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

using namespace dds::rtps;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

// Fixed sample values shared by every test below, matching the Go
// reproduction snippet in the file header exactly.
GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}
EntityId sample_writer_entity() {
    return EntityId{{0x00, 0x00, 0x42, 0x03}};
}

} // namespace

// ── GUID ─────────────────────────────────────────────────────────────────────

TEST_CASE("GUID::encode matches go-DDS reference vector", "[rtps][guid]") {
    GUID g;
    g.prefix = sample_prefix();
    g.entity = sample_writer_entity();

    std::vector<uint8_t> out;
    g.encode(out);

    CHECK(out.size() == GUID::kSize);
    CHECK(to_hex(out) == "010f996ecafebabe0000000100004203");
}

TEST_CASE("GUID::decode round-trips the reference vector", "[rtps][guid]") {
    auto bytes = hex_to_bytes("010f996ecafebabe0000000100004203");
    auto g = GUID::decode(bytes.data(), bytes.size());
    REQUIRE(g.has_value());
    CHECK(g->prefix == sample_prefix());
    CHECK(g->entity == sample_writer_entity());

    std::vector<uint8_t> re_encoded;
    g->encode(re_encoded);
    CHECK(re_encoded == bytes);
}

TEST_CASE("GUID::decode rejects short buffers", "[rtps][guid]") {
    std::array<uint8_t, 15> too_short{};
    CHECK_FALSE(GUID::decode(too_short.data(), too_short.size()).has_value());
    CHECK_FALSE(GUID::decode(nullptr, 0).has_value());
}

TEST_CASE("Well-known EntityId constants match go-DDS guid.go", "[rtps][guid]") {
    std::vector<uint8_t> b;
    b.assign(kEntityIdParticipant.bytes.begin(), kEntityIdParticipant.bytes.end());
    CHECK(to_hex(b) == "000001c1");

    b.assign(kEntityIdSPDPWriter.bytes.begin(), kEntityIdSPDPWriter.bytes.end());
    CHECK(to_hex(b) == "000100c2");

    b.assign(kEntityIdSPDPReader.bytes.begin(), kEntityIdSPDPReader.bytes.end());
    CHECK(to_hex(b) == "000100c7");

    b.assign(kEntityIdSEDPPubWriter.bytes.begin(), kEntityIdSEDPPubWriter.bytes.end());
    CHECK(to_hex(b) == "000003c2");

    b.assign(kEntityIdSEDPPubReader.bytes.begin(), kEntityIdSEDPPubReader.bytes.end());
    CHECK(to_hex(b) == "000003c7");

    b.assign(kEntityIdSEDPSubWriter.bytes.begin(), kEntityIdSEDPSubWriter.bytes.end());
    CHECK(to_hex(b) == "000004c2");

    b.assign(kEntityIdSEDPSubReader.bytes.begin(), kEntityIdSEDPSubReader.bytes.end());
    CHECK(to_hex(b) == "000004c7");

    b.assign(kEntityIdUnknown.bytes.begin(), kEntityIdUnknown.bytes.end());
    CHECK(to_hex(b) == "00000000");
}

// ── Locator ───────────────────────────────────────────────────────────────────

TEST_CASE("Locator::encode matches go-DDS UDPv4 reference vector", "[rtps][locator]") {
    Locator l;
    l.kind = Locator::kKindUDPv4;
    l.port = 7412;
    l.address = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 168, 1, 10};

    std::vector<uint8_t> out;
    l.encode(out);

    CHECK(out.size() == Locator::kSize);
    CHECK(to_hex(out) == "01000000f41c0000000000000000000000000000c0a8010a");
}

TEST_CASE("Locator::encode matches go-DDS UDPv6 reference vector", "[rtps][locator]") {
    Locator l;
    l.kind = Locator::kKindUDPv6;
    l.port = 7413;
    l.address = {0xfe, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01};

    std::vector<uint8_t> out;
    l.encode(out);

    CHECK(to_hex(out) == "02000000f51c0000fe800000000000000000000000000001");
}

TEST_CASE("Locator::decode round-trips both reference vectors", "[rtps][locator]") {
    {
        auto bytes = hex_to_bytes("01000000f41c0000000000000000000000000000c0a8010a");
        auto l = Locator::decode(bytes.data(), bytes.size());
        REQUIRE(l.has_value());
        CHECK(l->kind == Locator::kKindUDPv4);
        CHECK(l->port == 7412);
        std::vector<uint8_t> re;
        l->encode(re);
        CHECK(re == bytes);
    }
    {
        auto bytes = hex_to_bytes("02000000f51c0000fe800000000000000000000000000001");
        auto l = Locator::decode(bytes.data(), bytes.size());
        REQUIRE(l.has_value());
        CHECK(l->kind == Locator::kKindUDPv6);
        CHECK(l->port == 7413);
        std::vector<uint8_t> re;
        l->encode(re);
        CHECK(re == bytes);
    }
}

TEST_CASE("Locator::decode rejects short buffers", "[rtps][locator]") {
    std::array<uint8_t, 23> too_short{};
    CHECK_FALSE(Locator::decode(too_short.data(), too_short.size()).has_value());
}

// ── Header ────────────────────────────────────────────────────────────────────

TEST_CASE("Header::encode matches go-DDS reference vector", "[rtps][header]") {
    Header h;
    h.protocol_version = ProtocolVersion{2, 3};
    h.vendor_id         = kVendorIdGoDDS;
    h.guid_prefix       = sample_prefix();

    std::vector<uint8_t> out;
    h.encode(out);

    CHECK(out.size() == Header::kSize);
    CHECK(to_hex(out) == "5254505302030127010f996ecafebabe00000001");
}

TEST_CASE("Header::decode round-trips the reference vector and rejects bad magic", "[rtps][header]") {
    auto bytes = hex_to_bytes("5254505302030127010f996ecafebabe00000001");
    auto h = Header::decode(bytes.data(), bytes.size());
    REQUIRE(h.has_value());
    CHECK(h->protocol_version.major == 2);
    CHECK(h->protocol_version.minor == 3);
    CHECK(h->vendor_id == kVendorIdGoDDS);
    CHECK(h->guid_prefix == sample_prefix());

    std::vector<uint8_t> re;
    h->encode(re);
    CHECK(re == bytes);

    auto corrupted = bytes;
    corrupted[0] = 'X';
    CHECK_FALSE(Header::decode(corrupted.data(), corrupted.size()).has_value());

    std::array<uint8_t, 19> too_short{};
    CHECK_FALSE(Header::decode(too_short.data(), too_short.size()).has_value());
}

// ── DATA submessage (SubmessageHeader + body) ────────────────────────────────

TEST_CASE("DataSubmessage::encode matches go-DDS reference vector", "[rtps][data]") {
    DataSubmessage ds;
    ds.writer_entity_id = sample_writer_entity();
    ds.reader_entity_id = EntityId{{0x00, 0x00, 0x00, 0x04}};
    ds.seq_num          = SequenceNumber{0, 5};
    ds.payload          = {0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01};

    std::vector<uint8_t> out;
    ds.encode(out);

    CHECK(to_hex(out) == "15051a000000100000000004000042030000000005000000deadbeef0001");
}

TEST_CASE("DataSubmessage::decode round-trips the reference vector", "[rtps][data]") {
    auto bytes = hex_to_bytes("15051a000000100000000004000042030000000005000000deadbeef0001");
    auto ds = DataSubmessage::decode(bytes.data(), bytes.size());
    REQUIRE(ds.has_value());
    CHECK(ds->writer_entity_id == sample_writer_entity());
    CHECK(ds->reader_entity_id == EntityId{{0x00, 0x00, 0x00, 0x04}});
    CHECK(ds->seq_num == SequenceNumber{0, 5});
    CHECK(ds->payload == std::vector<uint8_t>{0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01});

    std::vector<uint8_t> re;
    ds->encode(re);
    CHECK(re == bytes);
}

TEST_CASE("DataSubmessage::decode rejects malformed input", "[rtps][data]") {
    // Wrong submessage id (HEARTBEAT's 0x07 instead of DATA's 0x15).
    auto bytes = hex_to_bytes("15051a000000100000000004000042030000000005000000deadbeef0001");
    auto wrong_id = bytes;
    wrong_id[0] = kSubmessageIdHeartbeat;
    CHECK_FALSE(DataSubmessage::decode(wrong_id.data(), wrong_id.size()).has_value());

    // Declared length overruns the actual buffer.
    auto truncated = bytes;
    truncated.resize(bytes.size() - 4);
    CHECK_FALSE(DataSubmessage::decode(truncated.data(), truncated.size()).has_value());

    // Body shorter than the fixed 20-byte prefix.
    std::vector<uint8_t> short_body = {0x15, 0x05, 0x04, 0x00, 0xAA, 0xBB, 0xCC, 0xDD};
    CHECK_FALSE(DataSubmessage::decode(short_body.data(), short_body.size()).has_value());
}

// ── Full RTPS message: Header + DATA submessage back to back ────────────────

TEST_CASE("Header + DataSubmessage concatenation matches go-DDS wrapInRTPSMessage vector",
          "[rtps][message]") {
    Header h;
    h.protocol_version = ProtocolVersion{2, 3};
    h.vendor_id         = kVendorIdGoDDS;
    h.guid_prefix       = sample_prefix();

    DataSubmessage ds;
    ds.writer_entity_id = sample_writer_entity();
    ds.reader_entity_id = EntityId{{0x00, 0x00, 0x00, 0x04}};
    ds.seq_num          = SequenceNumber{0, 5};
    ds.payload          = {0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01};

    std::vector<uint8_t> out;
    h.encode(out);
    ds.encode(out);

    CHECK(to_hex(out) ==
          "5254505302030127010f996ecafebabe0000000115051a000000100000000004000042030000000005000000deadbeef0001");
}

// ── SubmessageHeader / SequenceNumber (unit-level, exercised in situ above) ──

TEST_CASE("SubmessageHeader::encode/decode round-trip", "[rtps][submessage_header]") {
    SubmessageHeader h{kSubmessageIdData, kFlagEndianness | kFlagData, 0x001a};
    std::vector<uint8_t> out;
    h.encode(out);
    CHECK(to_hex(out) == "15051a00");

    auto decoded = SubmessageHeader::decode(out.data(), out.size());
    REQUIRE(decoded.has_value());
    CHECK(*decoded == h);
}

TEST_CASE("SequenceNumber::encode/decode round-trip, including negative high", "[rtps][seqnum]") {
    SequenceNumber sn{0, 5};
    std::vector<uint8_t> out;
    sn.encode(out);
    CHECK(to_hex(out) == "0000000005000000");

    auto decoded = SequenceNumber::decode(out.data(), out.size());
    REQUIRE(decoded.has_value());
    CHECK(*decoded == sn);

    // Negative High exercises the two's-complement bit-reinterpretation path.
    SequenceNumber neg{-1, 0xFFFFFFFFu};
    std::vector<uint8_t> neg_out;
    neg.encode(neg_out);
    CHECK(to_hex(neg_out) == "ffffffffffffffff");
    auto neg_decoded = SequenceNumber::decode(neg_out.data(), neg_out.size());
    REQUIRE(neg_decoded.has_value());
    CHECK(neg_decoded->high == -1);
    CHECK(neg_decoded->low == 0xFFFFFFFFu);
}
