// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Byte-exact wire compatibility tests for dds::rtps SEDP (build/parse
// EndpointData, full announcement message framing) against
// github.com/SoundMatt/go-DDS's `rtps` package (rtps/sedp.go) — the
// correctness oracle named in cpp-DDS's ROADMAP.md ("Tier 1 — RTPS wire
// protocol", phase 5: "SEDP") — plus behavioral tests of endpoint
// registration, remote-endpoint tables, and topic matching (SedpService).
//
// ── How every *_HEX constant below was derived ──────────────────────────────
//
// sedpService.buildEndpointData and the marshalDataSubmessage/
// wrapInRTPSMessage helpers it composes with are all unexported (or
// package-private), and buildEndpointData is itself a method on
// sedpService which needs a *participant. As with phases 1–4, the vectors
// were generated by calling those *actual* functions white-box, from a
// scratch _test.go file placed temporarily inside a fresh clone of
// go-DDS's rtps package (never committed to go-DDS, never pushed
// anywhere), constructing only the participant fields buildEndpointData
// actually reads (dataSock.port — discoveryPlugin left nil, matching this
// phase's scope):
//
//   git clone https://github.com/SoundMatt/go-DDS.git
//   cd go-DDS
//   cat > rtps/zzz_scratch_sedp_vectors_test.go <<'EOF'
//   package rtps
//
//   import (
//       "encoding/hex"
//       "fmt"
//       "testing"
//   )
//
//   func TestPrintCppDDSSEDPReferenceVectors(t *testing.T) {
//       prefix := GuidPrefix{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}
//       p := &participant{guidPrefix: prefix, dataSock: &udpSocket{port: 7411}}
//       s := newSEDPService(p)
//
//       writerGUID := GUID{Prefix: prefix, Entity: EntityId{0x00, 0x00, 0x01, 0x02}}
//       writerInfo := &endpointInfo{guid: writerGUID, topicName: "SomeTopic", isWriter: true}
//       writerPayload := s.buildEndpointData(writerInfo)
//       fmt.Println("SEDP_WRITER_ENDPOINT_DATA_HEX =", hex.EncodeToString(writerPayload))
//
//       writerSubmsg := marshalDataSubmessage(EntityIdSEDPPubWriter, EntityIdSEDPPubReader,
//           SequenceNumber{High: 0, Low: 1}, writerPayload)
//       writerMsg := wrapInRTPSMessage(p.guidPrefix, writerSubmsg)
//       fmt.Println("SEDP_WRITER_ANNOUNCEMENT_MSG_HEX =", hex.EncodeToString(writerMsg))
//
//       readerGUID := GUID{Prefix: prefix, Entity: EntityId{0x00, 0x00, 0x02, 0x07}}
//       readerInfo := &endpointInfo{guid: readerGUID, topicName: "OtherTopic", isWriter: false}
//       readerPayload := s.buildEndpointData(readerInfo)
//       fmt.Println("SEDP_READER_ENDPOINT_DATA_HEX =", hex.EncodeToString(readerPayload))
//
//       readerSubmsg := marshalDataSubmessage(EntityIdSEDPSubWriter, EntityIdSEDPSubReader,
//           SequenceNumber{High: 0, Low: 7}, readerPayload)
//       readerMsg := wrapInRTPSMessage(p.guidPrefix, readerSubmsg)
//       fmt.Println("SEDP_READER_ANNOUNCEMENT_MSG_HEX =", hex.EncodeToString(readerMsg))
//
//       prefix2 := GuidPrefix{0xAA, 0xBB, 0xCC, 0xDD, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}
//       p2 := &participant{guidPrefix: prefix2, dataSock: &udpSocket{port: 7661}}
//       s2 := newSEDPService(p2)
//
//       writerGUID2 := GUID{Prefix: prefix2, Entity: EntityId{0x00, 0x00, 0x05, 0x02}}
//       writerInfo2 := &endpointInfo{guid: writerGUID2, topicName: "Chatter", isWriter: true}
//       writerPayload2 := s2.buildEndpointData(writerInfo2)
//       fmt.Println("SEDP_WRITER_ENDPOINT_DATA2_HEX =", hex.EncodeToString(writerPayload2))
//
//       writerSubmsg2 := marshalDataSubmessage(EntityIdSEDPPubWriter, EntityIdSEDPPubReader,
//           SequenceNumber{High: 0, Low: 42}, writerPayload2)
//       writerMsg2 := wrapInRTPSMessage(p2.guidPrefix, writerSubmsg2)
//       fmt.Println("SEDP_WRITER_ANNOUNCEMENT_MSG2_HEX =", hex.EncodeToString(writerMsg2))
//   }
//   EOF
//   go test ./rtps -run TestPrintCppDDSSEDPReferenceVectors -v
//
// That produced (go-DDS main @ time of writing, module github.com/SoundMatt/go-DDS):
//
//   SEDP_WRITER_ENDPOINT_DATA_HEX = 030000005a001000010f996ecafebabe0000000100000102050010000a000000536f6d65546f70696300000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000000000000000000000000000000001000000
//   SEDP_WRITER_ANNOUNCEMENT_MSG_HEX = 5254505302030127010f996ecafebabe000000011505740000001000000003c7000003c20000000001000000030000005a001000010f996ecafebabe0000000100000102050010000a000000536f6d65546f70696300000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000000000000000000000000000000001000000
//   SEDP_READER_ENDPOINT_DATA_HEX = 030000005a001000010f996ecafebabe0000000100000207050010000b0000004f74686572546f706963000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000000000000000000000000000000001000000
//   SEDP_READER_ANNOUNCEMENT_MSG_HEX = 5254505302030127010f996ecafebabe000000011505740000001000000004c7000004c20000000007000000030000005a001000010f996ecafebabe0000000100000207050010000b0000004f74686572546f706963000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000000000000000000000000000000001000000
//   SEDP_WRITER_ENDPOINT_DATA2_HEX = 030000005a001000aabbccdd01020304050607080000050205000c0008000000436861747465720007001000090000004344525f424c4f42000000002f00180001000000ed1d00000000000000000000000000000000000001000000
//   SEDP_WRITER_ANNOUNCEMENT_MSG2_HEX = 5254505302030127aabbccdd01020304050607081505700000001000000003c7000003c2000000002a000000030000005a001000aabbccdd01020304050607080000050205000c0008000000436861747465720007001000090000004344525f424c4f42000000002f00180001000000ed1d00000000000000000000000000000000000001000000
//
// The scratch file was deleted immediately after and never committed —
// `git status` in the go-DDS clone was confirmed clean afterward.
//
// The SedpService registration/matching/eviction tests below are ordinary
// behavioral tests (go-DDS has no dedicated unit test isolating just the
// remote-endpoint-table logic either — it's exercised indirectly through
// full participant integration tests, which is a later Tier-1 phase here),
// not wire-format conformance vectors.

#include <algorithm>
#include <chrono>
#include <cctype>
#include <string>
#include <thread>
#include <vector>

#include <catch2/catch_test_macros.hpp>

#include <dds/rtps/sedp.hpp>

using namespace dds::rtps;
using namespace std::chrono_literals;

namespace {

std::vector<uint8_t> hex_to_bytes(std::string_view hex) {
    std::vector<uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        return static_cast<uint8_t>(std::tolower(static_cast<unsigned char>(c)) - 'a' + 10);
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return out;
}

std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char* digits = "0123456789abcdef";
    std::string        s;
    s.reserve(bytes.size() * 2);
    for (uint8_t b : bytes) {
        s.push_back(digits[b >> 4]);
        s.push_back(digits[b & 0x0F]);
    }
    return s;
}

GuidPrefix sample_prefix() {
    return GuidPrefix{{0x01, 0x0f, 0x99, 0x6e, 0xca, 0xfe, 0xba, 0xbe, 0x00, 0x00, 0x00, 0x01}};
}

GuidPrefix sample_prefix2() {
    return GuidPrefix{{0xAA, 0xBB, 0xCC, 0xDD, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}};
}

EndpointInfo sample_writer_info() {
    EndpointInfo info;
    info.guid       = GUID{sample_prefix(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    info.topic_name = "SomeTopic";
    info.is_writer  = true;
    return info;
}

EndpointInfo sample_reader_info() {
    EndpointInfo info;
    info.guid       = GUID{sample_prefix(), EntityId{{0x00, 0x00, 0x02, 0x07}}};
    info.topic_name = "OtherTopic";
    info.is_writer  = false;
    return info;
}

} // namespace

// ── build_endpoint_data ──────────────────────────────────────────────────────

TEST_CASE("build_endpoint_data matches go-DDS reference vector for a writer", "[rtps][sedp]") {
    CHECK(to_hex(build_endpoint_data(sample_writer_info(), 7411)) ==
          "030000005a001000010f996ecafebabe0000000100000102050010000a000000536f6d65546f70"
          "696300000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000"
          "000000000000000000000000000001000000");
}

TEST_CASE("build_endpoint_data matches go-DDS reference vector for a reader", "[rtps][sedp]") {
    CHECK(to_hex(build_endpoint_data(sample_reader_info(), 7411)) ==
          "030000005a001000010f996ecafebabe0000000100000207050010000b0000004f74686572546f"
          "706963000007001000090000004344525f424c4f42000000002f00180001000000f31c00000000"
          "000000000000000000000000000001000000");
}

TEST_CASE("build_endpoint_data matches go-DDS reference vector for a second sample",
          "[rtps][sedp]") {
    EndpointInfo info;
    info.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x05, 0x02}}};
    info.topic_name = "Chatter";
    info.is_writer  = true;

    CHECK(to_hex(build_endpoint_data(info, 7661)) ==
          "030000005a001000aabbccdd01020304050607080000050205000c0008000000436861747465720"
          "007001000090000004344525f424c4f42000000002f00180001000000ed1d0000000000000000"
          "0000000000000000000001000000");
}

// ── build_sedp_announcement ───────────────────────────────────────────────────

TEST_CASE("build_sedp_announcement matches go-DDS reference vector for a writer announcement",
          "[rtps][sedp]") {
    auto payload = build_endpoint_data(sample_writer_info(), 7411);
    auto msg     = build_sedp_announcement(sample_prefix(), kVendorIdGoDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 1}, payload);
    CHECK(to_hex(msg) ==
          "5254505302030127010f996ecafebabe000000011505740000001000000003c7000003c2000000"
          "0001000000030000005a001000010f996ecafebabe0000000100000102050010000a000000536f"
          "6d65546f70696300000007001000090000004344525f424c4f42000000002f00180001000000f3"
          "1c00000000000000000000000000000000000001000000");
}

TEST_CASE("build_sedp_announcement matches go-DDS reference vector for a reader announcement",
          "[rtps][sedp]") {
    auto payload = build_endpoint_data(sample_reader_info(), 7411);
    auto msg     = build_sedp_announcement(sample_prefix(), kVendorIdGoDDS, kEntityIdSEDPSubWriter,
                                        kEntityIdSEDPSubReader, SequenceNumber{0, 7}, payload);
    CHECK(to_hex(msg) ==
          "5254505302030127010f996ecafebabe000000011505740000001000000004c7000004c2000000"
          "0007000000030000005a001000010f996ecafebabe0000000100000207050010000b0000004f74"
          "686572546f706963000007001000090000004344525f424c4f42000000002f00180001000000f3"
          "1c00000000000000000000000000000000000001000000");
}

TEST_CASE("build_sedp_announcement matches go-DDS reference vector for a second sample",
          "[rtps][sedp]") {
    EndpointInfo info;
    info.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x05, 0x02}}};
    info.topic_name = "Chatter";
    info.is_writer  = true;
    auto payload    = build_endpoint_data(info, 7661);

    auto msg = build_sedp_announcement(sample_prefix2(), kVendorIdGoDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 42}, payload);
    CHECK(to_hex(msg) ==
          "5254505302030127aabbccdd01020304050607081505700000001000000003c7000003c2000000"
          "002a000000030000005a001000aabbccdd01020304050607080000050205000c00080000004368"
          "61747465720007001000090000004344525f424c4f42000000002f00180001000000ed1d000000"
          "00000000000000000000000000000001000000");
}

// ── parse_endpoint_data ───────────────────────────────────────────────────────

TEST_CASE("parse_endpoint_data round-trips build_endpoint_data's output "
          "and fills in the from-address for a 0.0.0.0 locator",
          "[rtps][sedp]") {
    auto payload = build_endpoint_data(sample_writer_info(), 7411);

    auto info = parse_endpoint_data(sample_prefix(), payload.data(), payload.size(), "192.168.1.50");
    REQUIRE(info.has_value());

    CHECK(info->guid == sample_writer_info().guid);
    CHECK(info->topic_name == "SomeTopic");
    CHECK(info->data_locator.kind == Locator::kKindUDPv4);
    CHECK(info->data_locator.port == 7411);
    CHECK(info->data_locator.address ==
          std::array<uint8_t, 16>{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 168, 1, 50});
}

TEST_CASE("parse_endpoint_data rejects an invalid PL_CDR_LE header", "[rtps][sedp]") {
    auto bad = hex_to_bytes("01000000deadbeef"); // CDR_LE scheme, not PL_CDR_LE
    CHECK_FALSE(
        parse_endpoint_data(sample_prefix(), bad.data(), bad.size(), "127.0.0.1").has_value());
}

TEST_CASE("parse_endpoint_data returns nullopt when no topic name parameter is present",
          "[rtps][sedp]") {
    PLCDREncoder enc;
    GUID         g{sample_prefix(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    enc.add_guid(kPidEndpointGUID, g);
    auto payload = enc.finish();

    CHECK_FALSE(
        parse_endpoint_data(sample_prefix(), payload.data(), payload.size(), "127.0.0.1")
            .has_value());
}

// ── SedpService: registration, matching, eviction (behavioral) ──────────────

namespace {

std::optional<SedpService> make_service(SedpConfig config) {
    auto sock = UdpSocket::bind_unicast(0);
    if (!sock) return std::nullopt;
    return std::optional<SedpService>(std::in_place, std::move(config), std::move(*sock));
}

ParticipantProxy make_proxy(const GuidPrefix& prefix, const std::string& addr, int port) {
    ParticipantProxy proxy;
    proxy.guid.prefix          = prefix;
    proxy.guid.entity          = kEntityIdParticipant;
    proxy.metatraffic_unicast.kind = Locator::kKindUDPv4;
    proxy.metatraffic_unicast.port = static_cast<uint32_t>(port);
    // Encode "127.0.0.1" (or whatever addr) into the trailing 4 bytes;
    // tests only ever use loopback here, so hardcode the common case.
    (void)addr;
    proxy.metatraffic_unicast.address = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 0, 0, 1};
    return proxy;
}

} // namespace

TEST_CASE("SedpService::handle_packet ignores its own announcements", "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    auto payload = build_endpoint_data(sample_writer_info(), 7411);
    auto msg     = build_sedp_announcement(cfg.local_guid_prefix, kVendorIdCppDDS,
                                        kEntityIdSEDPPubWriter, kEntityIdSEDPPubReader,
                                        SequenceNumber{0, 1}, payload);
    svc->handle_packet(msg, "127.0.0.1");
    CHECK(svc->announces_received() == 0);
    CHECK(svc->matched_writer_guids_for_reader(EntityId{{0, 0, 2, 7}}).empty());
}

TEST_CASE("SedpService::handle_packet stores a remote writer and matches an existing local reader",
          "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    EntityId reader_eid{{0x00, 0x00, 0x02, 0x07}};
    svc->register_reader(reader_eid, "SomeTopic");

    EndpointInfo remote_writer;
    remote_writer.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    remote_writer.topic_name = "SomeTopic";
    remote_writer.is_writer  = true;
    auto payload = build_endpoint_data(remote_writer, 9001);
    auto msg     = build_sedp_announcement(sample_prefix2(), kVendorIdCppDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 1}, payload);

    svc->handle_packet(msg, "10.0.0.5");

    CHECK(svc->announces_received() == 1);
    CHECK(svc->endpoint_matches() == 1);
    auto matched = svc->matched_writer_guids_for_reader(reader_eid);
    REQUIRE(matched.size() == 1);
    CHECK(matched[0] == remote_writer.guid);
    auto loc = svc->writer_locator(remote_writer.guid);
    REQUIRE(loc.has_value());
    CHECK(loc->port == 9001);
}

TEST_CASE("SedpService::register_reader matches an already-discovered remote writer",
          "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    // Discover the remote writer first (no local reader registered yet, so
    // no match happens on receipt).
    EndpointInfo remote_writer;
    remote_writer.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    remote_writer.topic_name = "SomeTopic";
    remote_writer.is_writer  = true;
    auto payload = build_endpoint_data(remote_writer, 9001);
    auto msg     = build_sedp_announcement(sample_prefix2(), kVendorIdCppDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 1}, payload);
    svc->handle_packet(msg, "10.0.0.5");
    CHECK(svc->endpoint_matches() == 0);

    // Now register a local reader for the same topic: it should pick up
    // the already-known remote writer immediately.
    EntityId reader_eid{{0x00, 0x00, 0x02, 0x07}};
    svc->register_reader(reader_eid, "SomeTopic");

    auto matched = svc->matched_writer_guids_for_reader(reader_eid);
    REQUIRE(matched.size() == 1);
    CHECK(matched[0] == remote_writer.guid);
}

TEST_CASE("SedpService::handle_packet ignores a non-matching topic", "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    EntityId reader_eid{{0x00, 0x00, 0x02, 0x07}};
    svc->register_reader(reader_eid, "SomeTopic");

    EndpointInfo remote_writer;
    remote_writer.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    remote_writer.topic_name = "UnrelatedTopic";
    remote_writer.is_writer  = true;
    auto payload = build_endpoint_data(remote_writer, 9001);
    auto msg     = build_sedp_announcement(sample_prefix2(), kVendorIdCppDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 1}, payload);
    svc->handle_packet(msg, "10.0.0.5");

    CHECK(svc->announces_received() == 1);
    CHECK(svc->endpoint_matches() == 0);
    CHECK(svc->matched_writer_guids_for_reader(reader_eid).empty());
}

TEST_CASE("SedpService::handle_packet records a remote subscription reader locator",
          "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    EndpointInfo remote_reader;
    remote_reader.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x02, 0x07}}};
    remote_reader.topic_name = "SomeTopic";
    remote_reader.is_writer  = false;
    auto payload = build_endpoint_data(remote_reader, 9002);
    auto msg     = build_sedp_announcement(sample_prefix2(), kVendorIdCppDDS, kEntityIdSEDPSubWriter,
                                        kEntityIdSEDPSubReader, SequenceNumber{0, 1}, payload);
    svc->handle_packet(msg, "10.0.0.5");

    auto loc = svc->reader_locator(remote_reader.guid);
    REQUIRE(loc.has_value());
    CHECK(loc->port == 9002);
}

TEST_CASE("SedpService::on_peer_evicted purges remote endpoints from the evicted prefix",
          "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    EntityId reader_eid{{0x00, 0x00, 0x02, 0x07}};
    svc->register_reader(reader_eid, "SomeTopic");

    EndpointInfo remote_writer;
    remote_writer.guid       = GUID{sample_prefix2(), EntityId{{0x00, 0x00, 0x01, 0x02}}};
    remote_writer.topic_name = "SomeTopic";
    remote_writer.is_writer  = true;
    auto payload = build_endpoint_data(remote_writer, 9001);
    auto msg     = build_sedp_announcement(sample_prefix2(), kVendorIdCppDDS, kEntityIdSEDPPubWriter,
                                        kEntityIdSEDPPubReader, SequenceNumber{0, 1}, payload);
    svc->handle_packet(msg, "10.0.0.5");
    REQUIRE(svc->writer_locator(remote_writer.guid).has_value());

    svc->on_peer_evicted(sample_prefix2());
    CHECK_FALSE(svc->writer_locator(remote_writer.guid).has_value());
}

TEST_CASE("SedpService::register_writer/register_reader announce to a peer added via on_new_peer",
          "[rtps][sedp]") {
    auto local_sock = UdpSocket::bind_unicast(0);
    auto peer_sock  = UdpSocket::bind_unicast(0);
    REQUIRE(local_sock.has_value());
    REQUIRE(peer_sock.has_value());

    SedpConfig cfg;
    cfg.local_guid_prefix   = sample_prefix();
    cfg.data_unicast_port    = 7411;
    SedpService svc(cfg, std::move(*local_sock));

    ParticipantProxy peer = make_proxy(sample_prefix2(), "127.0.0.1", peer_sock->port());
    svc.on_new_peer(peer); // no local endpoints registered yet, so no send happens

    svc.register_writer(EntityId{{0x00, 0x00, 0x01, 0x02}}, "SomeTopic");
    CHECK(svc.announces_sent() == 1);

    auto pkt = peer_sock->recv();
    REQUIRE(pkt.has_value());
    auto hdr = Header::decode(pkt->data.data(), pkt->data.size());
    REQUIRE(hdr.has_value());
    CHECK(hdr->guid_prefix == sample_prefix());
}

TEST_CASE("SedpService::start/stop is idempotent and safe to call repeatedly", "[rtps][sedp]") {
    SedpConfig cfg;
    cfg.local_guid_prefix = sample_prefix();
    auto svc = make_service(cfg);
    REQUIRE(svc.has_value());

    svc->start();
    svc->start(); // no-op: already running
    std::this_thread::sleep_for(20ms);
    svc->stop();
    svc->stop(); // no-op: already stopped
}

TEST_CASE("Two SedpService instances converge a reader<->writer match over unicast",
          "[rtps][sedp]") {
    auto a_sock = UdpSocket::bind_unicast(0);
    auto b_sock = UdpSocket::bind_unicast(0);
    REQUIRE(a_sock.has_value());
    REQUIRE(b_sock.has_value());

    const int a_port = a_sock->port();
    const int b_port = b_sock->port();

    SedpConfig cfg_a;
    cfg_a.local_guid_prefix = sample_prefix();
    cfg_a.data_unicast_port  = 9411;
    SedpService svc_a(cfg_a, std::move(*a_sock));

    SedpConfig cfg_b;
    cfg_b.local_guid_prefix = sample_prefix2();
    cfg_b.data_unicast_port  = 9412;
    SedpService svc_b(cfg_b, std::move(*b_sock));

    svc_a.start();
    svc_b.start();

    // A has a reader for "SomeTopic"; B has a writer for "SomeTopic".
    EntityId reader_eid{{0x00, 0x00, 0x02, 0x07}};
    EntityId writer_eid{{0x00, 0x00, 0x01, 0x02}};
    svc_a.register_reader(reader_eid, "SomeTopic");
    svc_b.register_writer(writer_eid, "SomeTopic");

    // Each learns about the other as a peer and re-announces directly to it.
    svc_a.on_new_peer(make_proxy(sample_prefix2(), "127.0.0.1", b_port));
    svc_b.on_new_peer(make_proxy(sample_prefix(), "127.0.0.1", a_port));

    GUID expected_writer_guid{sample_prefix2(), writer_eid};
    bool matched = false;
    for (int attempt = 0; attempt < 60 && !matched; ++attempt) {
        std::this_thread::sleep_for(50ms);
        auto guids = svc_a.matched_writer_guids_for_reader(reader_eid);
        matched    = std::find(guids.begin(), guids.end(), expected_writer_guid) != guids.end();
    }

    svc_a.stop();
    svc_b.stop();

    REQUIRE(matched);
    auto loc = svc_a.writer_locator(expected_writer_guid);
    REQUIRE(loc.has_value());
    CHECK(loc->port == 9412);
}
