// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// dds/cdr/cdr.hpp — General-purpose CDR/XCDR1 (Common Data Representation)
// encoding and decoding as specified by the OMG DDS-XTypes 1.3 standard,
// for arbitrary IDL-defined user payload types.
//
// C++ port of github.com/SoundMatt/go-DDS's top-level `cdr` package
// (tools/cdr/cdr.go, 348 LOC incl. tests). See ROADMAP.md, "Tier 3 — xtypes,
// tsn, idl, cdr", `cdr`.
//
// This is deliberately a SEPARATE library from Tier 1 phase 2's
// discovery-scoped PL_CDR encoder (dds/rtps/cdr.hpp / src/rtps/cdr.cpp),
// which handles only little-endian parameter-list encoding for SPDP/SEDP
// discovery submessages. go-DDS keeps these as two separate packages
// (`rtps/cdr.go` vs. top-level `tools/cdr/`) and cpp-DDS mirrors that split
// with this new `dds/cdr/` — do not reuse or extend `dds::rtps::cdr` for
// general payload-type work, and do not reuse or extend this library for
// discovery submessages.
//
// # Alignment
//
// Each primitive type is aligned to its own size (bool/int8/uint8: 1,
// int16/uint16: 2, int32/uint32/float32: 4, int64/uint64/float64: 8).
// Strings are encoded as a 4-byte length prefix (including null
// terminator) followed by the UTF-8 bytes and a null byte. Byte sequences
// use a 4-byte count prefix with no null terminator.
//
// # Encapsulation header
//
// Encoder prepends the 4-byte CDR_LE encapsulation header
// ({0x01,0x00,0x00,0x00} — scheme 0x0001 written little-endian) to every
// buffer it produces; Decoder::create() validates and consumes it. Both the
// CDR_LE (0x0001) and CDR_BE (0x0000) scheme values are accepted on decode
// (matching go-DDS's own NewDecoder exactly), but the payload is always
// decoded little-endian regardless of which of the two schemes was present
// — go-DDS never emits CDR_BE itself, and this quirk is preserved here only
// for decode-side behavioral parity with the go-DDS oracle, not because
// CDR_BE payloads are actually supported.
//
// # Usage
//
//   dds::cdr::Encoder e;
//   e.write_string("hello");
//   e.write_int32(42);
//   auto data = e.bytes();
//
//   auto d = dds::cdr::Decoder::create(data);
//   auto s = d->read_string();
//   auto n = d->read_int32();
//
// Every Encoder write_*()/Decoder read_*() method here MUST produce/consume
// byte-identical output to the corresponding go-DDS function; see
// tests/test_cdr.cpp for the reference vectors (generated by calling
// go-DDS's actual exported Encoder/Decoder methods from a scratch _test.go
// file placed temporarily inside a fresh go-DDS clone — never committed to
// go-DDS, never pushed anywhere).
//
// Unlike go-DDS's (value, error) return convention, decode failures here
// are reported as std::nullopt (no descriptive error string), matching this
// repo's own dds::rtps::PLCDRDecoder precedent (also a `cdr`-flavored,
// std::optional-returning decoder) rather than dds::xtypes's
// std::error_code convention — go-DDS's own cdr package exports no
// sentinel errors for callers to compare against (just ad hoc
// fmt.Errorf strings), so there is no distinguishable error identity to
// preserve across the port.

#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace dds::cdr {

// ── Encoder ───────────────────────────────────────────────────────────────────

// Encoder writes CDR/XCDR1 little-endian bytes to an internal buffer.
// Call bytes() to retrieve the complete encoded message including the
// 4-byte encapsulation header (go-DDS: cdr.Encoder).
// fusa:req REQ-CDR-001 REQ-CDR-002 REQ-CDR-004
class Encoder {
public:
    // Constructs an Encoder pre-seeded with the CDR_LE encapsulation header
    // (go-DDS: cdr.NewEncoder()).
    Encoder();

    // bytes returns the complete encoded buffer including the encapsulation
    // header.
    const std::vector<uint8_t>& bytes() const noexcept { return buf_; }

    // len returns the current encoded length in bytes.
    std::size_t len() const noexcept { return buf_.size(); }

    // ── Primitive writes ─────────────────────────────────────────────────

    // write_bool encodes a boolean (1 byte: 0 or 1).
    void write_bool(bool v);
    // write_uint8 encodes an unsigned byte.
    void write_uint8(uint8_t v);
    // write_int8 encodes a signed byte.
    void write_int8(int8_t v);
    // write_int16 encodes a signed 16-bit integer (2-byte aligned).
    void write_int16(int16_t v);
    // write_uint16 encodes an unsigned 16-bit integer (2-byte aligned).
    void write_uint16(uint16_t v);
    // write_int32 encodes a signed 32-bit integer (4-byte aligned).
    void write_int32(int32_t v);
    // write_uint32 encodes an unsigned 32-bit integer (4-byte aligned).
    void write_uint32(uint32_t v);
    // write_int64 encodes a signed 64-bit integer (8-byte aligned).
    void write_int64(int64_t v);
    // write_uint64 encodes an unsigned 64-bit integer (8-byte aligned).
    void write_uint64(uint64_t v);
    // write_float32 encodes a 32-bit IEEE 754 float (4-byte aligned).
    void write_float32(float v);
    // write_float64 encodes a 64-bit IEEE 754 float (8-byte aligned).
    void write_float64(double v);

    // write_string encodes a CDR string: uint32 length (including null
    // terminator), UTF-8 bytes, null byte. The length field is 4-byte
    // aligned.
    void write_string(const std::string& s);

    // write_bytes encodes a byte sequence: uint32 count + raw bytes (no
    // null terminator). The count field is 4-byte aligned.
    void write_bytes(const std::vector<uint8_t>& b);

private:
    void align(std::size_t n);

    std::vector<uint8_t> buf_;
};

// ── Decoder ───────────────────────────────────────────────────────────────────

// Decoder reads CDR/XCDR1 little-endian bytes from a buffer. The buffer
// must begin with the 4-byte CDR_LE (or CDR_BE, accepted but still decoded
// little-endian) encapsulation header (go-DDS: cdr.Decoder). Decoder does
// not own the bytes it reads: the buffer passed to create() must outlive
// the Decoder.
// fusa:req REQ-CDR-001 REQ-CDR-003 REQ-CDR-004
class Decoder {
public:
    // create validates the 4-byte encapsulation header and returns a
    // Decoder positioned just past it. Returns std::nullopt if data is
    // shorter than 4 bytes or the scheme field is neither 0x0001 (CDR_LE)
    // nor 0x0000 (CDR_BE) (go-DDS: cdr.NewDecoder()).
    static std::optional<Decoder> create(const uint8_t* data, std::size_t len);
    static std::optional<Decoder> create(const std::vector<uint8_t>& data);

    // remaining returns the number of undecoded bytes.
    std::size_t remaining() const noexcept { return len_ - pos_; }

    // ── Primitive reads ──────────────────────────────────────────────────

    // read_bool decodes a boolean byte.
    std::optional<bool> read_bool();
    // read_uint8 decodes an unsigned byte.
    std::optional<uint8_t> read_uint8();
    // read_int8 decodes a signed byte.
    std::optional<int8_t> read_int8();
    // read_int16 decodes a signed 16-bit integer.
    std::optional<int16_t> read_int16();
    // read_uint16 decodes an unsigned 16-bit integer.
    std::optional<uint16_t> read_uint16();
    // read_int32 decodes a signed 32-bit integer.
    std::optional<int32_t> read_int32();
    // read_uint32 decodes an unsigned 32-bit integer.
    std::optional<uint32_t> read_uint32();
    // read_int64 decodes a signed 64-bit integer.
    std::optional<int64_t> read_int64();
    // read_uint64 decodes an unsigned 64-bit integer.
    std::optional<uint64_t> read_uint64();
    // read_float32 decodes a 32-bit IEEE 754 float.
    std::optional<float> read_float32();
    // read_float64 decodes a 64-bit IEEE 754 float.
    std::optional<double> read_float64();

    // read_string decodes a CDR string (uint32 length + bytes + null
    // terminator); the trailing null is stripped from the returned string.
    std::optional<std::string> read_string();

    // read_bytes decodes a byte sequence (uint32 count + bytes, no null
    // terminator).
    std::optional<std::vector<uint8_t>> read_bytes();

private:
    Decoder(const uint8_t* data, std::size_t len, std::size_t pos) noexcept
        : data_(data), len_(len), pos_(pos) {}

    void align(std::size_t n) noexcept;
    bool need(std::size_t n) const noexcept;

    const uint8_t* data_{nullptr};
    std::size_t    len_{0};
    std::size_t    pos_{0};
};

} // namespace dds::cdr
