// Code generated by cpp-DDS ddstool (IDL compiler). DO NOT EDIT.

#pragma once

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "dds/cdr/cdr.hpp"

namespace idlgen {

// TopicID is a type alias generated from IDL typedef TopicID.
using TopicID = uint32_t;

// Priority is generated from IDL enum Priority.
enum class Priority : int32_t {
    LOW = 0,
    MEDIUM = 1,
    HIGH = 2,
    CRITICAL = 3,
};

// Header is generated from IDL struct Header.
struct Header {
    std::string topic_id{};
    int64_t timestamp_ns{};
    Priority priority{};
};

// HeaderCodec encodes/decodes Header using CDR/XCDR1 (dds::cdr).
struct HeaderCodec {
    static std::vector<uint8_t> marshal(const Header& v) {
        dds::cdr::Encoder e;
        e.write_string(v.topic_id);
        e.write_int64(v.timestamp_ns);
        e.write_int32(static_cast<int32_t>(v.priority));
        return e.bytes();
    }

    static std::optional<Header> unmarshal(const std::vector<uint8_t>& data) {
        auto d = dds::cdr::Decoder::create(data);
        if (!d) { return std::nullopt; }
        Header v;
        auto _f0 = d->read_string();
        if (!_f0) { return std::nullopt; }
        v.topic_id = *_f0;
        auto _f1 = d->read_int64();
        if (!_f1) { return std::nullopt; }
        v.timestamp_ns = *_f1;
        auto _ev2 = d->read_int32();
        if (!_ev2) { return std::nullopt; }
        v.priority = static_cast<Priority>(*_ev2);
        return v;
    }

    // key_fields returns the field names marked @key in the IDL source.
    static std::vector<std::string> key_fields() {
        return { "topic_id" };
    }
};

// Telemetry is generated from IDL struct Telemetry.
struct Telemetry {
    Header header{};
    std::array<double, 4> values{};
    float temperature{};
    bool valid{};
    std::vector<double> extras{};
};

// TelemetryCodec encodes/decodes Telemetry using CDR/XCDR1 (dds::cdr).
struct TelemetryCodec {
    static std::vector<uint8_t> marshal(const Telemetry& v) {
        dds::cdr::Encoder e;
        e.write_string(v.header.topic_id);
        e.write_int64(v.header.timestamp_ns);
        e.write_int32(static_cast<int32_t>(v.header.priority));
        for (const auto& _elem3 : v.values) {
            e.write_float64(_elem3);
        }
        e.write_float32(v.temperature);
        e.write_bool(v.valid);
        e.write_uint32(static_cast<uint32_t>(v.extras.size()));
        for (const auto& _elem4 : v.extras) {
            e.write_float64(_elem4);
        }
        return e.bytes();
    }

    static std::optional<Telemetry> unmarshal(const std::vector<uint8_t>& data) {
        auto d = dds::cdr::Decoder::create(data);
        if (!d) { return std::nullopt; }
        Telemetry v;
        auto _f5 = d->read_string();
        if (!_f5) { return std::nullopt; }
        v.header.topic_id = *_f5;
        auto _f6 = d->read_int64();
        if (!_f6) { return std::nullopt; }
        v.header.timestamp_ns = *_f6;
        auto _ev7 = d->read_int32();
        if (!_ev7) { return std::nullopt; }
        v.header.priority = static_cast<Priority>(*_ev7);
        for (auto& _elem8 : v.values) {
            auto _f9 = d->read_float64();
            if (!_f9) { return std::nullopt; }
            _elem8 = *_f9;
        }
        auto _f10 = d->read_float32();
        if (!_f10) { return std::nullopt; }
        v.temperature = *_f10;
        auto _f11 = d->read_bool();
        if (!_f11) { return std::nullopt; }
        v.valid = *_f11;
        auto _n12 = d->read_uint32();
        if (!_n12) { return std::nullopt; }
        v.extras.resize(*_n12);
        for (auto& _elem13 : v.extras) {
            auto _f14 = d->read_float64();
            if (!_f14) { return std::nullopt; }
            _elem13 = *_f14;
        }
        return v;
    }

    // key_fields returns the field names marked @key in the IDL source.
    static std::vector<std::string> key_fields() {
        return {};
    }
};

} // namespace idlgen
