// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// rtps/cdr.hpp — Discovery-scoped CDR/PL_CDR encoding (RTPS 2.3 §10.2–§10.3),
// used to encode/decode SPDP/SEDP parameter lists.
//
// This is Tier-1 sub-phase 2 of the cpp-DDS RTPS roadmap (see ROADMAP.md,
// "Tier 1 — RTPS wire protocol", phase 2: "Discovery-scoped CDR/PL_CDR
// encoding"). It is internal, additive scaffolding: NOT yet wired into the
// public dds::IParticipant / relay::INode surface, and not yet consumed by
// SPDP/SEDP (those are later phases). Little-endian only — the de-facto
// standard for modern RTPS — mirroring go-DDS, which never emits a
// big-endian encapsulation here.
//
// This is deliberately a *minimal* subset sufficient for discovery
// submessages. It is NOT the general-purpose XCDR1 codec for arbitrary
// IDL-defined user payload types — that is Tier 3's separate `dds/cdr/`
// library. go-DDS keeps these as two separate packages (`rtps/cdr.go` vs.
// top-level `cdr/`) and cpp-DDS follows suit: this file lives under
// `dds/rtps/`, not `dds/cdr/`.
//
// C++ port of github.com/SoundMatt/go-DDS's rtps/cdr.go (the
// plCDREncoder/plCDRDecoder types and their methods), plus the
// cdrWrapPayload/cdrUnwrapPayload helpers from rtps/message.go (the CDR_LE
// encapsulation header used to wrap a DATA submessage's serializedPayload —
// same encapsulation-scheme concern as cdr.go, just defined in the other
// file upstream). Every encode()/finish() here MUST produce byte-identical
// output to the corresponding go-DDS function; see
// tests/test_rtps_cdr.cpp for the reference vectors (generated by
// literally calling go-DDS's own unexported functions white-box from a
// scratch _test.go file — not re-derived by hand) that pin this.

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <dds/rtps/types.hpp>

namespace dds::rtps {

// ── CDR encapsulation scheme identifiers (RTPS 2.3 §10.2 Table 10.1) ───────

inline constexpr uint16_t kSchemeCDRLE   = 0x0001; // CDR little-endian
inline constexpr uint16_t kSchemePLCDRLE = 0x0003; // PL_CDR little-endian

// ── Parameter IDs for SPDP ParticipantProxy and SEDP EndpointData (§9.6.3) ──

inline constexpr uint16_t kPidPad                         = 0x0000;
inline constexpr uint16_t kPidSentinel                    = 0x0001;
inline constexpr uint16_t kPidUserData                    = 0x002C;
inline constexpr uint16_t kPidTopicName                   = 0x0005;
inline constexpr uint16_t kPidTypeName                    = 0x0007;
inline constexpr uint16_t kPidProtocolVersion             = 0x0015;
inline constexpr uint16_t kPidVendorId                    = 0x0016;
inline constexpr uint16_t kPidMetatrafficUnicastLocator   = 0x0032;
inline constexpr uint16_t kPidMetatrafficMulticastLocator = 0x0033;
inline constexpr uint16_t kPidDefaultUnicastLocator       = 0x002F;
inline constexpr uint16_t kPidDefaultMulticastLocator     = 0x0030;
inline constexpr uint16_t kPidParticipantLeaseDuration    = 0x0002;
inline constexpr uint16_t kPidParticipantGUID             = 0x0050;
inline constexpr uint16_t kPidEndpointGUID                = 0x005A;
inline constexpr uint16_t kPidBuiltinEndpointSet          = 0x0058;
inline constexpr uint16_t kPidReliability                 = 0x001A;
inline constexpr uint16_t kPidDurability                  = 0x001D;
// Vendor-specific PIDs (OMG vendor-extension range 0x8000-0xBFFF), matching
// go-DDS's pidDiscoveryToken/pidEndpointToken (rtps/cdr.go) used to carry
// discovery/endpoint authentication tags from a DiscoveryPlugin/EndpointPlugin.
inline constexpr uint16_t kPidDiscoveryToken              = 0x8001;
inline constexpr uint16_t kPidEndpointToken               = 0x8002;

// ── PLCDREncoder ─────────────────────────────────────────────────────────────

// PLCDREncoder builds a PL_CDR_LE encoded parameter list, matching go-DDS's
// plCDREncoder (rtps/cdr.go) field for field.
class PLCDREncoder {
public:
    // Pre-seeds the buffer with the PL_CDR_LE encapsulation header: scheme
    // (2 bytes, little-endian) + options (2 bytes, zero).
    PLCDREncoder();

    // Appends a (PID, length, value) triple, padding value up to a 4-byte
    // boundary with zero bytes. length in the wire header is the *padded*
    // length, matching go-DDS's addParam.
    void add_param(uint16_t pid, const uint8_t* value, std::size_t len);
    void add_param(uint16_t pid, const std::vector<uint8_t>& value);

    // Appends a 4-byte little-endian uint32 parameter.
    void add_uint32(uint16_t pid, uint32_t v);

    // Appends a 24-byte Locator parameter (Locator::encode's wire format).
    void add_locator(uint16_t pid, const Locator& l);

    // Appends a 16-byte GUID parameter (GUID::encode's wire format).
    void add_guid(uint16_t pid, const GUID& g);

    // Appends a CDR string parameter: uint32 length (including the null
    // terminator) + chars + null terminator, then padded to 4 bytes.
    void add_string(uint16_t pid, const std::string& s);

    // Appends an arbitrary byte-vector parameter (alias for add_param,
    // matching go-DDS's separate addBytes name/call site for clarity at
    // SEDP/SPDP call sites even though the wire behavior is identical).
    void add_bytes(uint16_t pid, const std::vector<uint8_t>& v);

    // Appends the PID_SENTINEL terminator and returns the fully encoded
    // buffer. Does not mutate internal state (safe to call once; matches
    // go-DDS's finish(), which is likewise only ever called once per
    // encoder in practice).
    std::vector<uint8_t> finish() const;

private:
    std::vector<uint8_t> buf_;
};

// ── PLCDRDecoder ─────────────────────────────────────────────────────────────

// Param is a single decoded (PID, value) entry. value is a view into the
// buffer passed to PLCDRDecoder::create — it remains valid only as long as
// that buffer does (matching go-DDS's decoder, which returns a sub-slice of
// the original byte slice rather than copying).
struct Param {
    uint16_t pid{0};
    const uint8_t* value{nullptr};
    std::size_t value_len{0};
};

// PLCDRDecoder iterates over a PL_CDR_LE parameter list, matching go-DDS's
// plCDRDecoder (rtps/cdr.go).
class PLCDRDecoder {
public:
    // Validates the 4-byte PL_CDR_LE header and returns a decoder positioned
    // just past it. Returns std::nullopt if len < 4 or the scheme field is
    // not kSchemePLCDRLE.
    static std::optional<PLCDRDecoder> create(const uint8_t* data, std::size_t len);

    // Returns the next parameter, advancing the cursor. Returns std::nullopt
    // at PID_SENTINEL, on a truncated/malformed header or value, or once the
    // buffer is exhausted — matching go-DDS's next(). PID_PAD entries are
    // transparently skipped (recursive skip in go-DDS; iterative here).
    std::optional<Param> next();

private:
    PLCDRDecoder(const uint8_t* data, std::size_t len, std::size_t pos)
        : data_(data), len_(len), pos_(pos) {}

    const uint8_t* data_{nullptr};
    std::size_t len_{0};
    std::size_t pos_{0};
};

// ── standalone decode helpers ────────────────────────────────────────────────

// Reads a CDR string from a parameter value: uint32 length (including null
// terminator) + chars + null terminator. The trailing null is stripped from
// the returned string, matching go-DDS's decodeString.
std::optional<std::string> decode_string(const uint8_t* value, std::size_t len);
inline std::optional<std::string> decode_string(const std::vector<uint8_t>& value) {
    return decode_string(value.data(), value.size());
}

// Reads a 16-byte GUID from a parameter value. Identical wire format to
// GUID::encode/decode (prefix || entity, no endianness concern), so this is
// a thin alias kept for API symmetry with decode_string at SPDP/SEDP call
// sites — matching go-DDS's separate decodeGUID function even though the
// implementation is literally GUID::decode.
inline std::optional<GUID> decode_guid(const uint8_t* value, std::size_t len) {
    return GUID::decode(value, len);
}
inline std::optional<GUID> decode_guid(const std::vector<uint8_t>& value) {
    return GUID::decode(value.data(), value.size());
}

// ── CDR_LE payload encapsulation (rtps/message.go: cdrWrapPayload/Unwrap) ───

// Prepends the 4-byte CDR_LE encapsulation header (scheme=kSchemeCDRLE,
// options=0) to a raw payload, matching go-DDS's cdrWrapPayload. Used to
// wrap a DATA submessage's serializedPayload.
std::vector<uint8_t> cdr_wrap_payload(const std::vector<uint8_t>& payload);

// Strips the 4-byte CDR/PL_CDR encapsulation header, accepting either
// kSchemeCDRLE or kSchemePLCDRLE (matching go-DDS's cdrUnwrapPayload).
// Returns std::nullopt if len < 4 or the scheme is neither of those two.
std::optional<std::vector<uint8_t>> cdr_unwrap_payload(const uint8_t* data, std::size_t len);
inline std::optional<std::vector<uint8_t>> cdr_unwrap_payload(const std::vector<uint8_t>& data) {
    return cdr_unwrap_payload(data.data(), data.size());
}

} // namespace dds::rtps
