// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// rtps/sedp.hpp — SEDP: Simple Endpoint Discovery Protocol
// (RTPS 2.3 §8.5.4 / §9.6.2). When a local writer or reader is registered,
// SEDP sends a publication or subscription announcement unicast to every
// known participant's meta-unicast port. When a remote announcement
// arrives, its topic name is matched against local endpoints so readers
// can be linked to their matching writers.
//
// This is Tier-1 sub-phase 5 of the cpp-DDS RTPS roadmap (see ROADMAP.md,
// "Tier 1 — RTPS wire protocol", phase 5: "SEDP"). It is internal,
// additive scaffolding: NOT yet wired into the public
// dds::IParticipant / relay::INode surface. That happens once entities
// (phase 6) exist to actually own reader/writer objects and a
// HistoryCache for matched data to flow into.
//
// C++ port of github.com/SoundMatt/go-DDS's rtps/sedp.go (sedpService and
// its methods). Every build_endpoint_data()/build_sedp_announcement()
// output here MUST produce byte-identical wire bytes to the corresponding
// go-DDS function for equivalent field values; see
// tests/test_rtps_sedp.cpp for the reference vectors (generated by
// literally calling go-DDS's own unexported functions white-box from a
// scratch _test.go file — not re-derived by hand) that pin this.
//
// Scope notes (deliberate deviations from a literal line-for-line port,
// matching the "internal scaffolding, no entities yet" constraint of this
// phase — the same constraint SPDP (phase 4) was built under):
//
//   - go-DDS's sedpService is a method set on the full `participant` type
//     (rtps/participant.go, 1,505 LOC — Tier-1 phase 6, not yet ported)
//     and reaches into it for exactly two things: the participant's own
//     GUID prefix/data-unicast port (to build endpoint payloads) and
//     `s.p.spdp.allPeers()` (to broadcast to every known participant).
//     This port instead takes the small, explicit slice of state SEDP
//     actually needs via SedpConfig, and maintains its own known-peers
//     table fed by explicit on_new_peer()/on_peer_evicted() calls — the
//     same shape SpdpService's own known-peers table already has —
//     rather than holding a live reference to a not-yet-ported
//     participant or a direct dependency on the SpdpService class. Phase
//     6 is expected to own a SedpService instance and wire
//     SpdpService::on_new_peer/eviction events into it, exactly as
//     go-DDS's participant type wires spdpService and sedpService
//     together internally.
//   - go-DDS's `endpointInfo` also carries `isWriter`, but nothing ever
//     reads that field back off a *received* announcement (the writer/
//     reader distinction for incoming packets is made once, up front, by
//     which SEDP writer entity ID the DATA submessage carries — see
//     handle_packet/handle_endpoint_announce). This port therefore keeps
//     `is_writer` on EndpointInfo (used for locally-registered endpoints,
//     matching go-DDS) but omits it from ParsedEndpointInfo (the decoded-
//     from-wire shape), which is a value-preserving simplification, not a
//     behavioral change.
//   - go-DDS's `sedpService.registerReader`/`onRemoteWriter` link a
//     matched writer to a reader by calling `r.addSourceGUID(rw.guid)` on
//     the not-yet-ported `rtpsReader` type, and `onRemoteWriter` also
//     registers the writer's data-delivery locator on the participant via
//     `p.addWriterLocator`. Both are replaced here with explicit query
//     tables (`matched_writer_guids_for_reader`, `writer_locator`,
//     `reader_locator`) that phase 6 can consume once rtpsReader/writer
//     equivalents exist — the matching bookkeeping itself (this phase's
//     actual deliverable) is fully ported, including the
//     `endpoint_matches` counter go-DDS increments in `onRemoteWriter`.
//   - The optional EndpointPlugin authentication-tag exchange
//     (`pidEndpointToken`) is omitted, mirroring SPDP's omission of
//     `pidDiscoveryToken`: it is Tier-2 security scope, not part of this
//     phase's "announce + topic-match" description.
//   - go-DDS's single process-wide `nextSeqNum()` atomic (shared by every
//     participant's SPDP *and* SEDP writers) is, as in SpdpService, one
//     atomic counter per SedpService instance instead — scoped to this
//     phase; a later phase can thread a shared counter through once one
//     exists to wire alongside it.
//   - Threading: only a receive loop runs in the background (go-DDS's
//     `sedpService.start()` likewise launches only `receiveLoop` — unlike
//     SPDP there is no periodic announce loop; SEDP announcements are
//     purely event-driven, fired from register_writer/register_reader/
//     on_new_peer). Uses the same cancellable-sleep-free, socket-internal-
//     timeout poll pattern as SpdpService::receive_loop.

#pragma once

#include <atomic>
#include <cstdint>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include <dds/rtps/cdr.hpp>
#include <dds/rtps/spdp.hpp>
#include <dds/rtps/transport.hpp>
#include <dds/rtps/types.hpp>

namespace dds::rtps {

// ── EndpointInfo ─────────────────────────────────────────────────────────────

// EndpointInfo describes a local or remote DDS endpoint. C++ port of
// go-DDS's endpointInfo (rtps/sedp.go).
struct EndpointInfo {
    GUID        guid{};
    std::string topic_name;
    bool        is_writer{false};
};

// Builds PL_CDR_LE EndpointData wire bytes for one endpoint, matching
// go-DDS's sedpService.buildEndpointData field for field. data_unicast_port
// is the participant-level user-DATA unicast port (go-DDS: p.dataSock.port)
// advertised via pidDefaultUnicastLocator — the same port for every local
// endpoint on this participant, regardless of that endpoint's own identity.
std::vector<uint8_t> build_endpoint_data(const EndpointInfo& info, uint16_t data_unicast_port);

// ParsedEndpointInfo is the decoded shape of a received EndpointData
// payload — see the file-level scope note for why it omits is_writer.
struct ParsedEndpointInfo {
    GUID        guid{};
    std::string topic_name;
    Locator     data_locator{};
};

// Parses PL_CDR_LE EndpointData received from from_address (dotted-quad
// IPv4). remote_prefix seeds guid.prefix (overwritten if a pidEndpointGUID
// parameter is present), matching go-DDS's handleEndpointAnnounce:
// `info.guid.Prefix = remotePrefix` is set before the decode loop, then
// possibly replaced by a decoded pidEndpointGUID value. A 0.0.0.0-address
// pidDefaultUnicastLocator has from_address filled into its trailing 4
// bytes, matching go-DDS's decodeLocator fill-in path (same trick
// parse_participant_data uses for SPDP). Returns std::nullopt if the
// PL_CDR_LE header itself is invalid, or if no pidTopicName parameter was
// present (go-DDS: handleEndpointAnnounce returns early when
// info.topicName == "").
std::optional<ParsedEndpointInfo> parse_endpoint_data(const GuidPrefix&   remote_prefix,
                                                        const uint8_t*      payload,
                                                        std::size_t         payload_len,
                                                        const std::string&  from_address);

// Builds the full wire bytes of one SEDP endpoint announcement: a DATA
// submessage (writer=writer_eid, reader=reader_eid, payload) wrapped in an
// RTPS message. C++ port of the construction shape shared by go-DDS's
// sedpService.announceWriter (writer_eid/reader_eid =
// kEntityIdSEDPPubWriter/kEntityIdSEDPPubReader) and .announceReader
// (kEntityIdSEDPSubWriter/kEntityIdSEDPSubReader).
std::vector<uint8_t> build_sedp_announcement(const GuidPrefix& local_prefix, const VendorId& vendor_id,
                                              const EntityId& writer_eid, const EntityId& reader_eid,
                                              SequenceNumber seq_num, const std::vector<uint8_t>& payload);

// ── SedpService ───────────────────────────────────────────────────────────────

// SedpConfig configures a SedpService instance.
struct SedpConfig {
    GuidPrefix local_guid_prefix{};
    // This participant's user-DATA unicast port, advertised in every local
    // endpoint announcement (go-DDS: p.dataSock.port).
    uint16_t data_unicast_port{0};
    VendorId vendor_id{kVendorIdCppDDS};
};

// SedpService manages local endpoint registration/announcement and the
// remote endpoint tables populated from received announcements. C++ port
// of go-DDS's sedpService (rtps/sedp.go) — see the file-level scope note
// for the deliberate deviations relative to a full line-for-line port.
class SedpService {
public:
    // socket is used both to send unicast announcements and to receive
    // them (go-DDS: p.metaSock, shared with SPDP's outbound send — see the
    // scope note in spdp.hpp about why SpdpService owns its own send
    // socket instead of literally sharing one with this class). Moved
    // into the service.
    SedpService(SedpConfig config, UdpSocket socket);
    ~SedpService();

    SedpService(const SedpService&)            = delete;
    SedpService& operator=(const SedpService&) = delete;
    SedpService(SedpService&&)                 = delete;
    SedpService& operator=(SedpService&&)      = delete;

    // Starts the receive thread. No-op if already started.
    void start();

    // Stops the receive thread and joins it. No-op if already stopped;
    // safe to call more than once and from the destructor.
    void stop();

    // Registers a local writer, records it, and immediately announces it
    // to every peer currently in the known-peers table (go-DDS:
    // registerWriter).
    void register_writer(const EntityId& eid, const std::string& topic_name);

    // Registers a local reader, records it, matches it against
    // already-discovered remote writers for the same topic (recorded in
    // matched_writer_guids_for_reader — see the file-level scope note),
    // and announces it to every known peer (go-DDS: registerReader).
    void register_reader(const EntityId& eid, const std::string& topic_name);

    // Records peer in the known-peers table and announces every currently
    // registered local endpoint to just that peer (go-DDS: onNewPeer, plus
    // the known-peers bookkeeping this port folds in — see the file-level
    // scope note). Intended to be called by phase 6's wiring whenever
    // SpdpService discovers a genuinely new participant.
    void on_new_peer(const ParticipantProxy& peer);

    // Removes peer's prefix from the known-peers table and purges all
    // remote endpoints (and their locators) belonging to it (go-DDS:
    // onPeerEvicted). Intended to be called by phase 6's wiring whenever a
    // peer's SPDP lease expires.
    void on_peer_evicted(const GuidPrefix& prefix);

    // Processes one received datagram as if it had arrived on this
    // service's socket (go-DDS: handlePacket). Called internally by the
    // receive loop; exposed so tests can drive the remote endpoint tables
    // deterministically without depending on socket timing.
    void handle_packet(const std::vector<uint8_t>& data, const std::string& from_address);

    // ── query surface for phase 6's reader/writer wiring ──────────────────

    // Snapshot of remote writer GUIDs matched to reader_eid so far (via
    // either register_reader or a later remote-writer announcement).
    std::vector<GUID> matched_writer_guids_for_reader(const EntityId& reader_eid) const;

    // Data-delivery locator for a matched remote writer, if known.
    std::optional<Locator> writer_locator(const GUID& writer_guid) const;

    // Data-delivery locator for a matched remote reader, if known.
    std::optional<Locator> reader_locator(const GUID& reader_guid) const;

    uint64_t endpoint_matches() const noexcept { return endpoint_matches_.load(); }
    uint64_t announces_sent() const noexcept { return announces_sent_.load(); }
    uint64_t announces_received() const noexcept { return announces_received_.load(); }

private:
    struct GuidPrefixHash {
        std::size_t operator()(const GuidPrefix& g) const noexcept;
    };
    struct EntityIdHash {
        std::size_t operator()(const EntityId& e) const noexcept;
    };
    struct GUIDHash {
        std::size_t operator()(const GUID& g) const noexcept;
    };

    void announce_writer(const EndpointInfo& info, const ParticipantProxy* only_to);
    void announce_reader(const EndpointInfo& info, const ParticipantProxy* only_to);
    void broadcast(const std::vector<uint8_t>& msg, const ParticipantProxy* only_to);
    void send_to(const std::vector<uint8_t>& msg, const ParticipantProxy& peer);

    void handle_endpoint_announce(const GuidPrefix& remote_prefix, const std::vector<uint8_t>& payload,
                                   bool is_writer, const std::string& from_address);
    void on_remote_writer(const EndpointInfo& info, const Locator& data_locator);
    void on_remote_reader(const EndpointInfo& info, const Locator& data_locator);

    void receive_loop();

    SedpConfig config_;
    UdpSocket  socket_;

    mutable std::mutex mu_;
    std::unordered_map<EntityId, EndpointInfo, EntityIdHash> local_writers_;
    std::unordered_map<EntityId, EndpointInfo, EntityIdHash> local_readers_;
    std::unordered_map<GUID, EndpointInfo, GUIDHash>         remote_writers_;
    std::unordered_map<GUID, EndpointInfo, GUIDHash>         remote_readers_;
    std::unordered_map<GUID, Locator, GUIDHash>               remote_writer_locs_;
    std::unordered_map<GUID, Locator, GUIDHash>               remote_reader_locs_;
    std::unordered_map<EntityId, std::vector<GUID>, EntityIdHash> matched_writers_by_reader_;
    std::unordered_map<GuidPrefix, ParticipantProxy, GuidPrefixHash> known_peers_;

    std::atomic<bool>     running_{false};
    std::atomic<uint32_t> seq_counter_{0};
    std::thread           receive_thread_;

    std::atomic<uint64_t> announces_sent_{0};
    std::atomic<uint64_t> announces_received_{0};
    std::atomic<uint64_t> endpoint_matches_{0};
};

} // namespace dds::rtps
