// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// rtps/spdp.hpp — SPDP: Simple Participant Discovery Protocol
// (RTPS 2.3 §8.5.3 / §9.6.1). Periodic multicast self-announcement of the
// local participant, plus a known-participants table populated from
// received announcements.
//
// This is Tier-1 sub-phase 4 of the cpp-DDS RTPS roadmap (see ROADMAP.md,
// "Tier 1 — RTPS wire protocol", phase 4: "SPDP"). It is internal,
// additive scaffolding: NOT yet wired into the public
// dds::IParticipant / relay::INode surface. That happens once entities
// (phase 6) exist to actually own and expose a participant object.
//
// C++ port of github.com/SoundMatt/go-DDS's rtps/spdp.go
// (spdpService/participantProxy and their methods). Every
// build_participant_data()/build_spdp_announcement() output here MUST
// produce byte-identical wire bytes to the corresponding go-DDS function
// for equivalent field values; see tests/test_rtps_spdp.cpp for the
// reference vectors (generated by literally calling go-DDS's own
// unexported functions white-box from a scratch _test.go file — not
// re-derived by hand) that pin this.
//
// Scope notes (deliberate deviations from a literal line-for-line port,
// matching the "internal scaffolding, no entities yet" constraint of this
// phase):
//
//   - go-DDS's spdpService is a method set on the full `participant` type
//     (rtps/participant.go, 1,505 LOC — Tier-1 phase 6, not yet ported).
//     This port instead takes only the small, explicit slice of
//     participant state SPDP actually needs (guid prefix, the two
//     unicast ports it advertises) via SpdpLocalInfo/SpdpConfig, so this
//     phase is independently buildable/testable without phase 6 existing
//     yet. Phase 6 is expected to own an SpdpService instance rather than
//     reimplementing its logic.
//   - The SEDP-notification hooks (`s.p.sedp.onNewPeer` /
//     `s.p.sedp.onPeerEvicted`) and the liveliness callback
//     (`s.p.livelinessCb`) are omitted: both depend on machinery (SEDP,
//     dds::IParticipant's liveliness surface) that doesn't exist until
//     later phases / the public-API wiring phase. The known-peers table
//     itself — this phase's actual deliverable — is fully ported.
//   - The optional DiscoveryPlugin authentication-token exchange
//     (`pidDiscoveryToken`) is omitted: it is Tier-2 security scope, not
//     part of this phase's "periodic announcement + known-participants
//     table" description.
//   - go-DDS's `nextSeqNum()` draws from a single process-wide
//     `atomic.Uint32` shared by every participant's SPDP *and* SEDP
//     writers in the process, so sequence numbers stay unique across a
//     multi-participant process. This port uses one atomic counter per
//     SpdpService instead, scoped to this phase (no SEDP writer to share
//     with yet); a later phase can thread a shared counter through once
//     one exists to wire alongside it.
//   - SpdpConfig::dest_address/dest_port default to the standard SPDP
//     multicast group/port (matching go-DDS exactly for production use)
//     but are overridable — production code should never override them;
//     tests use the override to exercise real peer discovery
//     deterministically over unicast loopback, since true multicast
//     delivery is not guaranteed in sandboxed CI environments (see
//     rtps/transport.hpp's UdpSocket::bind_multicast_receive doc comment
//     and its own test's same caveat).
//   - Threading: go-DDS uses goroutines + channels + select. This port
//     uses std::thread with a short-slice cancellable sleep (mirroring
//     the same "poll and check shutdown" pattern UdpSocket::recv already
//     uses for its 250ms read-deadline poll) instead of a native
//     cancellation primitive, since plain std::thread has none.

#pragma once

#include <atomic>
#include <chrono>
#include <cstdint>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include <dds/rtps/cdr.hpp>
#include <dds/rtps/transport.hpp>
#include <dds/rtps/types.hpp>

namespace dds::rtps {

// Default participant announcement interval (go-DDS: spdpAnnouncePeriod).
inline constexpr std::chrono::milliseconds kSpdpAnnouncePeriod{2000};

// Default lease duration: both the value advertised to peers via
// pidParticipantLeaseDuration and the fallback eviction timeout used for a
// peer that didn't advertise one (go-DDS: defaultLeaseDuration).
inline constexpr std::chrono::seconds kSpdpDefaultLeaseDuration{10};

// ── ParticipantProxy ─────────────────────────────────────────────────────────

// ParticipantProxy stores the addresses needed to exchange SEDP traffic with
// a remote participant, discovered via its SPDP announcements. C++ port of
// go-DDS's participantProxy (rtps/spdp.go).
struct ParticipantProxy {
    GUID     guid{};
    Locator  metatraffic_unicast{};
    Locator  default_unicast{};
    uint32_t builtin_endpoints{0};
    // 0 => caller should fall back to kSpdpDefaultLeaseDuration (matches
    // go-DDS's leaseDuration==0 sentinel).
    std::chrono::seconds                 lease_duration{0};
    std::chrono::steady_clock::time_point last_seen{};
};

// ── Self-announcement data ───────────────────────────────────────────────────

// SpdpLocalInfo is what this participant announces about itself. C++
// counterpart of the participant fields go-DDS's buildParticipantData reads
// (p.guidPrefix, p.metaSock.port, p.dataSock.port).
struct SpdpLocalInfo {
    GuidPrefix guid_prefix{};
    uint16_t   meta_unicast_port{0};    // advertised as pidMetatrafficUnicastLocator
    uint16_t   default_unicast_port{0}; // advertised as pidDefaultUnicastLocator
    VendorId   vendor_id{kVendorIdCppDDS};
    // Value written into pidParticipantLeaseDuration (go-DDS hardcodes 10
    // seconds here; kept configurable but defaults to the same value for
    // byte-exact parity with the reference vectors).
    std::chrono::seconds advertised_lease_duration{kSpdpDefaultLeaseDuration};
};

// Builds PL_CDR_LE ParticipantProxy data. Byte-identical to go-DDS's
// spdpService.buildParticipantData for equivalent field values (see
// tests/test_rtps_spdp.cpp).
std::vector<uint8_t> build_participant_data(const SpdpLocalInfo& info);

// Parses PL_CDR_LE participant proxy data received from from_address
// (dotted-quad IPv4). Matches go-DDS's parseParticipantData, including the
// 0.0.0.0-locator-address fill-in from the packet's source address. Returns
// std::nullopt only if the PL_CDR_LE header itself is invalid (matching
// go-DDS: a proxy with default/zero fields is still returned if individual
// parameters are absent).
std::optional<ParticipantProxy> parse_participant_data(const GuidPrefix& remote_prefix,
                                                         const uint8_t*   payload,
                                                         std::size_t      payload_len,
                                                         const std::string& from_address);

// Wraps submessage bytes in a full RTPS message: 20-byte Header +
// submessages. C++ port of go-DDS's wrapInRTPSMessage (message.go).
std::vector<uint8_t> wrap_in_rtps_message(const GuidPrefix& prefix, const VendorId& vendor_id,
                                           const std::vector<uint8_t>& submessage_bytes);

// Builds the full wire bytes of one SPDP self-announcement: a DATA
// submessage (writer=kEntityIdSPDPWriter, reader=kEntityIdSPDPReader,
// payload=build_participant_data(info)) wrapped in an RTPS message. C++
// port of go-DDS's spdpService.sendAnnouncement's message-construction path
// (the UDP send itself is SpdpService::send_announcement, below).
std::vector<uint8_t> build_spdp_announcement(const SpdpLocalInfo& info, SequenceNumber seq_num);

// ── SpdpService ───────────────────────────────────────────────────────────────

// SpdpConfig configures an SpdpService instance.
struct SpdpConfig {
    int            domain{0};
    SpdpLocalInfo  local{};
    std::chrono::milliseconds announce_period{kSpdpAnnouncePeriod}; // 0 => kSpdpAnnouncePeriod
    std::chrono::milliseconds jitter{0};                            // 0 => no jitter
    // Eviction timeout applied to a peer whose announcement didn't carry a
    // pidParticipantLeaseDuration (go-DDS: defaultLeaseDuration).
    std::chrono::seconds peer_lease_duration{kSpdpDefaultLeaseDuration};

    // Destination for outgoing announcements. Defaults to the standard
    // SPDP multicast group; dest_port < 0 means "derive from
    // meta_multicast_port(domain)". See the file-level scope note above
    // for why this is overridable (test determinism only).
    std::string dest_address{kSpdpMulticastAddr};
    int         dest_port{-1};
};

// SpdpService manages periodic SPDP self-announcement and the known-peers
// table populated from received announcements. C++ port of go-DDS's
// spdpService (rtps/spdp.go) — see the file-level scope note for the
// deliberate omissions (SEDP/liveliness hooks, DiscoveryPlugin) relative to
// a full line-for-line port.
class SpdpService {
public:
    // send_socket is used to transmit announcements (go-DDS: p.metaSock);
    // recv_socket receives incoming announcements and should be bound via
    // UdpSocket::bind_multicast_receive (go-DDS: p.mcastSock). Both are
    // moved into the service.
    SpdpService(SpdpConfig config, UdpSocket send_socket, UdpSocket recv_socket);
    ~SpdpService();

    SpdpService(const SpdpService&)            = delete;
    SpdpService& operator=(const SpdpService&) = delete;
    SpdpService(SpdpService&&)                 = delete;
    SpdpService& operator=(SpdpService&&)      = delete;

    // Starts the announce, receive, and lease-eviction threads. No-op if
    // already started.
    void start();

    // Stops all threads and joins them. No-op if already stopped; safe to
    // call more than once and from the destructor.
    void stop();

    // Snapshot of all known participant proxies (go-DDS: allPeers).
    std::vector<ParticipantProxy> peers() const;

    uint64_t announces_sent() const noexcept { return announces_sent_.load(); }
    uint64_t announces_received() const noexcept { return announces_received_.load(); }
    uint64_t peer_evictions() const noexcept { return peer_evictions_.load(); }

    // Sends one announcement immediately over send_socket. Called
    // internally by the announce loop; exposed so tests (and, in the
    // future, an on-demand "announce now" API) don't have to wait a full
    // announce_period.
    void send_announcement();

    // Processes one received datagram as if it had arrived on recv_socket.
    // Called internally by the receive loop; exposed so tests can drive
    // the known-peers table deterministically without depending on socket
    // timing.
    void handle_packet(const std::vector<uint8_t>& data, const std::string& from_address);

    // Removes any peer whose lease has expired. Called internally by the
    // eviction loop once per second (go-DDS: evictLoop); exposed for
    // deterministic tests.
    void evict_expired();

private:
    void announce_loop();
    void receive_loop();
    void evict_loop();
    void store_peer(ParticipantProxy proxy);

    struct GuidPrefixHash {
        std::size_t operator()(const GuidPrefix& g) const noexcept;
    };

    SpdpConfig config_;
    UdpSocket  send_socket_;
    UdpSocket  recv_socket_;

    mutable std::mutex mu_;
    std::unordered_map<GuidPrefix, ParticipantProxy, GuidPrefixHash> peers_;

    std::atomic<bool>     running_{false};
    std::atomic<uint32_t> seq_counter_{0};

    std::thread announce_thread_;
    std::thread receive_thread_;
    std::thread evict_thread_;

    std::atomic<uint64_t> announces_sent_{0};
    std::atomic<uint64_t> announces_received_{0};
    std::atomic<uint64_t> peer_evictions_{0};
};

} // namespace dds::rtps
