// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// rtps/types.hpp — Foundational RTPS 2.3 wire types: GuidPrefix, EntityId,
// GUID (§9.3.1), Locator_t (§9.3.2), and message framing — ProtocolVersion,
// VendorId, Header, SubmessageHeader, SequenceNumber, DataSubmessage (§9.4).
//
// This is Tier-1 sub-phase 1 of the cpp-DDS RTPS roadmap (see ROADMAP.md,
// "Tier 1 — RTPS wire protocol", phase 1: "Wire types & framing"). It is
// internal, additive scaffolding: NOT yet wired into the public
// dds::IParticipant / relay::INode surface. That happens in a later phase
// once UDP transport (phase 3) and entities (phase 6) exist.
//
// C++ port of github.com/SoundMatt/go-DDS's `rtps` package, specifically
// guid.go, locator.go, and message.go (Header / DATA submessage framing
// only — HEARTBEAT/ACKNACK/GAP/INFO_TS are later phases). Every encode()
// here MUST produce byte-identical output to the corresponding go-DDS
// marshal function; see tests/test_rtps_types.cpp for the reference
// vectors (generated by literally calling go-DDS's own marshal functions —
// not re-derived by hand) that pin this.
//
// All multi-byte integer fields in RTPS 2.3 discovery/message framing are
// little-endian only (go-DDS never emits big-endian; see message.go's
// exclusive use of encoding/binary.LittleEndian and the always-set 'E'
// endianness flag). This port follows suit: no big-endian path exists.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <optional>
#include <vector>

namespace dds::rtps {

// ── GuidPrefix / EntityId / GUID (RTPS 2.3 §9.3.1) ──────────────────────────

// GuidPrefix is the 12-byte participant identifier.
struct GuidPrefix {
    static constexpr std::size_t kSize = 12;
    std::array<uint8_t, kSize> bytes{};

    bool operator==(const GuidPrefix& o) const noexcept { return bytes == o.bytes; }
    bool operator!=(const GuidPrefix& o) const noexcept { return !(*this == o); }
};

// EntityId identifies a specific endpoint within a participant.
struct EntityId {
    static constexpr std::size_t kSize = 4;
    std::array<uint8_t, kSize> bytes{};

    bool operator==(const EntityId& o) const noexcept { return bytes == o.bytes; }
    bool operator!=(const EntityId& o) const noexcept { return !(*this == o); }
};

// Well-known entity IDs per RTPS 2.3 Table 9.1 (go-DDS guid.go).
inline constexpr EntityId kEntityIdParticipant{{0x00, 0x00, 0x01, 0xC1}};
inline constexpr EntityId kEntityIdSPDPWriter{{0x00, 0x01, 0x00, 0xC2}};
inline constexpr EntityId kEntityIdSPDPReader{{0x00, 0x01, 0x00, 0xC7}};
inline constexpr EntityId kEntityIdSEDPPubWriter{{0x00, 0x00, 0x03, 0xC2}};
inline constexpr EntityId kEntityIdSEDPPubReader{{0x00, 0x00, 0x03, 0xC7}};
inline constexpr EntityId kEntityIdSEDPSubWriter{{0x00, 0x00, 0x04, 0xC2}};
inline constexpr EntityId kEntityIdSEDPSubReader{{0x00, 0x00, 0x04, 0xC7}};
inline constexpr EntityId kEntityIdUnknown{{0x00, 0x00, 0x00, 0x00}};

// Builtin endpoint availability bitmask (§8.5.4.3 / §9.6.2.2).
inline constexpr uint32_t kEndpointSPDPAnnouncer    = 1u << 0;
inline constexpr uint32_t kEndpointSPDPDetector     = 1u << 1;
inline constexpr uint32_t kEndpointSEDPPubAnnouncer = 1u << 2;
inline constexpr uint32_t kEndpointSEDPPubDetector  = 1u << 3;
inline constexpr uint32_t kEndpointSEDPSubAnnouncer = 1u << 4;
inline constexpr uint32_t kEndpointSEDPSubDetector  = 1u << 5;

// GUID globally identifies a DDS entity: participant + endpoint. Wire
// encoding is a plain 16-byte concatenation of prefix then entity — there
// is no endianness concern since it is raw byte copy in go-DDS too (GUID
// bytes are never treated as a multi-byte integer).
struct GUID {
    static constexpr std::size_t kSize = GuidPrefix::kSize + EntityId::kSize; // 16
    GuidPrefix prefix{};
    EntityId   entity{};

    bool operator==(const GUID& o) const noexcept {
        return prefix == o.prefix && entity == o.entity;
    }
    bool operator!=(const GUID& o) const noexcept { return !(*this == o); }

    // Appends the 16-byte wire encoding (prefix || entity) to out.
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 16-byte GUID from data[0..len). Returns std::nullopt if
    // len < kSize.
    static std::optional<GUID> decode(const uint8_t* data, std::size_t len);
};

// ── Locator_t (RTPS 2.3 §9.3.2) ──────────────────────────────────────────────

struct Locator {
    static constexpr std::size_t kSize    = 24;
    static constexpr int32_t     kKindInvalid = -1;
    static constexpr int32_t     kKindUDPv4   = 1;
    static constexpr int32_t     kKindUDPv6   = 2;

    int32_t kind{kKindInvalid};
    uint32_t port{0};
    std::array<uint8_t, 16> address{};

    bool operator==(const Locator& o) const noexcept {
        return kind == o.kind && port == o.port && address == o.address;
    }
    bool operator!=(const Locator& o) const noexcept { return !(*this == o); }

    // Appends the 24-byte little-endian wire encoding to out:
    // kind(4 LE) + port(4 LE) + address(16).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 24-byte Locator from data[0..len). Returns std::nullopt if
    // len < kSize.
    static std::optional<Locator> decode(const uint8_t* data, std::size_t len);
};

// ── ProtocolVersion / VendorId (RTPS 2.3 §9.3.3 / §9.3.4) ───────────────────

struct ProtocolVersion {
    uint8_t major{2};
    uint8_t minor{3};

    bool operator==(const ProtocolVersion& o) const noexcept {
        return major == o.major && minor == o.minor;
    }
};

// cpp-DDS's own vendor ID (unregistered, distinct from go-DDS's 0x01,0x27).
// Used only for locally-originated messages; interop test vectors always
// use go-DDS's kVendorIdGoDDS to pin cross-implementation byte compat.
struct VendorId {
    std::array<uint8_t, 2> bytes{};

    bool operator==(const VendorId& o) const noexcept { return bytes == o.bytes; }
};

// go-DDS's vendor ID (message.go: goVendorId = [2]byte{0x01, 0x27}).
inline constexpr VendorId kVendorIdGoDDS{{0x01, 0x27}};

// cpp-DDS's own vendor ID: unregistered (not an OMG-assigned vendor ID,
// same status as go-DDS's own 0x0127 — see message.go's "unregistered;
// 0x0127 = arbitrary" comment), used for locally-originated RTPS messages
// starting with Tier-1 phase 4 (SPDP). ASCII "cp" — arbitrary but
// memorable, and deliberately distinct from kVendorIdGoDDS. This field is
// purely informational on the wire (RTPS parsing does not gate on vendor
// ID); interop reference-vector tests still pin kVendorIdGoDDS explicitly
// where byte-exact match against go-DDS's own output is required.
inline constexpr VendorId kVendorIdCppDDS{{0x63, 0x70}};

// ── Header (RTPS 2.3 §9.4.1) ─────────────────────────────────────────────────

// Header is the fixed 20-byte RTPS message header, including the leading
// 4-byte "RTPS" magic.
struct Header {
    static constexpr std::size_t kSize = 20;
    static constexpr std::array<uint8_t, 4> kMagic{{'R', 'T', 'P', 'S'}};

    ProtocolVersion protocol_version{};
    VendorId        vendor_id{};
    GuidPrefix      guid_prefix{};

    // Appends the 20-byte wire encoding to out: magic(4) +
    // protocol_version(2) + vendor_id(2) + guid_prefix(12).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 20-byte Header from data[0..len). Returns std::nullopt if
    // len < kSize or the magic bytes don't match "RTPS".
    static std::optional<Header> decode(const uint8_t* data, std::size_t len);
};

// ── SequenceNumber (RTPS 2.3 §9.3.2) ─────────────────────────────────────────

struct SequenceNumber {
    static constexpr std::size_t kSize = 8;
    int32_t  high{0};
    uint32_t low{0};

    bool operator==(const SequenceNumber& o) const noexcept {
        return high == o.high && low == o.low;
    }

    // Appends the 8-byte little-endian wire encoding: high(4 LE) + low(4 LE).
    void encode(std::vector<uint8_t>& out) const;

    static std::optional<SequenceNumber> decode(const uint8_t* data, std::size_t len);
};

// ── SubmessageHeader (RTPS 2.3 §9.4.2) ───────────────────────────────────────

// submessage kind IDs (§9.4.5.1.1) — only DATA is needed at this phase;
// the rest are reserved here for phase 7 (reliable delivery).
inline constexpr uint8_t kSubmessageIdData      = 0x15;
inline constexpr uint8_t kSubmessageIdGap       = 0x08;
inline constexpr uint8_t kSubmessageIdHeartbeat = 0x07;
inline constexpr uint8_t kSubmessageIdAckNack   = 0x06;
inline constexpr uint8_t kSubmessageIdInfoTs    = 0x09;
// DATA_FRAG (§8.3.7.3), added for Tier-1 phase 8 ("Fragmentation" — see
// types.hpp's DataFrag doc comment below).
inline constexpr uint8_t kSubmessageIdDataFrag  = 0x16;

// flag bits for the DATA submessage (§9.4.5.3).
inline constexpr uint8_t kFlagEndianness = 0x01; // E: 1 = little-endian
inline constexpr uint8_t kFlagInlineQos  = 0x02; // Q: inline QoS present
inline constexpr uint8_t kFlagData       = 0x04; // D: serialised payload present

// SubmessageHeader is the common 4-byte prefix of every RTPS submessage:
// submessageId(1) + flags(1) + octetsToNextHeader(2, little-endian).
struct SubmessageHeader {
    static constexpr std::size_t kSize = 4;

    uint8_t  submessage_id{0};
    uint8_t  flags{0};
    uint16_t octets_to_next_header{0};

    bool operator==(const SubmessageHeader& o) const noexcept {
        return submessage_id == o.submessage_id && flags == o.flags &&
               octets_to_next_header == o.octets_to_next_header;
    }

    // Appends the 4-byte wire encoding to out.
    void encode(std::vector<uint8_t>& out) const;

    static std::optional<SubmessageHeader> decode(const uint8_t* data, std::size_t len);
};

// ── DATA submessage (RTPS 2.3 §9.4.5.3) ──────────────────────────────────────

// DataSubmessage holds the fields of a (non-fragmented, no-inline-QoS) DATA
// submessage — the subset go-DDS's marshalDataSubmessage/parseDataSubmessage
// support. Inline QoS and key-hash parameters are later-phase additions.
struct DataSubmessage {
    EntityId        reader_entity_id{};
    EntityId        writer_entity_id{};
    SequenceNumber  seq_num{};
    std::vector<uint8_t> payload; // empty <=> Data flag not set on decode

    // Builds the full submessage (4-byte SubmessageHeader + 20-byte fixed
    // body + payload) and appends it to out, matching go-DDS's
    // marshalDataSubmessage exactly: extraFlags(2)=0, octetsToInlineQos(2)=16,
    // readerId(4), writerId(4), seqNum.high(4 LE), seqNum.low(4 LE), payload.
    // Flags are always set to (kFlagEndianness | kFlagData), matching go-DDS
    // (inline QoS is not produced at this phase).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a full DATA submessage (header + body) from data[0..len).
    // Returns std::nullopt on malformed input (short buffer, wrong
    // submessage id, or a declared length that overruns the buffer).
    static std::optional<DataSubmessage> decode(const uint8_t* data, std::size_t len);
};

// ── HEARTBEAT submessage (RTPS 2.3 §9.4.5.7 / go-DDS message.go §9.4.5.5) ───
//
// Added for Tier-1 phase 7 ("Reliable delivery — HEARTBEAT/ACKNACK", see
// ROADMAP.md). C++ port of go-DDS's Heartbeat/marshalHeartbeat/parseHeartbeat
// (rtps/message.go). A reliable writer sends this after every write and
// periodically to advertise the sequence-number span still held in its
// history, so a reliable reader can detect and NACK gaps.

// Heartbeat holds the fields of a HEARTBEAT submessage.
struct Heartbeat {
    EntityId       reader_entity_id{};
    EntityId       writer_entity_id{};
    SequenceNumber first_sn{}; // lowest SN still in the writer's history
    SequenceNumber last_sn{};  // highest SN sent so far
    int32_t        count{0};  // monotonically increasing per writer

    // Builds the full submessage (4-byte SubmessageHeader + 28-byte body) and
    // appends it to out, matching go-DDS's marshalHeartbeat exactly:
    // readerEID(4) + writerEID(4) + firstSN.high(4 LE) + firstSN.low(4 LE) +
    // lastSN.high(4 LE) + lastSN.low(4 LE) + count(4 LE) = 28 bytes.
    void encode(std::vector<uint8_t>& out) const;

    // Parses a full HEARTBEAT submessage (header + body) from data[0..len).
    // Returns std::nullopt on malformed input.
    static std::optional<Heartbeat> decode(const uint8_t* data, std::size_t len);
};

// ── ACKNACK submessage (RTPS 2.3 §9.4.5.6 / go-DDS message.go §9.4.5.1) ─────
//
// AckNack holds the fields of an ACKNACK submessage. Matching go-DDS, this
// port uses a fixed single 32-bit bitmap word (NumBits always 32 on the
// wire) rather than the general variable-length SequenceNumberSet the OMG
// spec allows — go-DDS's own reliability window never needs more than one
// word, and this is a byte-exact port of that choice, not an independent
// simplification.
struct AckNack {
    EntityId       reader_entity_id{};
    EntityId       writer_entity_id{};
    SequenceNumber base{};   // first missing sequence number
    uint32_t       bitmap{0}; // bit N set => base+N is missing
    int32_t        count{0};

    // Builds the full submessage (4-byte SubmessageHeader + 28-byte body) and
    // appends it to out, matching go-DDS's marshalAckNack exactly:
    // readerEID(4) + writerEID(4) + base.high(4 LE) + base.low(4 LE) +
    // numBits(4 LE, always 32) + bitmap(4 LE) + count(4 LE) = 28 bytes.
    void encode(std::vector<uint8_t>& out) const;

    // Parses a full ACKNACK submessage (header + body) from data[0..len).
    // The numBits field is read but not validated (matching go-DDS's
    // parseAckNack, which always treats it as 32). Returns std::nullopt on
    // malformed input.
    static std::optional<AckNack> decode(const uint8_t* data, std::size_t len);
};

// ── GAP submessage (RTPS 2.3 §9.4.5.4) ───────────────────────────────────────
//
// Gap indicates a contiguous range of sequence numbers permanently
// unavailable from a writer (evicted from history before a NACK could be
// satisfied). Encode-only, matching go-DDS's marshalGAP: go-DDS never
// defines a parseGAP either (see rtps/message.go) — sent so a reliable
// reader *could* advance past a permanently-lost range, but not currently
// consumed by go-DDS's own receive path, and this port preserves that exact
// asymmetry rather than adding a parse path go-DDS itself doesn't have.
struct Gap {
    EntityId       reader_entity_id{};
    EntityId       writer_entity_id{};
    SequenceNumber gap_start{}; // first irrelevant SN (inclusive)
    SequenceNumber gap_end{};   // last irrelevant SN (inclusive)

    // Builds the full submessage (4-byte SubmessageHeader + 28-byte body)
    // covering [gap_start, gap_end] inclusive and appends it to out,
    // matching go-DDS's marshalGAP exactly: readerEID(4) + writerEID(4) +
    // gapStart(8) + gapList.bitmapBase(8, = gapEnd+1) +
    // gapList.numBits(4 LE, = 0) = 28 bytes.
    void encode(std::vector<uint8_t>& out) const;
};

// ── DATA_FRAG submessage (RTPS 2.3 §8.3.7.3) ─────────────────────────────────
//
// Added for Tier-1 phase 8 ("Fragmentation" — see ROADMAP.md). C++ port of
// go-DDS's DataFrag/marshalDataFrag/parseDataFrag (rtps/fragment.go): a
// payload too large for one submessage is split across multiple DATA_FRAG
// submessages, each carrying one fragment. Matching go-DDS's
// splitIntoFragmentsN, this port's own fragment producer (fragment.hpp)
// always sets fragments_in_submsg = 1 — the wire format itself allows
// packing more than one fragment per submessage, but no go-DDS producer
// ever does, so there is nothing to port for that case.
struct DataFrag {
    EntityId       reader_entity_id{};
    EntityId       writer_entity_id{};
    SequenceNumber writer_seq_num{};
    uint32_t       fragment_starting_num{0}; // 1-based index of the first fragment in this submessage
    uint16_t       fragments_in_submsg{0};   // number of fragments in this submessage
    uint16_t       fragment_size{0};         // size of each fragment in bytes (last may be smaller)
    uint32_t       data_size{0};             // total (unfragmented) data size in bytes
    std::vector<uint8_t> payload;            // raw bytes of the fragment(s)

    // Builds the full submessage (4-byte SubmessageHeader + 32-byte fixed
    // body + payload) and appends it to out, matching go-DDS's
    // marshalDataFrag exactly: extraFlags(2)=0, octetsToInlineQos(2)=0,
    // readerId(4), writerId(4), writerSeqNum.high(4 LE),
    // writerSeqNum.low(4 LE), fragmentStartingNum(4 LE),
    // fragmentsInSubmsg(2 LE), fragmentSize(2 LE), dataSize(4 LE), payload.
    void encode(std::vector<uint8_t>& out) const;

    // Parses a full DATA_FRAG submessage (header + body) from data[0..len).
    // Returns std::nullopt on malformed input (short buffer, wrong
    // submessage id, or a declared length that overruns the buffer).
    static std::optional<DataFrag> decode(const uint8_t* data, std::size_t len);
};

// ── Participant/entity identity allocation ──────────────────────────────────
//
// Added for Tier-1 phase 6 ("Entities & history cache" — see ROADMAP.md).
// C++ port of go-DDS's rtps/guid.go newGuidPrefix/entityIdForWriter/
// entityIdForReader. These are identity-allocation algorithms, not a fixed
// wire encoding, so there is no golden-vector byte-exactness requirement
// (unlike GUID::encode/decode above) — only the well-known entity-kind byte
// convention (0x03 = user-defined writer, no key; 0x04 = user-defined
// reader, no key) needs to match so peers correctly classify the endpoint.

// Generates a random GuidPrefix for a new participant: 8 random bytes plus
// the low 4 bytes of the process ID (so participants on the same host are
// distinguishable even if the random source is degraded), matching
// go-DDS's newGuidPrefix.
GuidPrefix new_guid_prefix();

// Returns a user-defined writer EntityId (kind byte 0x03 = no key) for
// ordinal n, matching go-DDS's entityIdForWriter.
constexpr EntityId entity_id_for_writer(uint32_t n) noexcept {
    return EntityId{{static_cast<uint8_t>(n >> 16), static_cast<uint8_t>(n >> 8),
                      static_cast<uint8_t>(n), 0x03}};
}

// Returns a user-defined reader EntityId (kind byte 0x04 = no key) for
// ordinal n, matching go-DDS's entityIdForReader.
constexpr EntityId entity_id_for_reader(uint32_t n) noexcept {
    return EntityId{{static_cast<uint8_t>(n >> 16), static_cast<uint8_t>(n >> 8),
                      static_cast<uint8_t>(n), 0x04}};
}

} // namespace dds::rtps
