// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// rtps/types.hpp — Foundational RTPS 2.3 wire types: GuidPrefix, EntityId,
// GUID (§9.3.1), Locator_t (§9.3.2), and message framing — ProtocolVersion,
// VendorId, Header, SubmessageHeader, SequenceNumber, DataSubmessage (§9.4).
//
// This is Tier-1 sub-phase 1 of the cpp-DDS RTPS roadmap (see ROADMAP.md,
// "Tier 1 — RTPS wire protocol", phase 1: "Wire types & framing"). It is
// internal, additive scaffolding: NOT yet wired into the public
// dds::IParticipant / relay::INode surface. That happens in a later phase
// once UDP transport (phase 3) and entities (phase 6) exist.
//
// C++ port of github.com/SoundMatt/go-DDS's `rtps` package, specifically
// guid.go, locator.go, and message.go (Header / DATA submessage framing
// only — HEARTBEAT/ACKNACK/GAP/INFO_TS are later phases). Every encode()
// here MUST produce byte-identical output to the corresponding go-DDS
// marshal function; see tests/test_rtps_types.cpp for the reference
// vectors (generated by literally calling go-DDS's own marshal functions —
// not re-derived by hand) that pin this.
//
// All multi-byte integer fields in RTPS 2.3 discovery/message framing are
// little-endian only (go-DDS never emits big-endian; see message.go's
// exclusive use of encoding/binary.LittleEndian and the always-set 'E'
// endianness flag). This port follows suit: no big-endian path exists.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <optional>
#include <vector>

namespace dds::rtps {

// ── GuidPrefix / EntityId / GUID (RTPS 2.3 §9.3.1) ──────────────────────────

// GuidPrefix is the 12-byte participant identifier.
struct GuidPrefix {
    static constexpr std::size_t kSize = 12;
    std::array<uint8_t, kSize> bytes{};

    bool operator==(const GuidPrefix& o) const noexcept { return bytes == o.bytes; }
    bool operator!=(const GuidPrefix& o) const noexcept { return !(*this == o); }
};

// EntityId identifies a specific endpoint within a participant.
struct EntityId {
    static constexpr std::size_t kSize = 4;
    std::array<uint8_t, kSize> bytes{};

    bool operator==(const EntityId& o) const noexcept { return bytes == o.bytes; }
    bool operator!=(const EntityId& o) const noexcept { return !(*this == o); }
};

// Well-known entity IDs per RTPS 2.3 Table 9.1 (go-DDS guid.go).
inline constexpr EntityId kEntityIdParticipant{{0x00, 0x00, 0x01, 0xC1}};
inline constexpr EntityId kEntityIdSPDPWriter{{0x00, 0x01, 0x00, 0xC2}};
inline constexpr EntityId kEntityIdSPDPReader{{0x00, 0x01, 0x00, 0xC7}};
inline constexpr EntityId kEntityIdSEDPPubWriter{{0x00, 0x00, 0x03, 0xC2}};
inline constexpr EntityId kEntityIdSEDPPubReader{{0x00, 0x00, 0x03, 0xC7}};
inline constexpr EntityId kEntityIdSEDPSubWriter{{0x00, 0x00, 0x04, 0xC2}};
inline constexpr EntityId kEntityIdSEDPSubReader{{0x00, 0x00, 0x04, 0xC7}};
inline constexpr EntityId kEntityIdUnknown{{0x00, 0x00, 0x00, 0x00}};

// Builtin endpoint availability bitmask (§8.5.4.3 / §9.6.2.2).
inline constexpr uint32_t kEndpointSPDPAnnouncer    = 1u << 0;
inline constexpr uint32_t kEndpointSPDPDetector     = 1u << 1;
inline constexpr uint32_t kEndpointSEDPPubAnnouncer = 1u << 2;
inline constexpr uint32_t kEndpointSEDPPubDetector  = 1u << 3;
inline constexpr uint32_t kEndpointSEDPSubAnnouncer = 1u << 4;
inline constexpr uint32_t kEndpointSEDPSubDetector  = 1u << 5;

// GUID globally identifies a DDS entity: participant + endpoint. Wire
// encoding is a plain 16-byte concatenation of prefix then entity — there
// is no endianness concern since it is raw byte copy in go-DDS too (GUID
// bytes are never treated as a multi-byte integer).
struct GUID {
    static constexpr std::size_t kSize = GuidPrefix::kSize + EntityId::kSize; // 16
    GuidPrefix prefix{};
    EntityId   entity{};

    bool operator==(const GUID& o) const noexcept {
        return prefix == o.prefix && entity == o.entity;
    }
    bool operator!=(const GUID& o) const noexcept { return !(*this == o); }

    // Appends the 16-byte wire encoding (prefix || entity) to out.
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 16-byte GUID from data[0..len). Returns std::nullopt if
    // len < kSize.
    static std::optional<GUID> decode(const uint8_t* data, std::size_t len);
};

// ── Locator_t (RTPS 2.3 §9.3.2) ──────────────────────────────────────────────

struct Locator {
    static constexpr std::size_t kSize    = 24;
    static constexpr int32_t     kKindInvalid = -1;
    static constexpr int32_t     kKindUDPv4   = 1;
    static constexpr int32_t     kKindUDPv6   = 2;

    int32_t kind{kKindInvalid};
    uint32_t port{0};
    std::array<uint8_t, 16> address{};

    bool operator==(const Locator& o) const noexcept {
        return kind == o.kind && port == o.port && address == o.address;
    }
    bool operator!=(const Locator& o) const noexcept { return !(*this == o); }

    // Appends the 24-byte little-endian wire encoding to out:
    // kind(4 LE) + port(4 LE) + address(16).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 24-byte Locator from data[0..len). Returns std::nullopt if
    // len < kSize.
    static std::optional<Locator> decode(const uint8_t* data, std::size_t len);
};

// ── ProtocolVersion / VendorId (RTPS 2.3 §9.3.3 / §9.3.4) ───────────────────

struct ProtocolVersion {
    uint8_t major{2};
    uint8_t minor{3};

    bool operator==(const ProtocolVersion& o) const noexcept {
        return major == o.major && minor == o.minor;
    }
};

// cpp-DDS's own vendor ID (unregistered, distinct from go-DDS's 0x01,0x27).
// Used only for locally-originated messages; interop test vectors always
// use go-DDS's kVendorIdGoDDS to pin cross-implementation byte compat.
struct VendorId {
    std::array<uint8_t, 2> bytes{};

    bool operator==(const VendorId& o) const noexcept { return bytes == o.bytes; }
};

// go-DDS's vendor ID (message.go: goVendorId = [2]byte{0x01, 0x27}).
inline constexpr VendorId kVendorIdGoDDS{{0x01, 0x27}};

// ── Header (RTPS 2.3 §9.4.1) ─────────────────────────────────────────────────

// Header is the fixed 20-byte RTPS message header, including the leading
// 4-byte "RTPS" magic.
struct Header {
    static constexpr std::size_t kSize = 20;
    static constexpr std::array<uint8_t, 4> kMagic{{'R', 'T', 'P', 'S'}};

    ProtocolVersion protocol_version{};
    VendorId        vendor_id{};
    GuidPrefix      guid_prefix{};

    // Appends the 20-byte wire encoding to out: magic(4) +
    // protocol_version(2) + vendor_id(2) + guid_prefix(12).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a 20-byte Header from data[0..len). Returns std::nullopt if
    // len < kSize or the magic bytes don't match "RTPS".
    static std::optional<Header> decode(const uint8_t* data, std::size_t len);
};

// ── SequenceNumber (RTPS 2.3 §9.3.2) ─────────────────────────────────────────

struct SequenceNumber {
    static constexpr std::size_t kSize = 8;
    int32_t  high{0};
    uint32_t low{0};

    bool operator==(const SequenceNumber& o) const noexcept {
        return high == o.high && low == o.low;
    }

    // Appends the 8-byte little-endian wire encoding: high(4 LE) + low(4 LE).
    void encode(std::vector<uint8_t>& out) const;

    static std::optional<SequenceNumber> decode(const uint8_t* data, std::size_t len);
};

// ── SubmessageHeader (RTPS 2.3 §9.4.2) ───────────────────────────────────────

// submessage kind IDs (§9.4.5.1.1) — only DATA is needed at this phase;
// the rest are reserved here for phase 7 (reliable delivery).
inline constexpr uint8_t kSubmessageIdData      = 0x15;
inline constexpr uint8_t kSubmessageIdGap       = 0x08;
inline constexpr uint8_t kSubmessageIdHeartbeat = 0x07;
inline constexpr uint8_t kSubmessageIdAckNack   = 0x06;
inline constexpr uint8_t kSubmessageIdInfoTs    = 0x09;

// flag bits for the DATA submessage (§9.4.5.3).
inline constexpr uint8_t kFlagEndianness = 0x01; // E: 1 = little-endian
inline constexpr uint8_t kFlagInlineQos  = 0x02; // Q: inline QoS present
inline constexpr uint8_t kFlagData       = 0x04; // D: serialised payload present

// SubmessageHeader is the common 4-byte prefix of every RTPS submessage:
// submessageId(1) + flags(1) + octetsToNextHeader(2, little-endian).
struct SubmessageHeader {
    static constexpr std::size_t kSize = 4;

    uint8_t  submessage_id{0};
    uint8_t  flags{0};
    uint16_t octets_to_next_header{0};

    bool operator==(const SubmessageHeader& o) const noexcept {
        return submessage_id == o.submessage_id && flags == o.flags &&
               octets_to_next_header == o.octets_to_next_header;
    }

    // Appends the 4-byte wire encoding to out.
    void encode(std::vector<uint8_t>& out) const;

    static std::optional<SubmessageHeader> decode(const uint8_t* data, std::size_t len);
};

// ── DATA submessage (RTPS 2.3 §9.4.5.3) ──────────────────────────────────────

// DataSubmessage holds the fields of a (non-fragmented, no-inline-QoS) DATA
// submessage — the subset go-DDS's marshalDataSubmessage/parseDataSubmessage
// support. Inline QoS and key-hash parameters are later-phase additions.
struct DataSubmessage {
    EntityId        reader_entity_id{};
    EntityId        writer_entity_id{};
    SequenceNumber  seq_num{};
    std::vector<uint8_t> payload; // empty <=> Data flag not set on decode

    // Builds the full submessage (4-byte SubmessageHeader + 20-byte fixed
    // body + payload) and appends it to out, matching go-DDS's
    // marshalDataSubmessage exactly: extraFlags(2)=0, octetsToInlineQos(2)=16,
    // readerId(4), writerId(4), seqNum.high(4 LE), seqNum.low(4 LE), payload.
    // Flags are always set to (kFlagEndianness | kFlagData), matching go-DDS
    // (inline QoS is not produced at this phase).
    void encode(std::vector<uint8_t>& out) const;

    // Parses a full DATA submessage (header + body) from data[0..len).
    // Returns std::nullopt on malformed input (short buffer, wrong
    // submessage id, or a declared length that overruns the buffer).
    static std::optional<DataSubmessage> decode(const uint8_t* data, std::size_t len);
};

} // namespace dds::rtps
